### ISSUE TITLE
3.20 beta stuck applying rules but Set Custom Script works

### ISSUE THREAD

**Issue by markd89** [ukanth/afwall#1006]
Hi,

Lineage 16/OP5/3.20 Beta

I have several custom scripts.

If I click Apply, I usually get stuck at "Applying iptables rules". 

Curiously, if I go to Set Custom Script and click OK, I see it counting through the rules and applying fine.

**Comment by CHEF-KOCH** [comment]
It might take a while to apply all your rules and that's why it's "stuck" even if it's not, the GUI update mechanism is not perfect.

Keep in mind that using too many rules might causes a race condition and it ends up aborting to applying the rules. This is a limitation of iptables itself. (Dunno how many scripts/rules you use).

**Comment by ukanth** [comment]
Fixed. 57bf5fa2f29742ce9a8fee617579783f8c6df11e
