### ISSUE TITLE
google services framework

### ISSUE THREAD

**Issue by dnd66** [ukanth/afwall#1026]
first of all, great app!  

Im new to all of this, so I do have two problems:

1. I blocked most apps ( including all google apps) apart of a select few, however google services framework is still transmitting data. how is this possible and how can I change this?

2. for startup data leak, which file do i need to choose? none of these seem to work:
core - service.d
magisk - service.d
adb - service.d

I appreciate any input!

**Comment by develBuzz** [comment]
> 
> 
> first of all, great app!
> 
> Im new to all of this, so I do have two problems:
> 
>     1. I blocked most apps ( including all google apps) apart of a select few, however google services framework is still transmitting data. how is this possible and how can I change this?
> 
>     2. for startup data leak, which file do i need to choose? none of these seem to work:
>        core - service.d
>        magisk - service.d
>        adb - service.d
> 
> 
> I appreciate any input!

1) If you allow play store / play services then there is no way to prevent it. Another leak is uid 1000 Android-System etc.). But if you know that it is leaking data, you probably know which process is responsible ,else try https://play.google.com/store/apps/details?id=org.secuso.privacyfriendlynetmonitorapp
2) maybe your kernel doesn't support init.d, try an app from f-droid/play store and in afwall+ choose the path that this tool requires. 

3) This function "issues" is used for bugs/errors/problems  in AfWall+ and not for handling and newbie questions. 
Better go to a forum to ask that questions next time: 
https://forum.xda-developers.com/showthread.php?t=1957231

**Comment by dnd66** [comment]
thank you for your inputs and I apologize for posting it in the wrong forum.

In this case I would like to report an error, because google services framework is leaking and because there is a tethering error if afwall is activated:

all i have activated is norton, threema, firefox, my banking app and uid -13 for tethering.

however tethering does not work when -13 is activated so I had to add this custom script:

#!/system/bin/sh

IPTABLES=/system/bin/iptables
IP6TABLES=/system/bin/ip6tables

$IPTABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 67 --dport 68 -j RETURN
$IPTABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 53 -j RETURN
$IPTABLES -I afwall-wifi-tether -p tcp -m owner --uid-owner 1052 -m tcp --sport 53 -j RETURN

$IP6TABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 67 --dport 68 -j RETURN
$IP6TABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 53 -j RETURN
$IP6TABLES -I afwall-wifi-tether -p tcp -m owner --uid-owner 1052 -m tcp --sport 53 -j RETURN

As none of my apps can cause the frameworks leak it must be related to uid -13 or the custom script which I had to add to make tethering work.

**Comment by develBuzz** [comment]
1) For the tethering issue see:
https://github.com/ukanth/afwall/issues/924 or https://github.com/ukanth/afwall/issues/965
I guess you got the solution from this thread. No need for a new ticket. Maybe you add a comment there. 

2) Leaking data: 
If you use threema from play store it is surely using GCM (Google Cloud Messaging), for getting new messages, infos. and therefore using GSF . A lot of other apps use this too, so this might already explain the connections. 

If not, there are so many possibilities why data is send, that it is nearly impossible to give a good advice to solve it with that little information. 4 things which might help here:

a) Which network connections does NetMonitor show? 
https://play.google.com/store/apps/details?id=org.secuso.privacyfriendlynetmonitorapp
Under history you can even select, which apps should be loged. 

b) Take a look at your rules: AFWAll Menu => "Show rules". Are there rules which fit to the network connections? 

c) AfWall+ just adds a chain of rules to iptables (depending on your settings in the app). Each other tool with the right to edit iptables (every root-app might) can add own rules to allow traffic. 

added:
d) See https://github.com/ukanth/afwall/issues/352 for more information about google apps. 

And with your confguration you could not even download with firefox or most other apps, because download-manager is not allowed. 


If your issue is solved, please close it here.

**Comment by ForestCat4** [comment]
With everything blocked in AFWall, there is still network activity from the phone's MAC Address over WiFi.  It can be seen/monitored in Wireshark.
Do you have documentation on EXACTLY what types on network activity AFWall/iptables are unable to block?, ie, Android System, Google Framework, etc?
Samsung Note4 on Verizon, Stock 6.0.1
Thank you.
