### ISSUE TITLE
Android 10 logs are not working

### ISSUE THREAD

**Issue by Hoiss** [ukanth/afwall#1032]
Hi there,

I just installed afwall on a magisk rooted oneplus 7t with android 10 and have problems with getting any logs.
Firewall is enabled and "Turn on log service" is activated. Also the toasts are activated. But unfortunately I can't get any log which apps have been blocked. But it seems afwall is working, because apps which aren't allowed also do not have access to the internet.
A very confusing situation, any tips how to solve this? (It's really hard to find the minimum afwall permissions without logging the accesses of the apps)

**Comment by ukanth** [comment]
Please share the rules with log messages from menu-show rules-export

**Comment by Hoiss** [comment]
[IPv4rules.log](https://github.com/ukanth/afwall/files/3835227/IPv4rules.log)

**Comment by ukanth** [comment]
Fixed it in 3.3.0

**Comment by muello** [comment]
I'm encountering something similar to the issue described above. Android 10 on a Samsung phone. I flashed the firmware today and, after setting up Magisk, installed AFWall+ first thing. Activated toasts and log service. Both worked for a while, then stopped. I repeated the flash and install and they were working again, but have since stopped again. The firewall is working; unblocked apps have access to the internet and blocked apps are blocked.

**Comment by muello** [comment]
Perhaps I should add: it's not just the logs; I'm not getting any toast notifications either.

**Comment by Hoiss** [comment]
It's the same for me for months already.
My workaround is to explicitly disable the log and save that, then enable it again. It then will work for a while... Most times enough for further analysis.

**Comment by muello** [comment]
Ah, that works for me too. Thanks for the tip.
