### ISSUE TITLE
AFWall+ V3.3.0 blocks NOTHING

### ISSUE THREAD

**Issue by HagenTronje** [ukanth/afwall#1040]
OnePlus 7 with Android 10 and Magisk 7.4.1

Today i updated from V3.0.2 to V3.3.0. Afterwards none of my profiles stopped networktraffic.

So i went to settings, stopped AFWall+, cleared cache and app-data.

Then i started AFWall+ again and enabled it, checked that "Allow selected" was selected and that in the applied profile no app was enabled on any connection (LAN, Mobile, ...) but still ALL apps had free access to the network.

I switched back to V3.0.2 which so far works fine for me.

In the last 7 years i used AFWall+ (and its predecessor) on quite a few devices and i really love this app and appreciate it. However such behavior is quite embarrasing.

**Comment by ukanth** [comment]
Allow/Block "Clat" from system app depends on the profile for Android 10. If not please send me error log from menu-firewall rules-export.

**Comment by HagenTronje** [comment]
"Allow/Block "Clat" from system app depends on the profile for Android 10."

Sorry, i'm lost! Please could you be more explicit on what i should do?

Please remember:
V3.3.0 currently does not block any traffic on my device so it exposes me completely and i would really like to avoid this.

**Comment by abesty** [comment]
Same problem in here

**Comment by ukanth** [comment]
Without details , I can't fix or even look into it. 
https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug

**Comment by Hoiss** [comment]
I also use OnePlus7with android 10 and don't run into this issue, that's weird. But I also didn't upgrade to the latest OS update yet (got the info a few days ago)
Power saving (battery optimization) is disabled for afwall? You already tried to uninstall and reinstall it again? 
Otherwise send him the rules export!

**Comment by lolorc** [comment]
does it work if you disable the log service ?
see https://github.com/ukanth/afwall/issues/1035 that has been closed without reproducing & testing.

**Comment by wwwilq** [comment]
The same problem with me.   Version 3.3.0 blocks NOTHING.  Observed both on Android 8 Oreo (Resurrection Remix, Magisk 20.1) and on Android 9 Pie (Havoc, Magisk 20.1).   Version 3.1.0 works fine on both.

**Comment by ukanth** [comment]
again, Without details , I can't fix or even look into it.
https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug

**Comment by jw243** [comment]
Same on my device! Nothing is blocked at all! How can this happen?

MotoX4
LineageOS 16.0 microG
Magisk 20.1

**Comment by lolorc** [comment]
guys, do you have an error when applying rules ?
what's afwall+'s status ?
does it happen if log service is disabled ? (see https://github.com/ukanth/afwall/issues/1035)
if so, what's does it say when trying to enable log ?
If it's the same issue I'm encountering afwall+ disables the firewall because there's an issue when applying the rules (with a LOG rule)


there're 2 things here:
- issue with the log service
- afwall+ should not stop applying rules if an error occurs (especially if it's only an issue with a LOG rule)

**Comment by ukanth** [comment]
Here is the build with patch from @nxzero. Please let me know if this fixes the issue.

https://www.dropbox.com/s/w1mq5ankjkqsa52/AFWall%2B_3.3.1-TestBuild1.apk?dl=0

**Comment by HagenTronje** [comment]
> Here is the build with patch from @nxzero. Please let me know if this fixes the issue.
> 
> https://www.dropbox.com/s/w1mq5ankjkqsa52/AFWall%2B_3.3.1-TestBuild1.apk?dl=0

Thank you !!!

As far as i can see at the moment AFWall+_3.3.1-TestBuild1.apk works fine on my OnePlus7 (Oxygen OS 10.0.1.GM57BA).

Great work! Thank you very much indeed!!!

**Comment by ukanth** [comment]
Thanks. I've released a minor version with this fix.

**Comment by jw243** [comment]
Version 3.3.1 works for me as well. It blocks what it should and log service logs again, after it hadn't been working in the last two vor three versions. Thank you very much.
