### ISSUE TITLE
show logs crashes 

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#1067]
when opening view log, afwall crashes with a stack trace mentioning that path needs to be convex.
sorry, no more information, android feedback gui is does not allow for copying text out of it

**Comment by irontechmonkey** [comment]
I had been experiencing this for some time but been slow to report. Thanks @ NESC1US for creating the ticket. Until now any attempts to view log caused FC consistently but as I was about to log it again in Beta 40 there has been an interesting change in behaviour and possible confirmation of sub- hypothesis; That viewing log FCs only after there are some entries in the log.

- Immediately after update attempts to view log caused FC.
- Disabled logging then entered logging panel, cleared log.
- Enabled logging.
- No FC when viewing log but this is still consistent with hypothesis since there were no entries in log.
- Preferences > Logs> Log target (change from NFLOG to LOG (note there seem to be NFLOG choices)
- Viewed log successfully again which still had no entries as nothing had been blocked.
- Blocked all apps to induce logging and toasts. 
- Now logging working as implied by toasts but attempt to view log FCs
- Toggling between NFLOG to LOG does not stop the FC.

Attached logcat contains same fatal exception described by NESC1US
01-24 15:47:54.857 D/AndroidRuntime(19615): Shutting down VM
01-24 15:47:54.858 E/AndroidRuntime(19615): FATAL EXCEPTION: main
01-24 15:47:54.858 E/AndroidRuntime(19615): Process: dev.ukanth.ufirewall, PID: 19615
01-24 15:47:54.858 E/AndroidRuntime(19615): java.lang.IllegalArgumentException: path must be convex

In attached rules file local IP addresses have been redacted.
 
... if I am able to attach them. Saving ticket as is for now.

[EDIT] Logs attached. Device is Moto X4, LOS 15/Oreo, Magisk (multiple versions). 

Also, please note: A different Github ticket for "Log service not working" (https://github.com/ukanth/afwall/issues/1065) may be related to this issue or at least to the one part of this issue where changing  Preferences > Logs> Log target  from NFLOG to LOG induced logging... tereby taking us to the next test of FC.

[AfwallLogFC-IPv4rules.log](https://github.com/ukanth/afwall/files/4112243/AfwallLogFC-IPv4rules.log)

[AfwallLogFC2020-01-24-15-48-07.txt](https://github.com/ukanth/afwall/files/4112244/AfwallLogFC2020-01-24-15-48-07.txt)
