### ISSUE TITLE
Firewall not blocking

### ISSUE THREAD

**Issue by r4taw2mg** [ukanth/afwall#1097]
I was surprised to finde an app (feeder) being able to load RSS feeds via the internet without being allowed within the firewall (boxes unchecked).

The were no entries in the log.

AFWall+ 3.4.0, Samsung S7 running Android 8 on stock.

**Comment by r4taw2mg** [comment]
It seems, like no traffic is blocked at all. Restarting the phone, toggling the app, nothing worked. I am really puzzled, as I thought, this way of blocking was secure.

I am using an always on VPN (via OpenVPN).

**Comment by irontechmonkey** [comment]
> It seems, like no traffic is blocked at all. Restarting the phone, toggling the app, nothing worked. I am really puzzled, as I thought, this way of blocking was secure.
> 
> I am using an always on VPN (via OpenVPN).

@r4taw2mg FYI the symptoms you describe are the same as what would occur when using VPN without correct configuration in Afwall. Since this github page is for reporting bugs and you may just be experiencing a previously documented configuration issue you should consider going to the AFwall XDA thread. Note: I don't speak for the developer but I do know from personal experience configuring AFwall in my own VPN that this may not be a bug and you may find answers there.

**Comment by r4taw2mg** [comment]
@irontechmonkey Thank, you that was a pointer in the right direction. I switched to the display of the VPN column, that allowed me to auccessfully control traffic via VPN. Still I do not find it very intuitive. I would have expected to control all traffic with few options shown (a kind of inheritance).

**Comment by irontechmonkey** [comment]
> @irontechmonkey Thank, you that was a pointer in the right direction. I switched to the display of the VPN column, that allowed me to auccessfully control traffic via VPN. Still I do not find it very intuitive. I would have expected to control all traffic with few options shown (a kind of inheritance).

Your welcome. I'm no expert but happen to use similar settings. I've not had time to reply to your post at XDA but will share the details of my configuration there soon.
