### ISSUE TITLE
[ISSUE] Crash

### ISSUE THREAD

**Issue by oguz72** [ukanth/afwall#1110]
**Describe the bug**
When ever apply ant rule Afirewall stops and that rule dosn't works. After that app can not starts. Of I Clear app Data it opens again.

**Firewall Logs**
No data because I need To Clear data to open it.

**Smartphone (please complete the following information):**
 - X96 tvbox
 - Android OS: 6.0.1

**Additional context**
Rooted device, and it was working before update.

**Comment by setuidroot** [comment]
I have experienced a similar issue as this, but I cannot reproduce it right now.  I had this issue happen on Lineage-based Android 9 ROM with AFWall version 3.3.1.  I still have 3.3.1 installed despite version 3.4.0 being available... I don't like to update it much because I don't like to run without it (even for short periods of time.)  But I will see if I can reproduce this issue with the latest version of AFWall+.

I also have H96 Pro+ TV box on Android 6.0.1... crappy phone ROM on decent hardware TV box.  The stock ROM is just terrible... but I've rarely had issues with AFWall on it (except the issues I get which require reboot like when the mouse cursor disappears.)

I would suggest rolling back the version of AFWall that you are using because these latest versions have changes to support newer Android (9 and 10) which you don't need (and may conflict/cause issues on older Android 6.)

Can you **consistently** reproduce this issue?  Or does it just happen occasionally?  I've also found that only the default (the first of four) profile spots work (apply correctly) for me; if I use a different profile (regardless of its settings) then the firewall rules will not apply.

**Comment by ukanth** [comment]
Please provide logcat logs https://www.youtube.com/watch?v=W6iDw76UpQw 
Without logs it's not easy to understand the problem.

**Comment by oguz72** [comment]
Problem was mostly consistent, just some times after a restart it wasn't happened for a while . Right now I have installed 3.3.1 and disabled auto update, it works normal. I'll try logcat and  to provide more info.
