### ISSUE TITLE
[FEATURE] Repack AFWall+ with new packetname

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#1111]
**Is your feature request related to a problem? Please describe.**
I've a problem with some Banking apps. If I've AFWall installed the Banking Apps stop working.

**Describe the solution you'd like**
By uninstalling the app AFWall+, the Banking app are working again.

**Describe alternatives you've considered**
Is it possible to repack AFWall with a new name, so the Banking app cannot "see" AFWall+?
Magisk Manager has this feature....

May you consider this feature in upcoming builds?

**Comment by setuidroot** [comment]
Hmm is it possible to build AFWall+ with a different package name you ask?  Well, I don't know if I'm qualified to answer this (but nobody else has so I will.)

You could decompile the app and try to recompile it with a different package name... only the developers have access to the source code to compile apps though 🤔.

Oh wait... I forgot this whole project is open source; anybody can compile it (especially with the help of their instructions here: https://github.com/ukanth/afwall/wiki/HOWTO-Compile-AFWall )

So really the answer to your question can only be answered by you... are you willing to put a bit of time into setting up a dev environment and building this open source app?  If you are, I applaud you and I firmly believe you will learn some useful things on your journey.  If the answer is no... then maybe find somebody willing to compile a binary for you (I would do it, but probably not for free because I'd have to rent some server power to build it... unless you have a decent ~8 core CPU and can setup Ubuntu and TeamViewer.  My computer is less than 25% as powerful as my phone's CPU and it uses ~18x more power.)  

But beware anyone offering you a binary build... anyone (myself included; I wouldn't... but you don't know that) could add some malicious code to the app build (and that'd be too easy since this app runs as root... you could get infected with something deep and near undetectable, although chances are it would just be simple adware and/or a cryptominer while device is plugged in 🤔.)  Cryptominer will kill your battery pretty quick though (I know from experience willfully mining on old Android phones.)  Battery will start to bloat after a few months (which could cause battery puncture and possible fires in cramped devices like Samsung's infamous Note 7 devices.  Not to mention malware apps with root could (rather easily) inject a trusted SSL/TLS certificate into the system and use it to decrypt all of your SSL encrypted sites (ie steal all your login info.)  

I recommend you read info on how to build Android apps and build AFWall+ yourself from the source code here on github.  I am happy to answer any serious questions you have about building the app from source.  Otherwise I'm happy to post sarcastic answers to lazy (or ignorant) questions like this one.

I am **not** at all associated with the AFWall developers (I'm not good enough to be useful anyways.)  But when you ask things like this: "May you consider this feature in upcoming builds?"

It makes unpaid open source developers feel like this: "Maybe you should buy the donate version of AFWall+ (it has a different name BTW) to show your appreciation for all of our hard dev work on this app over the years."  And then the devs feel like people don't appreciate them and then they tend to disappear for awhile.  Again I'm not associated with the devs (I don't even know them.)  But questions like this aren't good for morale (just put yourself in their shoes... you get paid nothing to maintain this app just to have people ask you for custom binary builds expecting you to do something **more** for them for free 🤔.)

Anyways... I just wanted to point out that these guys work hard on this project for next to nothing (other than requests for more unpaid work.)  Often people don't donate because everybody thinks (oh, somebody else donated already... well that "somebody else" thought the same thing of you 🤔.)  Plus I wanted to point out that you can build this app yourself with whatever name you want.

The donate version (here: https://play.google.com/store/apps/details?id=dev.ukanth.ufirewall.donate ) it does have a different name (but only with .donate on the end of it... whether or not that would fool your banking apps depends on how they detect AFWall.)  My guess is it wouldn't fool them because they probably search for an app with a string containing "ukanth" and/or "firewall" in the name.  It is also possible that they are detecting it by using the "ls bug" (a bug in the ls binary which leaks information about a file's existence.)  

This ls binary bug happens because if you run "ls" on an existing (even without read permission) directory (like /data/data/dev.ukanth.ufirewall) then it will return: "Permission denied" if the directory exists; while it will return "No such file or directory" if it does not exist.  So if they're using this ls data leak on the directory "/data/data/dev.ukanth.ufirewall" then the donate app (that would be in "/data/data/dev.ukanth.ufirewall.donate" instead) might not be detected if the bank apps are not explicitly looking for it.  It is also possible that they're using this ls data leak bug to search for existence of the iptables binaries needed for this app to work.

The Android system comes with an iptables binary by default... so this means that everything you can do with AFWall+, you can also do from the Android terminal shell using the system's iptables binary (requires root, which obviously you already have.)  It isn't as easy to use (no pretty GUI like AFWall) but if you learn the iptables commands, you can manually apply all of the same iptables rules from a root shell.  AFWall actually shows you all of the iptables rules it uses if you click "Show rules."  Just copy these rules and apply them manually with iptables.


Why do you want to use AFWall with bank apps anyways?  Is it so you can force all apps to only use a VPN?  (That is what I use AFWall for... to make sure nothing leaks out of my VPN and to block internet access to most of my apps when I'm not using them.)  I only ask because if you are trying to cheat the bank apps: just take my word for it and do not bother.  It won't work ultimately and it's easy to trace back to your device.  I assume you are not trying to pull anything and that you just want to control the device you rightfully own, in which case I support you.

**Edit**: After rereading your question... is it possible the banking apps don't work because you haven't expressly granted them internet permission in AFWall?  I assume you would already have ruled this out, but I shouldn't assume anything.
