### ISSUE TITLE
Doesn't block 3g traffics on some devices

### ISSUE THREAD

**Issue by username39** [ukanth/afwall#197]
I'm using Samsung Galaxy Tab(SHW-m180L, Korean CDMA EV-DO variation).

My device uses ppp for 3g connection, so I had to add following script:
> $IPTABLES -A "afwall" -o ppp+ -j "afwall-3g" || exit

Found [this](https://github.com/skullone/android_firewall/issues/37) from skullone's repository. It seems Samsung Epic 4g also uses ppp.

If ppp should remain in VPN chain, I think some detection codes or at least warning message is essential for end users.

**Comment by CHEF-KOCH** [comment]
Is this issue still present?

**Comment by username39** [comment]
I'm sorry that I can't test on this device anymore.

**Comment by CHEF-KOCH** [comment]
Please close this ticket and re-open another ticket if that happens again. Of course do a search for closed/opened tickets before you do this.

I guess this was fixed with 1.2.4x+. On some systems and configurations the <code>|| exit</code> stuff needs to be removed to solve this, if not you get an error msg with -4 or without anything. 

Thanks.
