### ISSUE TITLE
Spawns a lot of 'su' processes, even with system busybox

### ISSUE THREAD

**Issue by 80tf3262p8** [ukanth/afwall#315]
I saw in a recent development thread post that work is being done to fix the problem with 'su' processes, so I am glad for this.  I also saw someone say that selecting the 'system' busybox works perfectly.  This is not the case for me and if it helps at all, it doesn't help much.

EDIT: Log link: https://github.com/80tf3262p8/attached/blob/master/rules.log

![sususususu](https://cloud.githubusercontent.com/assets/7275539/4299117/8e97d96e-3e31-11e4-96d9-7a1e0a31d837.png)

**Comment by 80tf3262p8** [comment]
Sorry, still happening. New phone now (VS985), Android 5.0.2 (ParanoidAndroid alpha). ~80 su processes with AFWall+ UID, ~80 tmp-mksh. Phone has 3GB of memory and runs out.

I don't see the relationship between the SetCPU issue and this issue -- closest is chainfire's statement "I have noticed that SetCPU creates su sessions from different processes at various times" -- but nobody said that it was flooding their system with su processes like AFWall+ does. There's also nothing in the SuperSU Changelog about a fix for an issue like this, near 2.24 or anywhere else.

Because I've had trouble getting AFWall+ to apply its rules at startup, and wasn't sure if it was erroring at other times as well, I made some Tasker profiles to disable and re-enable AFWall+ every couple of hours (refresh it, waiting 1 second in-between off and on -- too short?), after startup, and after connectivity changes (waits a few seconds first). If AFWall+ had a State for being enabled or not, I could make use of that, but it doesn't.

I need my phone to be stable the next few days, so I'm turning off notifications, but after that I'll turn them back on and try disabling all of my Tasker-related interactions with AFWall+ except the Device Boot event to see if that helps. This problem shouldn't be happening either way. I'll definitely report if the problem continues *after* turning notifications off, since that'd be a new one, or anything else I find out. But it's not over... :-( I don't often NEED the notifications, but there's still a bug somewhere.

**Comment by ukanth** [comment]
I will look into it with the next release

**Comment by CHEF-KOCH** [comment]
> but nobody said that it was flooding their system with su processes like AFWall+ does.

Not true, please read the whole story (over 20+ pages) which shows exactly the same overlay as mentioned in AFWall+.

> There's also nothing in the SuperSU Changelog about a fix for an issue like this, near 2.24 or anywhere else.

It's like all changelog, some things are never mentioned even if it's fixed. Important is the change in the source and SuperSU was massive re-written during the last 4 months. 

You use a system which is new, so what did you expect? Did you tested it with an older Android version? No, so why you complain about it? ...

Sorry that is a SU problem and not an AFWall+ problem, we only need to wait until Chainfire is fully done with the Android 5.x optimization and need to adjust our code to latest SU (Play Store and not Beta releases).

**Comment by 80tf3262p8** [comment]
Thank you for agreeing to look into this, ukanth.

CHEF-KOCH, I have read through the 32 pages containing the term "SetCPU" in the XDA thread and apparently my reading comprehension and/or vision are not as good as yours. Since you possess such superior skills, maybe you can provide a link...?

However, I'm actually having other issues with AFWall+ on the new system that make this one seem silly, so I'll no longer be following this thread. I also have to reverse my claim that AFWall+ was responsible for eating up my RAM. That was false! AFWall+ creates a ton of processes, but the RAM issue is something else. Like you said, CHEF, new systems have issues.

**Comment by CHEF-KOCH** [comment]
Maybe you watched the wrong thread, there is a SuperSU beta and a normal thread. I think this was in the normal thread, several times mentioned with a screenshot which shows the "spam" overlay behavior. Sure, I can re-link to it but that wouldn't change some facts about the SU changes last months (for exaple ACCESS_SUPERUSER was removed from SuperSU) and that you use a alpha version according to your given info -> ParanoidAndroid _alpha_. 
And a last note about SU integrated in some roms, some of them replaced in the past chainfires SU with the "old" but stable one -> because of some "crazy" problems (maybe this is one of them). The roms I talking about was SLIM, PARANOID, CARBON and such ... I also can give you some proof if you don't believe but that also wouldn't change something here. 

> .... that AFWall+ was responsible for eating up my RAM .... That was false! ....

Please provide some logs or screenshot. I usually test such things quickly with 3CTool (aka Android Tuner Pro) in the past (see also WIKI ~ without looking I think I wrote there 5 up to 10 MB) and it only takes 5 to max 15 MB (non shared) here with the latest AFWall+ alpha which is not good but okay. Maybe there are some memory leaks you talking about, but without anything it's difficult to say but I think you know that. 

This is really the last time I say that people with alpha/beta roms should first ask there rom devs how to identify there problems, it's also written down in the wiki ... big fat ... no eta support.
The problem is that if su gets another update or the rom gets another change we now face the same problem again and again or there will be some new which are not AFWall+ related. 

Maybe someone or I test if that can reproduced with kosh's superuser.apk.
