### ISSUE TITLE
AFWall constantly running

### ISSUE THREAD

**Issue by mikolino** [ukanth/afwall#328]
I've noticed that afwall remains in the background as a service. If I kill it it will eventually respawn itself.

I disabled anything that could need a service in my mind: logging, active rules, lan/vpn/roaming.

I do not have such issue with other droidwall forks, and I can't see a reason why an iptables frontend would need to keep running after applying the rules.

It is an issue on my device because I have very low ram (384MB) and afwall basically wastes ~25MB.

If it's not a bug can someone tell me why it keeps running?

Thanks

**Comment by mikolino** [comment]
If you tell me it needs to run in the background for active rules, then I really don't see how it is NOT a bug since I disabled them? If active rules are mandatory why are they even an option? Maybe your ROM flushes the rules on connectivity change, but mine doesn't.

Saying that it's "special" because it targets a newer android API is also bullshit, as newer API dispatch a "connectivity change" broadcast that afwall could listen for instead of running all the time!

Also note: I didn't compare directly to Droid wall, I think you skipped the word "forks" here. While afwall+ is the most popular these days, it is not the only fork out there...

**Comment by ukanth** [comment]
@mikolino, The current design of AFWall+ keeps a service which will be running in the background regardless of "Active Rules" to avoid afwall being killed by android. 

It supposed to stop the service if the active rules are disabled. There were few request's regarding the same (disable the service if no active rules). I'll keep this open till if anything else can be done in order to support both behavior.

Thanks

**Comment by CHEF-KOCH** [comment]
> Saying that it's "special" because it targets a newer android API is also bullshit, as newer API dispatch a "connectivity change" broadcast that afwall could listen for instead of running all the time!

Please be friendly. 
It's not bullshit, killing Android apps is a widly known myth and mostly ends up with long discussions. Yes it's dependency which API. Killing apps in Android 4.x is harder then with 3.x. If you don't like the GUI you can use the terminal or a script with the autoscript app. Problem solved. [Killing apps does not safe battery life](http://www.androidauthority.com/the-myth-about-android-application-task-killers-revealed-7655/).


> If you tell me it needs to run in the background for active rules, then I really don't see how it is NOT a bug since I disabled them?

Well, the thing is that the mentioned behavior need AFWall+ running in the background or start the service again (if closed). Since AFWall+ does not need much RAM or CPU usage I think there is no need to add an exit button. It's a "security" app, or did you entirely disable your AV/Firewall on Windows/Linux too if your RAM is low? Makes no sense.
And another thing is that some external apps like Locale/Tasker may also check if the service is running or not, which would be break some features if you gonna to completely shutdown all service.

Personally I would remove that button to not confuse the people. Even a 6 years old phone can handle AFWall+ in fact starting/stopping/starting/stopping the service would coust more CPU cycles.
