### ISSUE TITLE
LAN Broadcast packets go through afwall-wifi-wan like a WAN traffic

### ISSUE THREAD

**Issue by DVitalie** [ukanth/afwall#340]
I allow my app to use only LAN Network
But broadcast packages was tropes

AFWall+ Log
AppID :	10110
Application's Name:	Qloud Media Free
Total Packets Blocked:	4
[UDP]239.255.255.250:1900(4)

	---------

IPTables Rules
Chain afwall-wifi-fork (2 references)
  pkts bytes target     prot opt in     out     source               destination
  916 29966 afwall-wifi-lan  all  --  *      *       0.0.0.0/0            192.168.1.0/24
  3293  380K afwall-wifi-wan  all  --  *      *       0.0.0.0/0           !192.168.1.0/24      

Maybe to add rule
  afwall-wifi-lan  all  --  *      *       0.0.0.0/0            239.255.255.250
Will resolve issue?

**Comment by CHEF-KOCH** [comment]
As mentioned [here](https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug) we need more information, like OS, iptables, busybox, AFWall+ version.... to reproduce the problem.

**Comment by cris-** [comment]
I'm having the same problem with Yacc (http://www.yaacc.de/) and other upnp/dlna applications when they are only allowed to connect to LAN.
The problem is that the SSDP discovery broadcast communication to multicast addresses (see https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol) gets blocked when the application is only allowed to connect to LAN: if the application is allowed to connect to WIFI/WAN then the discovery works.
It would be nice to have a special rule or a custom script (like for tethering, adb, etc.) to enable such communication without having to grant the applications full wan access.

**Comment by ukanth** [comment]
This can be done using custom script.
