### ISSUE TITLE
[Feature Request] Favourite apps

### ISSUE THREAD

**Issue by brtpnc** [ukanth/afwall#341]
I propose a feature to "pin" the app to the top of the list in the GUI - outside of normal alphabetical order. That will make it easier for the user to find his commonly modified apps without needing to scroll for them. It might be implemented as an additional "Favourite" button on "Traffic details" screen that shows when application name is long-pressed (under "Open system details").

**Comment by ukanth** [comment]
Could you explain the commonly modified apps? Why not use search ?

**Comment by rootbeam** [comment]
Commonly modified apps as in apps that are often allowed or disallowed (e.g. Google Play Store and Download Manager in my case). Being able to pin apps you often change to the top is quicker, less repetetive and more useful than search.

**Comment by CHEF-KOCH** [comment]
The benefit from such option would be to "faster" find and edit the app settings but this can already be done with:
a) a custom script (via uid, name,...)
b) the tasker plugin to automatically apply these steps on certain situations like connectivity change or a rom update
c) using init.d scripts (once at boot)
d) search option

I don't see any benefit to include such feature, because not all people need to change the app statements very often, normally only once. So this is only for power users and they normally know how to handle mentioned a - d cases. Other apps I know also not have such pin-to-top option, "only" a search option and nobody complains about it, because as written, you normally not change such apps daily or weekly.

**Comment by CHEF-KOCH** [comment]
I think we can close it, nobody else want it and as I already said we have the _search_ + _scroll_ +_uid/time_ options to deal with it. Not even Xprivacy or other apps have an 'pin' option, because that makes a lot of more troubles, the time we spent to implement it could be investigate to harden other security aspects.

**Comment by Efreak** [comment]
Not arguing for or against here (I have no need for it anyways), but you can't really compare with XPrivacy and Privacy guard; you can create external links that launch the settings ui of both apps open to the settings for any given app. They might not implement the functions themselves, but it's trivial for others to implement (see xbridge xposed module).

An alternative might be to provide an intent consumer for blocking/unblocking apps (with some kind of confirmation feedback to prevent apps from doing it silently), or to allow widgets for specific apps.

Edit: looks like alternative already exists, ignore that...

**Comment by CHEF-KOCH** [comment]
I think we can just close it, due the reasons I've said and Efreak.
