### ISSUE TITLE
Traffic Details 

### ISSUE THREAD

**Issue by muoner** [ukanth/afwall#343]
hello,

I use AFWall (White list) and use the follow custom script:

IPTABLES=/system/bin/iptables
IP6TABLES=/system/bin/ip6tables 

$IPTABLES -F INPUT
$IPTABLES -F FORWARD
$IPTABLES -t nat -F
$IPTABLES -t mangle -F
$IP6TABLES -F INPUT
$IP6TABLES -F FORWARD
$IP6TABLES -t nat -F
$IP6TABLES -t mangle -F

$IPTABLES -X 
$IPTABLES -t nat -X 
$IPTABLES -t mangle -X 
$IP6TABLES -X 
$IP6TABLES -t nat -X 
$IP6TABLES -t mangle -X

$IP6TABLES -P INPUT DROP  
$IP6TABLES -P FORWARD DROP  
$IP6TABLES -P OUTPUT DROP

But if i look the traffic details from firefox (also other apps) it shows me only uploaded traffics. The traffic of downloads is Zero Bytes. How is this possible? There must be a incoming traffic for firefox, because how comes the content of a page? 

Or it is a issue?

**Comment by CHEF-KOCH** [comment]
I not understand your issue report (missing details and language/grammar). This is an incomplete report, please look at the wiki howto report a problem.

And you wrote that you looked at the traffic details from Firefox (and others), so we talking about there inbuild traffic stats or the traffic stats from AFWall? Because `about:networking` in Firefox is still beta and may show wrong results but if we talking about AFWall's feature I not understand what you mean by _zero bytes_ ? 
Firefox is not a server and does not listen to incoming connection requests on any port. Normally all incoming data that reaches your browser belongs to a connection that was once initiated by your browser. These connections have also a specific lifetime and once they die Firefox rejects any data coming from the remote site.

**Comment by muoner** [comment]
Sorry for my bad and incomplete report.

Yes, i mean the traffic stats from AFWall. 

If i don't purge the chains and tables with the posted custom script (above), then the traffic stats from AFWall shows the downloaded and uploaded amount of data. 
But if i add the custom script the traffic stats from AFWall shows only the uploaded amount of data. The downloaded is 0 byte in size. 
Is this normal?

**Comment by CHEF-KOCH** [comment]
Yes it's normal, as I wrote we not talking about a server based application and if it would be a sever based application such as a torrent application it wouldn't make any sense to block them since it would slow down your download/upload speed. That's a reason why some distros don't have a firewall enabled (because any connection originated from the web that tries to reach your machine will be rejected anyway - and of course the ports should be closed by default). A normal application does not need that, and we have to differ because connections and traffic is not the same! Connections are initiated from the web. If you launch an application like Firefox the initiation of the connection to the web is happening on the client side (local machine). Since the connection was established by your local machine, responses from the external sites are allowed. However, an external site can't connect to your computer out of the blue without you initiating it. 

I hope that helped you, if you try to monitor it I recommend to use Fiddler, Whireshark or on Android the [Network Log](https://play.google.com/store/apps/details?id=com.googlecode.networklog) app. For portscanning the nmap based one called [PIPS](https://market.android.com/details?id=com.wjholden.nmap) or his free alternate [Fing](https://market.android.com/details?id=com.overlook.android.fing)

A Wireshark solution under android seems [Shark-app](https://market.android.com/details?id=lv.n3o.sharknative) [needs tcpdump] also available as [free version](https://market.android.com/details?id=lv.n3o.shark). [You need another app to read the PCAP directly on Android- Shark Reader]. For tcpdump I wrote here an short article howto use it [here](http://www.kandroid.org/online-pdk/guide/tcpdump.html).

And the last app [Network Spoofer](https://market.android.com/details?id=uk.digitalsquid.netspoofer) needs unpacked over 400 MB! and is not for beginners but efficient to show what's really goes on, personally I not recommend to use such apps under Android Gingerbread since WLAN not goes under Monitor- or Promiscuous-Mode, only 4.x (ICS or higher) allow such behavior without manipulating system data or firmware (ICS or higher supports USB Host Mode).

**Comment by muoner** [comment]
Thank you for the explanation!

Now I feel safe again.
