### ISSUE TITLE
Wi-Fi-Hotspot not working while AFWall+ is enabled

### ISSUE THREAD

**Issue by bopi-** [ukanth/afwall#344]
AFWall+ Logs:
AppID : -11
Application's Name: 
Total Packets Blocked:  4
[UDP]10.74.210.211:53(2)
[UDP]10.74.210.210:53(2)

NFLOG:
{AFL} IN= OUT=ccmni0 SRC=10.202.247.168 DST=10.74.210.210 LEN=69 PROTO=UDP SPT=53300 DPT=53 LEN=49 UID=1014
{AFL} IN= OUT=ccmni0 SRC=10.202.247.168 DST=10.74.210.211 LEN=69 PROTO=UDP SPT=53300 DPT=53 LEN=49 UID=1014

Adding a custom script solves the problem:
$IPTABLES -A afwall-3g-tether -p tcp -m owner --uid-owner 1014 -m tcp --dport 53 -j RETURN
$IPTABLES -A afwall-3g-tether -p udp -m owner --uid-owner 1014 -m udp --dport 53 -j RETURN

What do you thing about adding these rules to afwall-3g-tether chain when enabling "-12:(Tethering) - DHCP+DNS service"?

AFWall+: 1.3.4.1
Android: 4.2.2
Device:  Acer Z160

**Comment by CHEF-KOCH** [comment]
It's depending with which configuration this works or not, on Android 4.3+ DNS is general disabled but if we gonna disable netd and enable tethering it works (no need to add custom rules and btw the only difference is the owner ID you gave us compared to existent source). 

Try this with the latest alpha and report back if that worked for you, sure you are on 4.2.2 but it's not mentioned if it's stock/nightly/aokp or which base use this rom so it could be working or not. To general automatically open it _could be a security risk_. 

A little story about that to better understand:
DNS is known as insecure (on windows and Linux I entirely disabled this and all still works). There is also an option under Windows to enable the caching for only a specific time via registry (which in fact would be more _secure_). Disabling such service doesn't have any negative effects, since it won't break any web page from loading because your provider will manage this on our client site it's only act like a cache. But remember that turning such stuff off does not empty the cache (under windows _ipconfig /flushdns_ and under Linux/Android it's a bit more 'complicated' (more stuff to type). 

``
ndc resolver flushif <iface>  (e.g. wifi, rmnet01)
ndc resolver flushdefaultif
ndc resolver setifdns <iface> <dns1> <dns2>
ndc resolver setdefaultif <iface>
```

The important line:
But AFWall+ does not control such stuff since this will interference with your system settings (and also needs a restart after each apply).

Imho the best thing is to leave it just how it comes (enabled/manual) because disabling it will stop your computer/device from registering it's domain name with your local DNS server if you're on an Active Directory domain, reducing the cache duration in the registry as mentioned is the best thing (4 hours should be okay). I not found any similar solution in Android yet (or only with huge expense). And also remember that we have different systems (Android 4/5) and such which may (depending on the rom/implementation) handle stuff different.

**Comment by Mannshoch** [comment]
Its strange. On my Samsung Galaxy S2 (CM11, Android 4.4.4); AFWall+ Alpha2 from F-Droid
3G -> Wifi works with activated AFWall+
Wifi -> USB only if I deactivate AFWall+

**Comment by Mannshoch** [comment]
I detected that Wifi -> USB work also if I tick "-10:(Jede App)" to be allowed for Wifi

**Comment by CHEF-KOCH** [comment]
As I said it's no bug at all.

**Comment by Mannshoch** [comment]
I know but there is a silent hope for an enhancement :-)

**Comment by CHEF-KOCH** [comment]
For what? Nothing to improve here, it's the nature of Linux.

**Comment by varhub** [comment]
@ukanth I reflog this issue due similar problems in android 6.
If 1014 is a reserved uid, why not just add these an others to list and let user enable it?
Just like 1013 (media) -12 (tethering) -11 (kernel) 1011 (gps) and so on.

**Comment by codyit** [comment]
So for my case the blocked UID is -1
Either for hotspot and another application in work profile calling microg gsm
What does -1 mean?

**Comment by ghost** [comment]
Count me in on this issue.

Android 9 OnePlus 6.

Open Beta 23.

Client connected to the Hotspot, no internet till I disabled afwall

And I also see the weird -1 as @codyit mentioned.
For me, it reports as Linux kernel

**Comment by nihal697** [comment]
Same issue here.
Running xiaomi redmi note 7,  AICP android Q
