### ISSUE TITLE
Feature: Prompt - Allow internet access for X minutes

### ISSUE THREAD

**Issue by rancidfrog** [ukanth/afwall#349]
It would be nice to have a feature to allow certain apps access to internet for X amounts of minutes upon access attempt.
It would almost be like how SuperSU handles root request, I.E. Allow/Deny/Prompt
An extra would be to have a white list of apps that should display prompt request.
Also, to have the number of minutes variable.

Thank you

**Comment by CHEF-KOCH** [comment]
A normal firewall doesn't have such feature, not on desktop windows pc's or on linux machines. It makes no sense to allow such thing, because we would need to verify every x seconds if it's still open or not (in fact this would course a lot of battery and wakelocks).

See also FAQ [#24](https://github.com/ukanth/afwall/wiki/FAQ#24-how-can-i-disable-the-firewall-temporarily) & [#43](https://github.com/ukanth/afwall/wiki/FAQ#43-will-there-a-connection-confirm-dialog-on-demand-feature-implemented-soon)

If you like million of popups, take a look at [Lightning Wall](http://forum.xda-developers.com/xposed/modules/app-lightningwall-t2746254#).

**Comment by rancidfrog** [comment]
Thank you for your reply.

I guess it depends on what you think is normal.
I used to use comodo firewall in desktop back in the day. And it did ask per request if set.
So, I guess normal is really not the right word to use.

I do not agree with you in regards to battery drain and wakelocks.
As nobody has been complaining regarding SuperSU. And, it can allow every app to be set to Prompt.

But, I did mention that a prompt could also be set on only a certain white-listed apps, (As I saw the issue with checking time and time again for traffic and timing issues).
Personally I would like to see a prompt on only a selected few apps, i.e. Root (to connect to vpn) and Settings (for certain updates) but only temporarily. And, it is a hassle to manually enable and disable them. So, I was thinking that maybe it was possible as I have the Root prompt each time for certain apps and it created no issues.

Regarding FAQ #24 and #43,
I do not want to disable everything, only enable one thing for 5-10 minutes.
And,
" There is no on-demand firewall based on iptables available "
Which is why I hoped maybe a developer here would be interested.
I did a search and #269 did not show up, but thank you for linking to it, indirectly.
So, I guess I am not the only one.

And I do not use Xposed.

**Comment by CHEF-KOCH** [comment]
Comodo and any external tools providing advance features which does not use iptables, the windows own firewall is similar compared to iptables (but easier). So _normal_ the windows own firewall is more than enough for everyone, but most people don't know how to deal with it....

Comodo, Kaspersky and others also including a ids/hips (which is a special thing to detect new things, but this have nothing much todo with an ordinary firewall, it's more for preventing unknown executable's). But you do not need such things, really, that does not stop/block malware or is a benefit - because if a user not answer or regulate all of these popups there could be a hole in the wall and no power user I know need to open/close some ports all the day or for xyz seconds.
And remember back in the good old linux days the software/iptables (gui) firewall wasn't activated by default because you not need it as a normal user - better use a nat and that's it.... 

As song you are on the whitelist mode there will be no traffic and I not understand why someone need to open it for some seconds? You may not understand that as long you not open the app, that there will be no traffic (except some core/kernel traffic).

About SuperSU:
Sure it will drain battery if it would handle as much requests as the firewall would handle but su only handle the requests coming from the apps that needs root - and that's it. You can't compare single requests with constantly requests for incoming/outgoing traffic....


About Xposed:
There is also LBEGuard, but imho it's not based on iptables.
