### ISSUE TITLE
[Feature Request] seperate profiles wifi networks

### ISSUE THREAD

**Issue by ka223** [ukanth/afwall#350]
Hi,

it would be usefull to set up seperate profiles for different wifi networks.

So I can differ between default, homeWIFI, work, hotspots, ... and so on.

Thanks

**Comment by ukanth** [comment]
You could do that with the current one until I'm missing something.

**Comment by CHEF-KOCH** [comment]
I guess he means that we can change profiles for each new/connected SSID. That would make it possible to apply our rules for multiple SSID so that we have something like a [whitelist](http://repo.xposed.info/module/com.smartmadsoft.xposed.nolockhome) for e.g. guest bridge access to Internet.

**Comment by ka223** [comment]
@CHEF-KOCH
Yes, for example by switching to a wifi network with ssid xy, profile xy is automatically activated by afwall.

**Comment by DavydLiu** [comment]
I think this feature will be very useful. Do we have any updates regarding it? Or maybe the ability to  schedule profiles. e.g. 8:00am - 5:00pm use profile A, the rest of time use profile B.

**Comment by CHEF-KOCH** [comment]
Android isn't a backbone, means there is only one wifi connection at the same time. You need to select the wifi you want connect to manually from the avaible network overview list, this is based on a whitelist, the user connects only to the allowed network that was granted. This needs no extra profiles because the existent rules will be used. To change on each other network app internet privileges is also unessary since the apps that are not running in the background doesn't consume any bandwith, to restrict system relevant things could be problematic. 
Besides that since Android 4.x you could just create different user profiles and android does support this, called multi-user together with Tasker it's already powerfull enough.

**Comment by ukanth** [comment]
This can be done via tasker/ AFWall Rules. I'm not going to duplicate if that can be done with other similar tools.

**Comment by ka223** [comment]
@ukanth 
I need this to prevent apps to use centain wifi networks.

For example, one wifi network is provided over utms an stick with limited mobile data. 
Apps are loading updates and other stuff, in most cases I could deactivate this manually, but this is painful by switching besides wifi networks. 
And if I try to switch afwall profiles manually, if I miss this once, all my mobile data is gone.
