### ISSUE TITLE
detect blocked connection gapps

### ISSUE THREAD

**Issue by Andre3g** [ukanth/afwall#352]
Hallo,

Every time i unlock screen i found a connection to 74.125.136.188.5228 on my WLAN-Router.
This user seem to be u0_a19 (gapps).

Now i remove uid 10019 from wl-mode and apply.
But connection  will be NOT blocked.

Whats going wrong?

details below.
afwall 1.3.4.1 on Sam-Tab3/4.2.2

regards Andre

test unlock screen

- router:tcpdump
17:46:03.898727 IP 10.1.1.16.33270 > 74.125.136.188.5228: Flags [P.], seq 2084:2111, ack 4801, win 409, options [nop,nop,TS val 421855 ecr 2721658101], length 27
17:46:04.045181 IP 74.125.136.188.5228 > 10.1.1.16.33270: Flags [.], ack 2111, win 442, options [nop,nop,TS val 2722409438 ecr 421855], length 0
17:46:04.045254 IP 74.125.136.188.5228 > 10.1.1.16.33270: Flags [P.], seq 4801:4830, ack 2111, win 442, options [nop,nop,TS val 2722409446 ecr 421855], length 29
17:46:04.169410 IP 10.1.1.16.33270 > 74.125.136.188.5228: Flags [.], ack 4830, win 409, options [nop,nop,TS val 421884 ecr 2722409446], length 0

- sh conn, get pid
root@android:/ # busybox  netstat -anep   | busybox more
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 ::ffff:10.1.1.16:45970  ::ffff:74.125.136.95:443 ESTABLISHED 9039/com.google.and
tcp        0      0 ::ffff:10.1.1.16:33270  ::ffff:74.125.136.188:5228 ESTABLISHED 2646/com.google.pro
tcp        1      0 ::ffff:10.1.1.16:35730  ::ffff:173.194.113.164:443 CLOSE_WAIT  2646/com.google.pro
raw        0      0 ::%1:58                 ::%1166480:*            58          3361/dhcpcd

- get user
root@android:/ # ps | busybox grep 2646
u0_a19    2646  1911  587372 16932 ffffffff 4007e15b S com.google.process.gapps

- get uid
root@android:/ # ls -l acct/uid | busybox grep u0_a19
drwx------ root     u0_a19            2015-03-06 18:32 10019

**Comment by CHEF-KOCH** [comment]
This isn't a _issue_, it's more like a question/identification about google's gapps process and why the hell it needs a connection all the time. 

So, we need some more info because the IP itself does not help much. 

A [quick search](https://www.robtex.com/en/advisory/ip/74/125/136/188/) about that IP reveals that it really comes from Google, Inc. - alias _ea-in-f188.1e100.net_ (reverse rec.) So it could be googles safe browsing feature or [gtalks heartbeat](https://jira.cyanogenmod.org/secure/attachmentzip/unzip/637050/26935%5B0%5D/event.log) ping from com.android.incallui (10019 /mtalk.google.com:5228/ & mobile-gtalk.l.google.com) [which also comes from the framework itself].

```
Data over HTTPS to Google on these ip addresses
- 173.194.116.0/16
- 173.194.65.94
- 173.194.65.120
- 176.34.155.23
- 173.194.65.95 - TSLV1 protocol - Application Data
- 74.125.136.101
- 74.125.136.103
- 74.125.136.188 - Framework / incallui
- 54.229.105.203
- 54.231.10.72

TCP Hpvroom data with Google:
- 175.158.4.76
- 175.158.4.78 
- 216.58.212.0/16
```

There are several _solutions_:
* Block the connection via custom script <code>$IPT -A "afwall" -d 74.125.136.188:/22 -j REJECT</code>
* Via router (would be the best if you don't like such connection but only works at @home wifi)
* Do not use any Google apps, like YouTube or Google accounts on the phone.
* Since [it is encrypted](http://www.pcmech.com/article/the-mysterious-1e100-net/) you never know what's behind all this, don't waste your time try to identify which processes/apps are responsible for such behavior, but rather use iptables to prevent this communication via init.d something like <code> -I OUTPUT --dest 74.125.136.188 -j DROP</code>.
* Official statement about this, available over [here](https://support.google.com/faqs/answer/174717?hl=en) [which only explains why such strange name but not which app use it... useless].

**Comment by CHEF-KOCH** [comment]
Under the gapps process (com.google.process.gapps) there are several root processes running, such as:
* com.google.android.syncadapters.contacts
* com.google.android.gms
* com.google.android.gsf
* com.google.android.gsf.login
* ... others (depending which gapps package was installed (gapps/agapps/pagapps)

So you need to indicate first from which package this comes. If <code>root</code> wasn't checked in AFWall+ this will be blocked anyway. So as written in other threads, we are not add something for each new google gimmick and to block all isn't good (especially if you installed gapps - you must trust google or just remove it if you don't).
