### ISSUE TITLE
make sure permanent status bar icon appears starting from boot

### ISSUE THREAD

**Issue by jidanni** [ukanth/afwall#362]
Not sure if related to #328 but once one launches afwall (beta or not, Android 4.0.4 IceCreamSandwich) there is no way to exit it to the degree that it will finally leave the status bar.

Disabling all the rules and choosing exit just won't get it out of the status bar. No choice in Preferences seems to help.

Therefore beside "Exit" in the menu, perhaps add a "Really Exit".

**Comment by CHEF-KOCH** [comment]
It's a duplicate.

I already gave an very detailed answer on this, other security app also don't have any "Exit" button because it makes no sense to disable it (if you don't like it why you installed it and not used Terminal Emulator or ADB to take control over your iptables?).

We can already freeze the app itself via:
````
adb shell
pm disable <package name> (in our case _dev.ukanth.ufirewall_)
````

We can re-enable apps with </code>pm enable <package name></code>. In fact, this seems to be the only way to re-enable them without external apps like TitaniumBackup, OBackup and such. If someone don't know the exact package name he can simply use <code>pm list packages -e | grep 'afwall'</code.

There are also apps like Greenify that are designed to not freeze/disable the app and only wakes theme if it's really necessary or controlled by the user. But I not recommend such apps, since it also coasts ram and cpu usage for something what can be used via brain (just don't install 100+ apps).
To think that killing the apps and re-run them will safe any battery [is a myth](http://androidforums.com/threads/putting-to-rest-the-myths-about-task-killers-ram-optimizers-and-the-like.896663/), Android's memory management is already efficient.

**Comment by CHEF-KOCH** [comment]
It's a duplicate.

I already gave an very detailed answer on this, other security app also don't have any "Exit" button because it makes no sense to disable it (if you don't like it why you installed it and not used Terminal Emulator or ADB to take control over your iptables?).

We can already freeze the app itself via:
````
adb shell
pm disable <package name> (in our case _dev.ukanth.ufirewall_)
````

We can re-enable apps with </code>pm enable <package name></code>. In fact, this seems to be the only way to re-enable them without external apps like TitaniumBackup, OBackup and such. If someone don't know the exact package name he can simply use <code>pm list packages -e | grep 'afwall'</code.

There are also apps like Greenify that are designed to not freeze/disable the app and only wakes theme if it's really necessary or controlled by the user. But I not recommend such apps, since it also coasts ram and cpu usage for something what can be used via brain (just don't install 100+ apps).
To think that killing the apps and re-run them will safe any battery [is a myth](http://androidforums.com/threads/putting-to-rest-the-myths-about-task-killers-ram-optimizers-and-the-like.896663/), Android's memory management is already efficient.

**Comment by CHEF-KOCH** [comment]
It's a duplicate.

I already gave an very detailed answer on this, other security app also don't have any "Exit" button because it makes no sense to disable it (if you don't like it why you installed it and not used Terminal Emulator or ADB to take control over your iptables?).

We can already freeze the app itself via:
````
adb shell
pm disable <package name> (in our case _dev.ukanth.ufirewall_)
````

We can re-enable apps with </code>pm enable <package name></code>. In fact, this seems to be the only way to re-enable them without external apps like TitaniumBackup, OBackup and such. If someone don't know the exact package name he can simply use <code>pm list packages -e | grep 'afwall'</code.

There are also apps like Greenify that are designed to not freeze/disable the app and only wakes theme if it's really necessary or controlled by the user. But I not recommend such apps, since it also coasts ram and cpu usage for something what can be used via brain (just don't install 100+ apps).
To think that killing the apps and re-run them will safe any battery [is a myth](http://androidforums.com/threads/putting-to-rest-the-myths-about-task-killers-ram-optimizers-and-the-like.896663/), Android's memory management is already efficient.

**Comment by CHEF-KOCH** [comment]
It's a duplicate.

I already gave an very detailed answer on this, other security app also don't have any "Exit" button because it makes no sense to disable it (if you don't like it why you installed it and not used Terminal Emulator or ADB to take control over your iptables?).

We can already freeze the app itself via:
````
adb shell
pm disable <package name> (in our case _dev.ukanth.ufirewall_)
````

We can re-enable apps with </code>pm enable <package name></code>. In fact, this seems to be the only way to re-enable them without external apps like TitaniumBackup, OBackup and such. If someone don't know the exact package name he can simply use <code>pm list packages -e | grep 'afwall'</code.

There are also apps like Greenify that are designed to not freeze/disable the app and only wakes theme if it's really necessary or controlled by the user. But I not recommend such apps, since it also coasts ram and cpu usage for something what can be used via brain (just don't install 100+ apps).
To think that killing the apps and re-run them will safe any battery [is a myth](http://androidforums.com/threads/putting-to-rest-the-myths-about-task-killers-ram-optimizers-and-the-like.896663/), Android's memory management is already efficient.

**Comment by CHEF-KOCH** [comment]
It's a duplicate.

I already gave an very detailed answer on this, other security app also don't have any "Exit" button because it makes no sense to disable it (if you don't like it why you installed it and not used Terminal Emulator or ADB to take control over your iptables?).

We can already freeze the app itself via:
````
adb shell
pm disable <package name> (in our case _dev.ukanth.ufirewall_)
````

We can re-enable apps with </code>pm enable <package name></code>. In fact, this seems to be the only way to re-enable them without external apps like TitaniumBackup, OBackup and such. If someone don't know the exact package name he can simply use <code>pm list packages -e | grep 'afwall'</code.

There are also apps like Greenify that are designed to not freeze/disable the app and only wakes theme if it's really necessary or controlled by the user. But I not recommend such apps, since it also coasts ram and cpu usage for something what can be used via brain (just don't install 100+ apps).
To think that killing the apps and re-run them will safe any battery [is a myth](http://androidforums.com/threads/putting-to-rest-the-myths-about-task-killers-ram-optimizers-and-the-like.896663/), Android's memory management is already efficient.

**Comment by jidanni** [comment]
Ideas: Perhaps remove the exit key as it is just the same as the BACK
key pretty much, I have now discovered.

I think the main thing that confuses users (me) is that when one powers
up their phone, there is no status icon (even though chosen in
Preferences.) One has to start the app in the launcher to get the icon
to appear there in the status (notification) bar there at the top of the
screen.

And its presence (from then on) is totally determined by the checkmark
in Preferences, and not by anything else.

So from boot all the way till e.g., an hour later when the user touches
the app with his finger to launch it, the app is indeed doing its job
just the same, except that its icon there in the status bar isn't
showing.

One would think "if the program is so smart that it can defend us
against all that traffic during that hour, perhaps it could also
remember to put its icon there in the status bar and not wait until my
finger press to do that".

Perhaps put a note there in Preferences mentioning if that is impossible.

**Comment by CHEF-KOCH** [comment]
The status bar icon has nothing much todo with the exit button. So, stay on the line. I guess we will remove it entirely or just _pkill_ the app so that it won't run anymore (imho it's not an good idea since Android should control it and not the user - because if someone accidentally pressed it nothing is anymore running in the background, so we minimum need a feedback after this was pressed).

**Comment by jidanni** [comment]
OK I retitled this bug to "make sure status bar icon appears at boot..." .

Even if you kill the app it will still keep doing its job of blocking connections, so that would confuse users even more, plus it is real bad practice probably. Anyway if the exit button can't act like other programs' exit buttons then it is probably best to remove it.

Apparently as long as the app is installed there is only two states: tables enabled and tables disabled, and not third state: on the disk but totally not run at all. (I didn't look at the source code so am guessing.)

**Comment by CHEF-KOCH** [comment]
AFWall+ is just an GUI for iptables (which never can be shutdown since it isn't an app - it's a binary). I already wrote about this, now twice and it's well written down in the FAQ which people constantly ignore without any reasons. 

Yes that exit button is just an relict, since Android 4.x the OOM is already well handled so normally no apps doesn't need to be shutdown even if you have low memory (let Android handle it).
As ukanth and I already wrote in the other threads and on XDA, it's not possible to monitor the connectivity changes from e.g. 3G<->4G if the GUI is completely shutdown (wiped from the memory) since this will break some features, like the "active rules" option and of course if you change the DNS via custom script this also will not get an re-apply after each connectivity change.


Here are some facts about how Android handle memory OOM -> Low Memory Management/out-of-memory
https://developer.android.com/training/articles/memory.html
https://source.android.com/devices/tech/low-ram.html
http://www.3c71.com/android/?q=node/594
http://android.stackexchange.com/questions/23469/how-to-lower-oom-value-of-an-app-permanently

Some kernels and tools like 3C can "tweak" such settings, which is more a relict as from Android 2/3. In fact since we are currently on 4/5 nobody needs such tools anymore, same as the TRIM feature, such stuff are relict's from older systems. But I admit that in some rare situations and configurations, sometimes, for some power-user it can be a benefit from adjust such settings, but in fact killing and restarting apps always drains the battery faster. It's not the memory what kills your battery, it's the cpu cycles which will need more battery, more cycles means more power and ends up will less battery.

Read here:
https://source.android.com/devices/tech/power.html
http://stackoverflow.com/questions/20212195/determine-how-much-each-cpu-cycle-consumes-battery-life
http://android.stackexchange.com/questions/17382/how-can-i-find-out-what-causes-android-os-to-consume-battery

Of course all of these mentioned things does not considered some bugs which maybe comes with the rom, like the sdcard scanning bug which constantly running in the background end never gets killed/stopped.


I hope this was now the last time we need to talk about it, I gave now much detailed information how the background app stuff is handled by the Android OS. The rest should be clear enouth, as said I think we just remove that button to not confuse the people or add just an warning if you really want to exit the app this will may break some functions. These are the only two options.

**Comment by CHEF-KOCH** [comment]
> make sure permanent status bar icon appears starting from boot 

I don't think this will be fixed, I don't like such behavior in Xprivacy and I never got the reasons why the user needs for every new "security" app million of popups/notifications. For me it makes sense to show only something if it fails - and AFWall+ does this with e.g. a yellow Icon + toast. 
Every new user attempt to something (which is already clear) is pretty annoying and don't have any reasons. 

It's like to use a software Firewall on your PC which shows for each new ip a popup, nobody needs this.

**Comment by jidanni** [comment]
I in fact am glad the icon doesn't show until one launches the app. But it still seems odd to me that there is no way to make the icon appear starting at boot at least via Preferences.

**Comment by CHEF-KOCH** [comment]
Because nobody wanted that there is a persistent icon. 
You're the first one, but I still don't get it why we need an persistent icon all the time? It makes only sense to show persistent icon(s) if that shows an real-time indicator if something happens (firewall/disabled/enabled/rules applied failed/... -> and we already did have extra icons to show most important things). I would bet all my money that people will directly complaining why an GUI needs so many ram + attention.

One of the core benefit is that beginners can use the firewall without much attention. Remember that Linux isn't Windows, you don't need that much attention to the products if all is already working just out-of-the-box. I don't get any seriously reasons why we should touch this behavior.

So if there is no security reasons (and there is none) this will not be implemented. Sorry.

**Comment by jidanni** [comment]
I don't want it either.
I just thought it odd that in preferences one can only make it permanent from launch to poweroff, but not from boot to poweroff. OK, closing.
