### ISSUE TITLE
log window: just one or two messages normal?

### ISSUE THREAD

**Issue by jidanni** [ukanth/afwall#363]
What is the log screen supposed to look like?

Is only one or two items visible normal?

And nothing changes until one hits "refresh".

Then there are just another one or two items there total.

All despite the many messages being flashed in the middle of the screen.

Beta AFwall+ on IceCreamSandwich Android 4.0.4.

**Comment by CHEF-KOCH** [comment]
Please learn how to post a correct [bugreport](https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug). And search via _is:issue is:open log_ or something like this he next time. 

I already gave an answer and you opened just another one report + [ignoring my words](https://github.com/ukanth/afwall/issues/361#issuecomment-89594009), in relationship with it look at #345 , #319, #295, #194, #84, #9.

The log has a limit as requested by issues number 9, so it won't cache all stuff forever and of course it won't show anything it internet is disabled or depending in which mode you are if something is blocked (checked) or not. If there is no internet traffic requested by the app you are looking for, this means that it's simply not blocked or nothing to block. The refresh button is only for something if really something happened in the background, e.g. if you disabled auto sync + there is no app which needs internet in the background you can tap on that refresh button million times and it won't change anything because there is nothing that requires an active internet connection.

**Comment by jidanni** [comment]
Duplicate of #194

**Comment by jidanni** [comment]
Also not sure of how each of the Log Preferences work or if they are related to each other. So perhaps add more words there.
