### ISSUE TITLE
VPN problems with AFWall+ 1.3.4.1

### ISSUE THREAD

**Issue by shellshocker** [ukanth/afwall#364]
Hi there,

I have some problems to get a working VPN-Connection on Android 4.4.4 (OmniROM).

I'm using following custom script:
```
# Flush/Purge all rules expect OUTPUT
$IPTABLES -F INPUT
$IPTABLES -F FORWARD
$IPTABLES -t nat -F
$IPTABLES -t mangle -F
$IP6TABLES -F INPUT
$IP6TABLES -F FORWARD
$IP6TABLES -t nat -F
$IP6TABLES -t mangle -F

# Flush/Purge all chains  
$IPTABLES -X   
$IPTABLES -t nat -X  
$IPTABLES -t mangle -X  
$IP6TABLES -X   
$IP6TABLES -t nat -X  
$IP6TABLES -t mangle -X

####################
# Defaults         #
####################

# IPv4 connections
$IPTABLES -P INPUT   DROP 
$IPTABLES -P FORWARD DROP 
$IPTABLES -P OUTPUT  DROP 

# IPv6 connections  
$IP6TABLES -P INPUT DROP  
$IP6TABLES -P FORWARD DROP  
$IP6TABLES -P OUTPUT DROP

#####################
# Special Rules     #
#####################

# Allow loopback interface lo 
$IPTABLES -A INPUT -i lo -j ACCEPT 
$IPTABLES -A "afwall" -o lo -j ACCEPT

# Fix DNS-Server
$IPTABLES -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination x.x.x.x:53
$IPTABLES -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination x.x.x.x:53

#####################
# Incoming Traffic  #
#####################

# Allow ICMP packets
$IPTABLES -A INPUT -p icmp -m icmp --icmp-type echo-reply -j ACCEPT 
$IPTABLES -A INPUT -p icmp -m icmp --icmp-type echo-request -j ACCEPT 
$IPTABLES -A INPUT -p icmp -m icmp --icmp-type destination-unreachable -j ACCEPT

# VPN
$IPTABLES -A INPUT -p UDP --dport 500 -j ACCEPT
$IPTABLES -A INPUT -p UDP --dport 4500 -j ACCEPT

# Allow all traffic from an established connection
$IPTABLES -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

####################
# Outgoing Traffic #
####################

# VPN
$IPTABLES -A "afwall" -p UDP --dport 500 -j ACCEPT
$IPTABLES -A "afwall" -p UDP --dport 4500 -j ACCEPT
```

Am I missing something? Firewall log stays empty.
0: (Root) Apps are also allowed in AFWall+ GUI.

Cheers
shellshocker

**Comment by CHEF-KOCH** [comment]
We are not here to talk about common custom script usage, if you have problems with any script you need to make sure that you tested all stuff without any script - just out-of-the-box. And only after such procedure we are able to check it.

On whitelist mode VPN needs the following checked:
_- 14_ , _-12_, _1016_ and _0_. This should work without any script.

**Comment by shellshocker** [comment]
Well out of the boxing it's working with just 0 allowed. So it's not really an AFWall+ issue. Sorry for that. Thus I'm curious why it's working with default settings and not with the additional Custom Scripts. Maybe a problem with forwarding or NAT rules.

**Comment by CHEF-KOCH** [comment]
That's why it's called custom scripts, because it's custom - in other words it's optional. AFWall+ was designed to work as it is without any custom script for all users and only experts should use the scripts if they really know how to handle with possible errors. That's why you need to look always in the logs/logcat to show what's really goes on behind the doors (because AFWall+ itself have only a limited view for this, because we won't want to confuse non-tec people - so this is a compromise).

Again without having any log, the whole custom script stuff is not really useful, because nobody knows if all is working as expected.

Anyway thanks, for letting me know that nothing is perfect, so I will ad some more stuff to the custom rules section to ensure the next time if someone face a problem how to handle it. 

The rest can be discussed over XDA/G+ or other boards.

**Comment by shellshocker** [comment]
Right now I don't have the time but I will work with the logs to identify the missing rules. I was simply using the iptables rules from my desktop PC - but they don't seem to work. I'm curious why it's working with default settings - there has to be a kind of »workaround« rule for VPN connections.
