### ISSUE TITLE
Tri-state check boxes

### ISSUE THREAD

**Issue by Perlence** [ukanth/afwall#367]
Check boxes on application list items should have the third state: follow the general rule, which is set by default.

General rules here are: Any application, Kernel and Root.

Use case: user allows access to Wi-Fi and denies access to mobile networks for all applications by checking/unchecking corresponding check boxes on "(Any application)" list item. Now user can explicitly deny access to Wi-Fi for any selected app, e.g. app with ads. All newly installed apps will follow the general rule, while this one app will be denied from Wi-Fi and mobile network.

**Comment by CHEF-KOCH** [comment]
So what I understand is that you asking for separate profiles to white-/blacklist apps based on there status? Something like a template (default/wifi/mobile/roaming) which will be respected for new installed apps.

**Comment by Perlence** [comment]
> Something like a template (default/wifi/mobile/roaming) which will be respected for new installed apps.

I should have described the problem I experience first, but you get it right.

The problem is if I select white list mode and "Check all" to allow all apps to use Wi-Fi, I'd be able to manually uncheck those few selected apps, that's good. All apps are denied from mobile network which is what I need. But each time I install a new app I have to give it a permission to use Wi-Fi, which I want to be granted by default.

The same problem, but from the other side, persists if I select black list mode: each time I install an app, I have to check it in the "mobile network" column.

**Comment by Perlence** [comment]
There could be a new list item, "Default permission". I would check it for Wi-Fi and leave it unchecked for mobile network, assuming white list mode.

**Comment by CHEF-KOCH** [comment]
The whole problem about this, and already similar requested features is that we need to ensure that it not interference with other apps/services. For example if we implement such Wifi templates this would be problematic for other apps that need all connections, for example all system services + apps which may using them such as DNSCrypt. Imho the best would be to apply a template to whitelisted (trusted) apps only but this is very complicate.

And I'm generally unsure if people really need to change xyz app depending on the connection each day/week, because if you doing this, it property means that you not trust the app and I see no reasons to support such behavior (just uninstall the app or install an trusted alternative). 
-> Compared to ofter software based firewalls I know nobody which need to change there states every day/week, in most cases the rules will be created once and never touched anymore (except for import/export).

Don't understand me wrong, but it's normally only for experts.

**Comment by Perlence** [comment]
Closing this since tri-state check boxes won't fix the problem.
