### ISSUE TITLE
Incompatible with DNScrypt, connection problems

### ISSUE THREAD

**Issue by ossiborni** [ukanth/afwall#368]
Tested with: 
Android 5.0.2 and 5.1: Cyanogenmod 12.0 and 12.1 on Galaxy S3 (i9300) and LG G2 (D802), OnePlus (5.0.2)
AFwall: Version 2.0.0-ALPHA-1 and stable 1.3.4.1

Using this DNScrypt script: http://forum.xda-developers.com/attachment.php?attachmentid=3233170&d=1427549179

I can reproduce this issue with many phones, with AFwall disabled DNScrypt is working all the time (no connection loss)

Hello,

I'm using DNScrypt and AFwall together on Cyanogenmod, but have following connection problems (only when AFwall is enabled):

- No connection after restart when AFwall is enabled at boot, there are just exclamation marks over the WIFI and the mobile data icon
- No connection if network is changing (from mobile data do wifi and vice versa)
- DNScrypt is not working when "enable inbound connections" is unchecked (no connection at all)

The solution for both problems: Disable AFwall manually and enable it again. This works until the next reboot or the next changing connection.

This is neither a problem with AFwall and disabled DNScrypt, nor with only DNScrypt being enabled and AFwall disabled.

I'd be really happy to see a fix for this as fast as possible. :+1:

**Comment by CHEF-KOCH** [comment]
meh, ... **Invalid Ticket** - This will never be fixed ...
Why I have known this, I added the article about DNSCrypt and people just popping up with a new issue... 

As described in the Wiki and already said here in the issue page, we not adding for each new gimmick/software new workarounds since this is optional - and if people don't know how to handle it, they better not using it. 

Here is what I use which works, there are two possible solutions:
* Make sure AFWall+ does not use the startup data leak fix (because this will "block" all traffic)
* Make sure that your integrated iptables recognize the following commands at boot (if not DNSCrypt never works <code> iptables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1</code>) - it's stored in the _/system/etc/init.d/99dnscrypt_ script ...
* Make sure the deamon is running <code>ps w |grep dnscrypt</code> and <code>nslookup google.com</code>
Make sure DHCP/DNS + Timesyncronisation + root isn't blocked in AFWall+ (whitelist mode)
* Make sure your _etc/resolv.conf_ is set to <code>nameserver 127.0.0.1</code> (all other nameserver entrys's are optional dns addresses 


The other solution is to just add:
* Remove the iptables line (mentioned one above) in the init.d script or just comment it out

Add this to your startup custom script 
```
$IPTABLES -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:53 || true
$IPTABLES -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:53 || true

$IPTABLES -t nat -I OUTPUT -p tcp --dport 53 -j DNAT --to-destination 127.0.0.1:53
$IPTABLES -t nat -I OUTPUT -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:53
```


For VPN unbound you need something like 
```
$IPTABLES -A INPUT -s <server-address> -p tcp -m tcp --dport 53 -j ACCEPT
$IPTABLES -A INPUT -s <server-address> -p udp -m udp --dport 53 -j ACCEPT
```

And check that the query was answered by the nameserver you selected for dnscrypt to use via <code>ls -la /run/dnscrypt</code>


Maybe I add this to the wiki, but I'm sick to fix stuff for people which are to lazy to read the documents, or the [known problems](https://github.com/jedisct1/dnscrypt-proxy/issues/163).

**Comment by CHEF-KOCH** [comment]
Remember that there is also recently a VPN [vulnerability](http://thehackernews.com/2015/02/webrtc-leaks-vpn-ip-address.html) discovered, which affects all VPN providers (even OpenVPN and DNSCrypt/DNSSec)

_"The vulnerability in WebRTC lies in the method used to establish browser-to-browser connections when one or both machines are behind a NAT. This NAT “traversal” method requires both browsers to execute a bit of JavaScript that connects to a STUN (Session Traversal Utilities for NAT) server on the public Internet, which then facilitates the browser-to-browser connection when NAT is in use. When WebRTC makes the connection to the STUN server, rather than sending only the public IP you are appearing to connect from using the VPN, WebRTC also sends over your actual public IP, as well as your LAN IP." _
[Source](https://ritcyberselfdefense.wordpress.com/2015/02/03/vulnerability-in-chrome-and-firefox-leaks-vpn-users-actual-public-ip-address/)

So I recommend to use (if not already) [NoScript](https://addons.mozilla.org/de/firefox/addon/noscript/) (on Firefox) + on Chome (or Chromium) [ScriptSafe](https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf) and check all against [ipleak.net](http://ipleak.net/). A generall good beginning about meta-data is to read [this](http://www.deepdotweb.com/2015/03/11/book-review-data-and-goliath-by-bruce-schneier/) and [this](http://freehaven.net/anonbib/).

**Comment by CHEF-KOCH** [comment]
According to your post over [here](http://forum.xda-developers.com/showpost.php?p=60007746&postcount=39) it seems to be a user configure problem.

**Comment by CHEF-KOCH** [comment]
DNSCrypt 1.6 works quite fine with all Android versions even IPv6 works very good <code>::FFFF:127.0.0.1</code> (replace 127.x with the DNS IPv6 representation. There was also a dist-build folder added with different shell scripts to compile it for arm/armv7/mipsx86/x86 so it should not be a problem to compile it. The only con that I noticed seems that tethering is in some situations slower.

**Comment by jedisct1** [comment]
@CHEF-KOCH Do you have a good link with step by step instructions on how to install and configure DNSCrypt 1.6 on Android?

**Comment by CHEF-KOCH** [comment]
Uargh, that's a pretty good question, DNSCrypt (OpenDNS/Cisco) official supports iOS and Android but they not providing any packages/binaries (I guess because there are to many cpu types) for Android that is easy installable or having an user friendly interface. 

* The latest official binaries can be found over [here](https://download.dnscrypt.org/dnscrypt-proxy/) + there is also an hidden _old_ dir over [here](https://download.dnscrypt.org/dnscrypt-proxy/old/) that contains a cwm installer for Android (I guess it contains the armv7 binary). You could start with this, or on the XDA thread use the lollipop compatible provided package (see the [last pages](http://forum.xda-developers.com/attachment.php?attachmentid=3233170&d=1427549179)) and mod the <code>/etc/init.d/99dnscrypt</code> script [to e.g. change the resolver and such]. 
* The latest resolver csv list with the servers is available over [here](https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-resolvers.csv)
* To understand the parameters and how to build you should take a look at the [official project](https://github.com/jedisct1/dnscrypt-proxy), README.markdown + README-PLUGINS.markdown is all you need. 
* So the only part you need to do on your own is to compile the lib and the dnsproxy version via make. 

Basic parameters example:
```bash
// replace < ... > with stuff from the .csv
dnscrypt-proxy --daemonize --resolver-address=<resolver>:<port> --provider-name=<provider-name> --provider-key=<insert-key> --max-active-requests=100 --edns-payload-size=4096
// mentioned iptables in case you have problems with AFWall+ or the DNS
// as resolver I recommed cloudns, dnscrypt.eu or OpenNIC severs. most of them are fast, stable and using all security extensions (DNSSEC,..)
```

If there is a huge interest I could ask the author if he like to provide binaries for each version on the official download location, or if I get commit rights to upload my packages I could bump it on GitHub. But better would be to integrate this directly in the ROM (like CM 12.1.x).

**Comment by jedisct1** [comment]
Hi Chef,

I am the author of the protocol and dnscrypt-proxy :)

Since the first release, I've been trying to make sure that it always properly compiles on Android, and I got some feedback from Android that it was actually working. 

However my experience with Android is very limited, even as a simple user. So I was looking for links I could add to the official documentation and web site explaining how to install it.

The Lollipop package from the thread you referenced helps immensely and I can use this as a starting point to build precompiled packages for each architecture. Does this work on any rooted Android or does it specifically require CM?

**Comment by CHEF-KOCH** [comment]
Ah, good to know.

No there is no link, because Android normal installs only apk's and not binaries, and since the "main stuff" is a binary we are talking here about something that is in this current state only for experts (sorry). So one of a goal could or should be to introduce in the future an .apk (that of course could published on F-Droid/Play/GitHub) that allow all non-expert future to use DNSCrypt. The pro argument about that is that the apk could include an small GUI to see the current status (overview) + the ability to download and change the resolver(s)/lists/binary/missing stuff. It could also solve some troubles if there are several workarounds implemented (for different OS) to install it, since the mentioned user-own packages may not work on every OS (because symlink/SDcard/whatever changes). 
Well, on the con site we have the time argument (as always, but that's how development works) to design and develop such app and publish them, but I'm quite sure if there would be an separate donate apk a lot of people are willingly to spent some bucks $ to get an security improvement, of course an free version should also be available (Android is known that there are less people compared to iOS to pay for apps). 

To answer the question, yes the mentioned package could be used on lollipop but remember that there is still the user interference problem, since this comes with an pre-configured resolver and setting in the init.d script which means that in this state my above steps to change that should be mentioned. 

Maybe instead of writing/updating the readme I would spent that time to finx someone which want to write an .apk (because the mentioned reasons). Of course I could help on developing this.

**Comment by CHEF-KOCH** [comment]
Since yesterday the dns project now official _supports_ android by giving the people an ]precompiled .zip package](https://download.dnscrypt.org/dnscrypt-proxy/) and a more detailed overview on the [start page](http://dnscrypt.org/#dnscrypt-android/). Thanks for this. I hope this will solve some problems for some people. 

See commits for a detailed overview how it works:
d005030cbc705292bf7fcb516f11fbf1ed859c8f
8ef7b349da73a9005ad96b6d37a45d373fe9ace7
5784f65dbbce24a39d82a3ae08b955b1e76e2494
11d0e74afdcaccf5510122bed2ad58b4ec9801ef
486aa5f7a188c8139820dc4a763827a83ca95ab7

**Comment by jedisct1** [comment]
Unfortunately, the iptables DNAT rules don't seem to work as expected; outgoing packets for port 53 are not redirected to 127.0.0.1:53 (Android 5.1.1, stock ROM). Any idea why?

**Comment by CHEF-KOCH** [comment]
What does the log/terminal shows?

**Comment by jedisct1** [comment]
`iptables -t nat --list` shows the rules, but they don't do anything. Non-NAT rules such as blocking a specific IP or port work fine.

Changing the resolver settings on Android seem to be a lot of fun: https://github.com/bparmentier/DNSSetter/wiki/ndc-resolver-commands

Is there a way to get the network id from the command-line?

**Comment by CHEF-KOCH** [comment]
Yes, because of all these kind of problems I wrote that the only real solution is to write an app for this, it would be much easier to code this, instead of writing huge scripts that are difficult to debug especially under the real device environment. OverrideDNS (currently in beta stage to test a watchdog service) is the only app that respect all systems, but even with that app in some situations the DNS gets overridden. 


<code>nat</code> needs to be enabled via routing _ip_forward_. That can be done e.g. with <code>echo 1 > /proc/sys/net/ipv4/ip_forward</code> in the init.d script, it's also documented over [official channels](http://www.netfilter.org/documentation/HOWTO/NAT-HOWTO.txt), see also NatController.cpp in AOSP. 

> Is there a way to get the network id from the command-line?

Of course, via <code>ifconfig | grep netId</code> by reading <code>etc/network/interfaces</code> but that won't help in case you're not on a wlan environment, the main intent comes from RIL, so you can set whatever you want, it will be overridden every time again and again. Maybe an solution could be to force dnsmasq t use them as a local DNS.

```bash
# Example etc/dnsmasq.conf (opendns/wlan0/lo/rmnet0 interfaces)
no-resolv
no-poll
no-IPv6
no-negcache
all-servers
addn-hosts=/etc/hosts
log-facility=/dev/null
log-async=5 
cache-size=65536 
local-ttl=86400 
interface=lo
interface=wlan0
except-interface=rmnet0
no-dhcp-interface=lo
no-dhcp-interface=wlan0
no-dhcp-interface=rmnet0
server=208.67.222.222
server=208.67.220.220
server=192.168.1.1
server=8.8.4.4
server=8.8.8.8

# .. set 127.x e.g. via build.prop, adb, shell or whatever, ...
setprop net.dns1 127.0.0.1
setprop net.rmnet0.dns1 127.0.0.1
setprop net.wlan0.dns1 127.0.0.1
setprop dhcp.wlan0.dns1 127.0.0.1
setprop dhcp.eth0.dns1 127.0.0.1

# Example /etc/resolv.conf
nameserver 127.0.0.1
nameserver 8.8.4.4
nameserver 8.8.8.8
nameserver 208.67.222.222
nameserver 208.67.220.220



# On Lollipop+
netcfg wlan0 down
ndc network destroy 100
ndc interface clearaddrs wlan0
ifconfig wlan0 10.99.4.11 netmask 255.255.252.0
route add default gw 10.99.5.1 dev wlan0
#ndc resolver setnetdns wlan0 8.8.8.8 8.8.4.4
ndc resolver setnetdns wlan0 208.67.222.222 208.67.220.220


ndc network create 100
ndc network interface add 100 wlan0
ndc network route add 100 wlan0 <GATEWAY>/24
ndc network route add 100 wlan0 0.0.0.0/0 <DNS1> <DNS2>
ndc resolver setnetdns 100 localdomain <DNS1> <DNS2>
ndc network default set 100


This does the following:
RIL calls the radio system to start a data connection, which are here in this example wlan0<->eth0.
RIL calls netcfg dhcp wlan0 to obtain the DNS, IP address 
RIL calls the ndc resolver setifdns wlan0 to ensure that the established data connection is the default connection
RIL sets the DNS via setifdns wlan0 <dns1> <dns2>
Now check wifi via adb shell dumpsys wifi if DNS was set, of course that needs to be done for adb shell dumpsys connectivity (mobile) adb shell dumpsys bluetooth or whatever you're connected with
```

**Comment by CHEF-KOCH** [comment]
We can close this topic. DNSCrypt will never prober work on Android. I already explained it on the official DNSCrypt issue tracker. Even CM team will never fix that, it's due the api limitation - and VPN or any other tunnel api will also not resolve these kind of problems, since it's also suffering from limitation.
