### ISSUE TITLE
Stuck on applying iptables rules

### ISSUE THREAD

**Issue by Primokorn** [ukanth/afwall#374]
Hi,
I created a small custom script located in /data/local/afscript.sh:
"# Necessary at the beginning of each script!
IP6TABLES=/system/bin/ip6tables
IPTABLES=/system/bin/iptables

#
"# Others
$IPTABLES -A "afwall" --destination "23.4.92.33/32"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "23.32.0.0/11"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "23.64.0.0/14"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "23.253.56.120/32"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "64.207.128.0/18"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "68.232.32.0/20"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "91.103.140.0/24"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "104.16.0.0/12"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "104.64.0.0/10"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "116.214.0.0/16"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "118.214.0.0/16"; -j "afwall-reject" || exit
$IPTABLES -A "afwall" --destination "198.232.125.88/32"; -j "afwall-reject" || exit

(ignore the " it's just to avoid Github formatting)

I'm using AFWall+ version 2.0.0-ALPHA-2 and AICP CAF rom under Android 5.1.1.
My script afscript.sh has 755 permissions is its patch is entered in AFWall+ => . /data/local/afscript.sh
When I want to apply the new rules I'm stuck on the popup saying 'Applying iptables rules'. I don't see what's wrong with this script so I though it could be an AF+ issue.

Thank you.

**Comment by CHEF-KOCH** [comment]
It's mentioned in the custom script section with a big fat warning that we won't accept any external related scripting problems if it's not directly related to AFWall+ itself - and this is such as case. 

To format something you can use e.g. something like this:
```
```bash
```
```

You're whole syntax is wrong, the correct syntax should be <code>$IPTABLES -A "afwall" -d 31.13.24.0/21 -j REJECT</code>, the <code>exit 0</code> statement is only needed once (if!) you use the internal Android toolbox, since we using busybox (or better use the external one) it will automatically parsed. 

This isn't an issue, is just how things are, there is no callback from any script related error since this will automatically be done only if you use any iptables parser script or any debugging related stuff to look at. I don't see any argument to implement 600+ error codes ad feedbacks + explain them all for something that could be easier done with external debugging. 

BTw. since it coasts some performance I generally not recommend to block xyz ip's with afwall, ipset is a lot of faster even with million blocked ip's according to parse them all every xyz connecitity change. - but's already well documented.

**Comment by CHEF-KOCH** [comment]
```bash 
#!/system/bin/sh

IP6TABLES=/system/bin/ip6tables 
IPTABLES=/system/bin/iptables

# Log all iptables events (just for debugging)
$IPTABLES -A "afwall" OUTPUT -j LOG --log-level 7 --log-prefix 'afscript: '

#Since you not using IPv6 you could block it 
$IP6TABLES -P INPUT DROP  
$IP6TABLES -P OUTPUT DROP

# Block  Outgoing Connections
$IPTABLES -A "afwall" -d 23.4.92.33/32 -j REJECT
$IPTABLES -A "afwall" -d 23.32.0.0/11 -j REJECT
$IPTABLES -A "afwall" -d 23.64.0.0/14 -j REJECT
$IPTABLES -A "afwall" -d 23.253.56.120/32 -j REJECT
$IPTABLES -A "afwall" -d 64.207.128.0/18 -j REJECT
$IPTABLES -A "afwall" -d 68.232.32.0/20 -j REJECT
$IPTABLES -A "afwall" -d 91.103.140.0/24 -j REJECT
$IPTABLES -A "afwall" -d 104.16.0.0/12 -j REJECT
$IPTABLES -A "afwall" -d 104.64.0.0/10 -j REJECT
$IPTABLES -A "afwall" -d 116.214.0.0/16 -j REJECT
$IPTABLES -A "afwall" -d 118.214.0.0/16 -j REJECT
$IPTABLES -A "afwall" -d 198.232.125.88/32 -j REJECT
```

This isn't an AFWall+ problem.

**Comment by Primokorn** [comment]
Did you try this script on your device? Which Android version do you have?

**Comment by CHEF-KOCH** [comment]
Yes it works, I always test my stuff.

**Comment by Primokorn** [comment]
I updated Busybox to 1.23.2 and check the spaces into the script. It works fine now. Cheers.
