### ISSUE TITLE
excluding apps from custom script rules

### ISSUE THREAD

**Issue by irregularisnotrandom** [ukanth/afwall#378]
Hi

I am not an advanced iptablws user to know this. it would be nice if one could exclude some apps from the rules from the custom scripts.

**Comment by CHEF-KOCH** [comment]
Hi,

that's [already possible](https://www.netfilter.org/documentation/) but we talking more or less about a feature that is only for advance users. Also often called application level firewalling which needs _CONFIG_IP_NF_MATCH_OWNER_ compiled into your kernel.

AFWall+ and his gui should do most (if possible all) the magic by touching on the applications to restrict them or not. In our custom script section I already gave an example to block specific domains or ip's - I think that's enouth. Excluding something with a firewall is seriously the wrong logic, you should better block or not block something but to exclude xyz can could lead in security problems e.g. an application could easily spawn a child process which maybe would never been blocked by such rule. 

Please also remember that UID (user name) + GID (group name) never helps because these are the ID's of the current executing users/group for the application. Means that blocking a specific application is usually done by blocking all ports that the application uses. In fact that only works if the user can't change the ports which the application use. 

```bash
$ iptables -m owner --help

owner match options:
[!] --uid-owner userid[-userid]      Match local UID
[!] --gid-owner groupid[-groupid]    Match local GID
[!] --cmd-owner                              Matches if the packet was created by a process with the given command name.
[!] --pid-owner                           Matches if the packet was created by a process with the given process id.
[!] --pid-id processid             Matches if the packet was created by a process with the given process id
[!] --socket-exists                  Match if socket exists
```

**Comment by irregularisnotrandom** [comment]
Thanks i will check it out
