### ISSUE TITLE
unable to refresh app list

### ISSUE THREAD

**Issue by somename456** [ukanth/afwall#381]
AFWall+ 2.0.0-ALPHA-2, using Lollipop 5.1, CM12.

In ALPHA-1, pulling down the app list refreshed it, no longer possible in ALPHA-2.

It's useful when installing/uninstalling apps, one  must now destroy the activity each time to update the app list

**Comment by CHEF-KOCH** [comment]
Test scenario:
* Open Titanium Backup 
* Open AFWall and switch back to TiB (from recent panel) 
* Remove xyz app switch back to AFWall+ via pressing the back button under TiB
* You'll see that the list doesn't update anything 

Workarounds:
* As mentioned you can kill the activity 
* .. or manually click on the _Reload Applications_ button.


Confirmed it's bug, not only CM is affect by this behavior any ROM because _broken_ su. We working on that, that su thing will also fix some other small problems that are already on our list here.
