### ISSUE TITLE
Is there a way to apply rule only on certain SSID?

### ISSUE THREAD

**Issue by DavydLiu** [ukanth/afwall#401]
For example, I want to apple rule for certain public WiFi but not to my home WiFi. Is there a way to achieve this?

**Comment by CHEF-KOCH** [comment]
This is not a right place for common talk about how to handle iptables and specific user problems, better use the XDA thread for such questions and read the official documents. 

But to give some examples, of course it needs to be changed for needs:
```
# Needs NETFILTER_XT_MATCH_MAC in kernel alias zcat /proc/config.gz | awk '/CONFIG_NETFILTER_XT_MATCH_MAC/' (check against modprobe config)
# Allow dns (port 53 for a specific mac) via mac to lan
iptables -t nat -A PREROUTING -i <interface-name> -m mac --mac-source <MAC_of_Android_device> -p udp --dport 53 -j DNAT --to <internal_LAN_DNS_IP>

# Drop a mac (local traffic)
iptables -A INPUT -m mac --mac-source <MAC> -j DROP

# Block routed traffic
iptables -A FORWARD -m mac --mac-source <MAC> -j DROP

# Specific time from x between y
iptables -A INPUT -m time --timestart 04:30 --timestop 12:30 --weekdays Sun,Mon,Tue,Wed,Thu,Fri,Sat -j DROP
```

**Comment by DavydLiu** [comment]
Thanks for the example. Unfortunately, I have no clue of it. Should I modify the IPtable in the app?

Also, this is not a common talk. If there is no such feature, I can change it to feature request.

**Comment by CHEF-KOCH** [comment]
No we don't need such feature , in the name of security you should only connect to trusted sources and for the rest the normal user can simply switch Wlan of or use existent apps e.g Smart Network and million others they handle a whitelist internal without need to mod any iptables.

If you're not an expert or able to read the documents you should never use any scripts, since this ends usually with more troubles or security holes.
