### ISSUE TITLE
[Feature] Enable option to not show disabled apps.

### ISSUE THREAD

**Issue by brtpnc** [ukanth/afwall#403]
Some people disable some apps (e.g. calculator, default Internet browser on custom ROM, Google+ etc.). Why not have an option to not display those in the list?

**Comment by CHEF-KOCH** [comment]
For what?  In case you re-enable them and need to configure the firewall. If you not need the apps just uninstall them. Since we have root this is no problem to freeze/uninstall it.

**Comment by brtpnc** [comment]
It's also not a problem to ignore disabled apps when drawing the list.

**Comment by CHEF-KOCH** [comment]
It's a security/data leakage risk on blacklist mode since the re-enabled app needs a re-configuration.

**Comment by brtpnc** [comment]
It's not a data leakage risk when you default to blocking them by default on re-enable.

**Comment by CHEF-KOCH** [comment]
Yes on blacklist mode it is, install gapps...start the System...leakage, same logic on installing them from the market or first boot the Stock android without any initial configuration.

**Comment by ukanth** [comment]
I doubt there are API's supported by Android. So may not be possible at all

**Comment by CHEF-KOCH** [comment]
7 reasons against such gimmick:

1) Security (see my comments), if course whitelist is default, but AFWall+ does not comes pre-installed on any ROM I know. There are only some TWRP mods to handle it, but that's unofficial. Rest is a blacklist problem.
2) GUI, Android itself does not offer any user interface to freeze apps, this must be done by external apps like Titanium Backup, Xposed modules, or any other apps (or for pros via adb) a normal user never use this outside any app, as I said TiB > 50 mio downloads and +50 or more illegal downloads and users. 
3) It's useless, instead of freeze any app just uninstall them or backup just only his app data and re-import it after a fresh and clean/updated installation of the new app (via the market, adb, or any other place).
4) No Firewall I know use such feature because it's useless and redundant and possible ends up with duplicates (in case new sig/permission are changed), since traditionell firewalls are controled by the user, if a software is getting uninstalled by the user, the interface shows an separate button (on android this is not necessary since there is no permission for internet anymore) or it cleans it out itself (example, wfc, pfsense, kaspersky firewal, and 100 others I know using only these two methods).
5) There is no performance improvement at all, one of my test device is an I9100 which is now 4+ years old which includes 402 apps (312 with internet permission), changing the icon on/off or any other drawing option won't improve the performance on a real device, see last commits they're more theoretically improvements (drawing took 2 seconds + some to fetch icons). There is no non-cached open source app that is faster (if there is one, show me the code), except the apps that caching the entire list and only updating them per request, we overall talking about milli seconds. On quad cores it took < 400 ms.
6) Provide an feature that "does nothing" or is only for a small range of people mostly ends up with bad comments, rankings or just confuse the people.
7) Future: Freezing apps is not a daily usable feature, it will be possible removed in newer Android versions, install/uninstall options are always present.

So I still absolute no reasons. We have other things that are more important to fix or to improve if someone wants to make a pull request, feel free but that must respect the mentioned con arguments anyway.

**Comment by brtpnc** [comment]
> I doubt there are API's supported by Android. So may not be possible at all
```
getPackageManager().getApplicationInfo("com.blah.blah", 0).enabled;
```
> 1) ...
I think you assumed that you can disable apps before even first boot of the device. And the leakage problem applies despite that (you need to not configure wifi and mobile data to not have it). I don't understand your point.
> 2) GUI, Android itself does not offer any user interface to freeze apps
wtf? https://i.imgur.com/jWzvNtb.png
> 3)
Some apps can't be uninstalled.
> 4)
But this is also the case for normal apps...
> 5)
It's not about performance improvement, but to declutter the app list.
> 6)
Negative comments about an app list filter?
> 7)
I don't think so.

Tip: if you're going to not make a simple switch to not show disabled apps on the list, focus on getting Bluetooth tethering to work instead of claiming it's "not a bug".

Thank you.

**Comment by CHEF-KOCH** [comment]
> I think you assumed that you can disable apps before even first boot of the device. And the leakage problem applies despite that (you need to not configure wifi and mobile data to not have it). I don't understand your point.

The leakage problem is not the OS (in this situation), it's the app, since e.g. installing gapps automatically starting them (especially on the first installation, the user gets an prompt) even without this, there is no doubt that changing the permission together with blacklist mode is problematic directly on the device, wifi/mobile is enabled for the update (to dl them, except if you're on adb/terminal to push it) and there is no chance to control such situation. In Android M exactly this was changed since the user can contrll _some_ permissions and do not get an dialog to accept all the changed stuff or deny them (eat or die philosophy). Both are real case scenarios. 

> wtf? https://i.imgur.com/jWzvNtb.png

On which rom is that? Disable is not freeze from what I know, or we talking about different things, on Stock there is no freeze button, and this button is definitly called freeze and not stop (disabling the main activity never prevent from been called again btw).

> Some apps can't be uninstalled.

Which one, you said in the first post G+, calculator or stock browser, all of them can be uninstalled and re-installed again without any problems. Even Google Play Services can be uninstalled, that may break some external apps but it works.


> But this is also the case for normal apps...

Yes and normal apps should be shown, same as all others, like I said.


> It's not about performance improvement, but to declutter the app list.

For what? People that can't use the search or scrolling down? Really? Is that so hard? I use over 412 apps, scrolling down to find the correct one normally take some seconds. To declutter something we already have the ability to look if the app use the internet permission or not, all other apps are not listed. 

> Negative comments about an app list filter?

Yes, because as I said it does nothing. After you build a project, do you hide the project folder or do you remove the entire folder including sub-folders? I bet the last one. 

> I don't think so.

Nobody knows, in the past a lot of features was removed and re-adopted by Cm and other projects, that's why a lot of people prefer such ROM's, for security, speed and other reasons.


> Tip: if you're going to not make a simple switch to not show disabled apps on the list, focus on getting Bluetooth tethering to work instead of claiming it's "not a bug".

If all is so easy make a pull request without breaking any security aspect. 
I don't know why you come up with another thread now, like that BT thread, but if you really looked in that thread I gave already much detailed answer. There was no answer after my last comment and Android hits now the 5.1.1+ state so this is also possible fixed, searching 2 seconds the AOSP issue tracker would reveal that this is also possible ROM related, a lot of people fighting with this.

**Comment by ukanth** [comment]
@CHEF-KOCH, There is nothing wrong about asking for feature. 

@brtpnc, The problem is we already have plenty of feature not used by many users and adding feature based on user input might clutter the UI or preferences even more. You can reopen and I will keep it as feature. If many people wants similar feature, then i will consider implementing it.

Thanks.

**Comment by CHEF-KOCH** [comment]
> There is nothing wrong about asking for feature. 

This is not against a feature requests. The major problem is the security aspect and other reasons. I still not understand why not simply use the uninstall option, even with 400+ apps there is nothing wrong about this, and as I wrote freezing/disabling is OS problematic, it's may getting removed or is implemented in xyz app, so a user may not see this or is able to use it and this definitely ends up with comments.

So, if you want to implement such feature the people ask for strong filters like Titanium Backup or other apps that managing the apps or the overview list, this is more a database related thing and has nothing much to do with a firewall. There is a search, the scroll down option, the uninstall option, the just ignore it option, several filters for UID/Name and install time I think we have a lot of other problems and seriously tell me here that you install/uninstall/freeze/disable xyz apps the whole time?!

**Comment by brtpnc** [comment]
CHEF-KOCH, I think you might horribly mistaking my intent. All I want is a simple option in preferences to not show disabled apps (it's called "disable" not "freeze" and it's present in Android API since ICS (so it's not "only on custom ROMs"). I'm telling you again that you cannot uninstall some system apps and the only option is to disable them in "Apps" screen.

Previously, I asked for a (again, dead simple and obvious) feature to allow pinning apps to top of the list (I have AFWall on quick launch shortcut and frequently switch app firewall on and off on mobile data) and I was faced with similar hostility from you for reasons I cannot understand (what's wrong with a button in "Traffic Details" screen that is half-unused?). I'm tired of dealing with you and will not issue another feature request again.

Have fun.

**Comment by CHEF-KOCH** [comment]
You can uninstall all apps, may not with your posted gui but with adb/terminal/TiB so you just ignore this, if you really need such an option feel free to ask in AOSP to integrate an Task Manager which is such an all-in-one-solution. I did not have this option on STOCK (only that was changed removed dms/play), I yesterday checked it, but as I said it could be apk/system depending, so it does not plays any role if that it's implemented in the OS or not if the GUI/APK doesn't provide this function. 

> Previously, I asked for a (again, dead simple and obvious) feature to allow pinning apps to top of the list (I have AFWall on quick launch shortcut and frequently switch app firewall on and off on mobile data) and I was faced with similar hostility from you for reasons I cannot understand (what's wrong with a button in "Traffic Details" screen that is half-unused?). I'm tired of dealing with you and will not issue another feature request again.

You come up with a BT thread and now with yet again topic that doesn't plays any role here in this discussion because lack of arguments, I gave 7 con arguments and there is not any pro argument for this feature except laziness or user to ignore the given options. 

> ... and I was faced with similar hostility from you for reasons I cannot understand  ...

Yes, seems you resist against arguments in general. We have an pin option, install an app with internet permission, open AFWall+ and you'll see that this is pinned at the top, so what do you want more?! The next user ask for a switch for show it for xyz days, useless because the normal user not change the entire day app options, just learn how to work with custom scripts or use different profiles/tasker if you have that special situations. As I did say this would ends up with a database and not anymore with a firewall aspect. 

> I'm tired of dealing with you and will not issue another feature request again.

You may realize someday that Android is customizable via apps, scripts, mods, whatever and you can't make it right to everyone. That's why people use apps, for this situations, and this is for AFWall+ too, there is still not argument to implement xyz that's gonna be removed, bugged in the next Android version, only a few users needs/understand it and other reasons. For people that are able to root the phone I expect some effort and intelligence to manage xyz scenario. 


You're just lazy and angry about past closed requests that's the real problem here, sorry for saying this. So don't see this so emotional and personally, just give good arguments/logs/ideas/alternatives that's all I want, same like in the other two mentioned threads - nothing to confirm or lack of arguments this will just end up with nothing, in this time we talked here I could install/uninstall 100 apps including to configuring them without any additional gimmicks (also called batch, but okay,..)

I no longer waste my time here, thanks.
