### ISSUE TITLE
afwall-2.0 alpha firewall log

### ISSUE THREAD

**Issue by two-dogs** [ukanth/afwall#406]
i am really enjoying the multiple profile option, i was wondering if the firewall log could show what profile is in use?

**Comment by CHEF-KOCH** [comment]
Could you please re-label the topic to something that have todo with your question, like 'Feature Request: Add multi-user profile indicator' or something like this. Thanks.

Yes, generally it's possible. The question is if that's useful since you can name or re-name the profiles to whatever you want to. But an indicator which profile's are currently in use or exists would be help that's correct. In the normal environment the default profile is always owner, except if you use/create/changed something to multi-user.

**Comment by two-dogs** [comment]
thnks for the response, really enjoy the work you have done to the app
