### ISSUE TITLE
I need add a fire wall in my app,how can do .

### ISSUE THREAD

**Issue by yaming116** [ukanth/afwall#414]
some rules i get it from server,so i can not use this .

**Comment by CHEF-KOCH** [comment]
Please speak proper english. Nobody understand what did you want to say with this.

**Comment by yaming116** [comment]
I need to add a firewall in our software, because some of the rules is to obtain from the server, how can I do?

**Comment by CHEF-KOCH** [comment]
A firewall in a software? Software-Firewall like Outpost?

AFWall+ isn't a firewall it's just an gui for iptables, so that beginners can work with that and nothing more (of course with some other gimmicks). 

If you mean you like to add some rules to a software/app then please ensure you can give as much information as possible as explained over the given link.

**Comment by yaming116** [comment]
thx

**Comment by CHEF-KOCH** [comment]
If all is done, please close your issue report.

For additional questions feel free to ask me via eMail or Xabber/XMPP.

**Comment by yaming116** [comment]
ok
