### ISSUE TITLE
Can afwall have second "non-root edition" also, which firewalls without root (Even with some known limitations), if user wants so.

### ISSUE THREAD

**Issue by zaxebo1** [ukanth/afwall#415]
At  https://github.com/ukanth/afwall/wiki/Similar-Firewall-solutions , you have mentioned "limitations of Non-root Android Firewalls", but still many people are very happy to use "non root" firewall and their usecase is satisfied with those non-root firwall apps and these non-root firewall apps are heavily popular.

Here are four non-root firewall apps:
https://play.google.com/store/apps/details?id=com.lostnet.fw.free&hl=en     ( LostNet NoRoot Firewall )
https://play.google.com/store/apps/details?id=com.jianjia.firewall
https://play.google.com/store/apps/details?id=com.netspark.firewall
https://play.google.com/store/apps/details?id=app.greyshirts.firewall

**All these are "closed source" non-root firewall apps.** There is not a single non-root firewall app, which is open source.

---

afwall already has rooted firewall app edition
Now my feature request is that, **can the "open source" afwall have a second edition , which works as non-root (even with some known limitations as stated by you)"** That will be really great.

**Comment by CHEF-KOCH** [comment]
Hello, 

I don't know what the "open-source" vs closed source argument have to do with the limitations of the firewall and the popularity. Non-root means that stuff like netd/time/.. and such are not blocked, this is due the API restriction. 

You're statement that there is no open source non-root firewall is wrong, OpenVPN is very popular and does not need root, technical speaking it does the same as you're mentioned _firewalls_. In my eyes creating an TAP and redirect "everything" trough, that isn't really _firewall'ing_ it's more a bridge that also can be handled by Android without any external apps. The reason why OpenVPN isn't a root app is, as mentioned the API that doesn't allow creating e.g. an TUN so that's why this app doesn't need root - again for me this isn't a firewall - It's more a bridge since not everything will be redirect, that can be seen if you use Whireshark/Burp and with apps that use hardcoded DNS, it still bypass the firewall (in my gists I have a fix for this published - it's called VPN data leakage). There are other examples why iptables is a true firewall and why VPN isn't. 

To answer your real question about AFWall+ and no-root, no it's simply not possible and it's already explained in our FAQ that low-level access needs root. In fact many people saying rooting the device is a security problem, on XDA I showed that this is bullshit, the last security vulnerabilities gave us the confirmation for this. Waiting for you OEM/provider to fix stuff takes months, installing CM (that 12/12.1 - that fixed stagefigher since months without hype btw!) takes minutes. In fact that improve the security since YOU have CONTROL and not your OEM/Provider. But that root vs non-root argument is a point to open another topic.

There is no way to handle internal processes that are already running by the OS as root (like netd >4.+) without root, that's the nature how Linux works. If you don't like it, show Torvals a method to running restricted system processes without root and without losing the security aspect - Nobody can.

**Comment by ukanth** [comment]
There is already an open source non root firewall called Netguard from respected developer. Please check it out.

**Comment by Jkarhani** [comment]
I still can't find any non-root firewall like the afwall+ : it doesn't disconnect and have a password for the settings!! 
Any application similar please..?
