### ISSUE TITLE
Multiuser doesn't work on Android 4.4.4

### ISSUE THREAD

**Issue by Magissia** [ukanth/afwall#423]
Checking the "multi user" checkbox doesn't add any of secondary user UID to the chains.

==========
IPv4 Rules
==========

Chain INPUT (policy ACCEPT 3278 packets, 844K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 102K  123M bw_INPUT   all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 102K  123M fw_INPUT   all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 oem_fwd    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 fw_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 bw_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 natctrl_FORWARD  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain OUTPUT (policy ACCEPT 1118 packets, 113K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 1343  145K afwall     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
69360 7073K oem_out    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
69360 7073K fw_OUTPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
69360 7073K bw_OUTPUT  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 1027  102K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            state ESTABLISHED
    0     0 afwall-vpn  all  --  *      tun+    0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-vpn  all  --  *      ppp+    0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-vpn  all  --  *      tap+    0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-vpn  all  --  *      *       0.0.0.0/0            0.0.0.0/0           [goto]  mark match 0x3c/0xfffc
    0     0 afwall-vpn  all  --  *      *       0.0.0.0/0            0.0.0.0/0           [goto]  mark match 0x40/0xfff8
    0     0 afwall-wifi  all  --  *      eth+    0.0.0.0/0            0.0.0.0/0           
  227 19323 afwall-wifi  all  --  *      wlan+   0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-wifi  all  --  *      tiwlan+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-wifi  all  --  *      ra+     0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-wifi  all  --  *      bnep+   0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      rmnet+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      pdp+    0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      uwbr+   0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      wimax+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      vsnet+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      rmnet_sdio+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      ccmni+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      qmi+    0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      svnet0+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      ccemni+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      rmnet_usb+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      wwan+   0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      cdma_rmnet+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      usb+    0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      rmnet_usb+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      clat4+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      cc2mni+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      bond1+  0.0.0.0/0            0.0.0.0/0           
    0     0 afwall-3g  all  --  *      rmnet_smux+  0.0.0.0/0            0.0.0.0/0           
Chain afwall-3g (19 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-3g-postcustom  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-3g-fork (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-3g-home  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-3g-home (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10049
Chain afwall-3g-postcustom (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-3g-fork  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-3g-roam (0 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain afwall-3g-tether (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-3g-fork  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-reject (66 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 LOG        all  --  *      *       0.0.0.0/0            0.0.0.0/0            limit: avg 1000/min burst 5 LOG flags 8 level 4 prefix "{AFL}"
    0     0 REJECT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            reject-with icmp-port-unreachable
Chain afwall-vpn (5 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10027
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10031
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10049
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10050
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10113
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10129
Chain afwall-wifi (5 references)
 pkts bytes target     prot opt in     out     source               destination         
  227 19323 afwall-wifi-postcustom  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-wifi-fork (2 references)
 pkts bytes target     prot opt in     out     source               destination         
   98  6458 afwall-wifi-lan  all  --  *      *       0.0.0.0/0            192.168.150.0/24    
   20  1222 afwall-wifi-wan  all  --  *      *       0.0.0.0/0           !192.168.150.0/24    
Chain afwall-wifi-lan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10001
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10002
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10015
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10018
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10019
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10020
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10022
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10027
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10029
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10031
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10033
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10037
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10041
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10047
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10050
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10051
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10053
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10054
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10058
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10061
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10062
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10064
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10069
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10070
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10073
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10074
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10075
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10076
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10081
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10090
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10093
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10095
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10096
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10099
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10105
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10109
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10111
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10112
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10113
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10114
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10115
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10116
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10124
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10129
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10130
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10132
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10135
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10137
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10140
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10141
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10142
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10143
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10144
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10145
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10146
Chain afwall-wifi-postcustom (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  118  7680 afwall-wifi-fork  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-wifi-tether (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-wifi-fork  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain afwall-wifi-wan (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10027
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10031
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10049
    0     0 afwall-reject  all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner UID match 10129
Chain bw_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain bw_INPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 5102 7239K            all  --  *      *       0.0.0.0/0            0.0.0.0/0            ! quota globalAlert: 2097152 bytes 
98149  122M            all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner socket exists
Chain bw_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
 2595  198K            all  --  *      *       0.0.0.0/0            0.0.0.0/0            ! quota globalAlert: 2097152 bytes 
68560 6964K            all  --  *      *       0.0.0.0/0            0.0.0.0/0            owner socket exists
Chain bw_costly_shared (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 bw_penalty_box  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain bw_happy_box (0 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain bw_penalty_box (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain fw_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain fw_INPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain fw_OUTPUT (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain natctrl_FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain natctrl_tether_counters (0 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain oem_fwd (1 references)
 pkts bytes target     prot opt in     out     source               destination         
Chain oem_out (1 references)
 pkts bytes target     prot opt in     out     source               destination         

==================
Network interfaces
==================

lo: unknown
dummy0: unknown
tunl0: VPN
sit0: unknown
ip6tnl0: unknown
wlan0: wifi

========
ifconfig
========

dummy0    Link encap:Ethernet  HWaddr 22:6E:8A:D4:B4:5D  
          BROADCAST NOARP  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
ip6tnl0   Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1452  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:1457 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1457 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:353580 (345.2 KiB)  TX bytes:353580 (345.2 KiB)
sit0      Link encap:IPv6-in-IPv4  
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
tunl0     Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
wlan0     Link encap:Ethernet  HWaddr ::censored::  
          inet addr:192.168.150.162  Bcast:192.168.150.255  Mask:255.255.255.0
          inet6 addr: ::censored:::3bf7:a70d/64 Scope:Global
          inet6 addr: ::censored:::fead:78b9/64 Scope:Global
          inet6 addr: fe80::646:65ff:fead:78b9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:136965 errors:0 dropped:3922 overruns:0 frame:0
          TX packets:74246 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:163530926 (155.9 MiB)  TX bytes:8719115 (8.3 MiB)

===========
System info
===========

Android version: 4.4.4
Manufacturer: asus
Model: Transformer TF101
Build: KTU84Q KatKiss-4.4.4_035
Active interface: wifi
Tether status: no
Roam status: no
IPv4 subnet: 192.168.150.162/24
IPv6 subnet: fe80::646:65ff:fead:78b9/64
/system/bin/su: not present
/system/xbin/su: 75364 bytes
/system/app/Superuser.apk: not present
Superuser: eu.chainfire.supersu v2.46

===========
Preferences
===========

activeNotification: false
activeRules: true
appVersion: 15208
bb_path: system
disableIcons: false
disableTaskerToast: true
dns_value: auto
enableAdmin: true
enableConfirm: true
enableIPv6: true
enableInbound: true
enableLAN: true
enableLog: true
enableLogService: false
enableRoam: false
enableVPN: true
fixLeak: false
hasRoot: true
ip_path: system
isRootAvail: true
locale: en
logTarget: LOG
multiUser: true
multiUserId: 0
notifyAppInstall: true
passSetting: p1
patternMax: 3
profilePwd: <censored>

pwdEncrypt: true
showFilter: true
showUid: false
sort: s0
storedPosition: 0
sysColor: -10432

======
Logcat
======

23:55:02 Starting root shell...
23:55:02 [libsuperuser] [SU%] START
23:55:03 Root shell is open
23:55:22 isWifiApEnabled is false
00:08:00 Now assuming NO connection (all interfaces down)
00:08:00 CONNECTIVITY_CHANGE: applied rules
00:08:07 CONNECTIVITY_CHANGE: interface state has not changed, ignoring
01:31:09 isWifiApEnabled is false
01:31:09 Now assuming wifi connection
01:31:09 IPv4 LAN netmask on wlan0: 192.168.150.162/24
01:31:09 IPv6 LAN netmask on wlan0: fe80::646:65ff:fead:78b9/64
01:31:10 CONNECTIVITY_CHANGE: applied rules
01:31:14 isWifiApEnabled is false
01:31:14 CONNECTIVITY_CHANGE: interface state has not changed, ignoring

**Comment by CHEF-KOCH** [comment]
#271 + #259

**Comment by Magissia** [comment]
#259 is about restricting the choice of enabling multi user or not to the owner account.
Comparing with #271, I don't see any afwall10 at all in the rules. (User id 1,10 and 11 exist on the device) while "multiUser: true"
Are we sure #271 is exactly the same problem ? In both cases, it cause multi user protection malfunction, but is the problem caused at the same level ?
Should I rename to "Multi user specific chains are not created" ?

**Comment by CHEF-KOCH** [comment]
Yes, that happens if I don't have enough information. Multiuser is a wide common used term. But seems you answered it already yourself. In case 271 is exactly the same problem you need to close this ticket an answer directly in the proper place. 

AFWall+ can't not fix problems that are rom or iptables specific. As you may noted no one is working on the entire iptables stuff - that means all of these reported problems will [at this point] never be fixed until I do or someone which knows a lot about iptables.

**Comment by Magissia** [comment]
Multi user isn't rom or iptables specific, it is Android specific since at least 4.4.

iptables is technically able to filter packets for all users, adding manually the UID of second user's app inside the custom script section works without flaws.

It means, nobody has to work on iptables itself, nobody has to check if weird roms doesn't support it.
If you support multi user for AOSP it should work for everyone past 4.4.

AFwall provides to iptables the UID to block, it's not iptables that search for them.

**Comment by CHEF-KOCH** [comment]
Multi-user (API 17) is of course ROM specific, Android 5 handles and fixes problems that 4.x doesn't could handle. Android is handled by 24.000 devices (stats from 2015)! So fragmentation is always a problem. Everything that have todo with inet is iptables specific, AFWall+ is only the gui to take easier control over it. Or else you can do the same via terminal/adb and scripts and don't need the GUI.

Seems you never read any iptables document, it wasn't designed for multi-user (from the beginning) and it suffers from a lot of security problems, that's why I never recommend to use multi-user. Ie if an root process spawns an child process this may leaks in traffic that can't be controlled (via AFWall). I also explained this several times over here on GitHub. Of course this is only one example. There are a lot of more problems with are [ROM specific](https://code.google.com/p/android/issues/list?can=1&q=multi-user&colspec=ID+Type+Status+Owner+Summary+Stars&cells=tiles).  

> It means, nobody has to work on iptables itself, nobody has to check if weird roms doesn't support it.

Multi-user is only supported since iptables v 1.3.x btw. And remember that not every rom contains iptables. If you're watched the latest changes there was a lot of changed code to get iptables working with Android 5.x. 


Multi-user also suffers from a lot of security problems and other problems especially on Android 4. Read [here](https://code.google.com/p/android/issues/detail?id=177463), [here](https://code.google.com/p/android/issues/detail?id=157208) or [here](https://code.google.com/p/android/issues/detail?id=48418). This truly shows that this isn't nothing more then an experiment (yet). The implementation (Android specific) is lacking from common problems. 

And no-one except me and some other guys looked at the iptables stuff, because this a lot of more complicated and problematic since we don't want hidden traffic.

**Comment by Magissia** [comment]
The way I fixed it manually with custom script on each device I own shows it is not ROM specific, most runs stock system and are not from the same OEM. 
I am reporting it doesn't work because the maintenance burden of manually adding each secondary user app UID to custom script is high, I'm not doing any voodoo to get this working I'm just copy pasting what AFwall does for android user 1 and add a digit to make it apply to user 10.

Thanks for the link but they doesn't apply for what I'm talking about, we don't need to know if the secondary user also installed the app I am blocking for myself, block it in case to be safe if you don't know. It doesn't require any voodoo to know if a secondary user exist, it can be checked by looking if a folder exist. 

We don't need to know who runs AFwall, if someone else than user 1 has root access, the owner has more serious problems to fix than the firewall

Yes this solution has a flaw, if a secondary user has an app the owner doesn't have, it won't be possible to block it for the secondary user from AFwall, but this problem is minor compared to blocking absolutely nothing. 

You are right if you say this is not perfect, but I wasn't able to find a single device running 4.4.4 where I couldn't apply this method. (more precisely, I didn't had to modify anything from my hacky shell fix to get this working on each device I had on hands) 

And please let's exclude root usage, if root is used of course it is complicated, it's up to the user to manage that if the user trust or not process it grants root to. 

If there is no plans to support multi user for 4.4.4, hide the multi user option on device with system version inferior to 5. Boom, resolved. Officially not supported and no plans to. 
If you have any device where the multi user option works on a system running 4.4.4, I would love to have the name. 

I am obviously running a version of iptables that support the owneruid parameter (else AFwall wouldn't work at all)

**Comment by CHEF-KOCH** [comment]
If it would be Android specific it would work for all exactly the same, the fact that the provider/manufacture is using AOSP doesn't mean that it contains exactly the same (drivers, firmware, binaries, apps and other stuff is often changed .. for security, performance or ad reasons). So this is why it works different on the 24k devices (called fragmentation due different configs, ROM's, changes, ...). Because it works for you doesn't mean it works for all, AFWall+ is not an AOSP only product, we also supporting other ROM's like AOKP, Kang, CM, ... so they are definitely different from AOSP. 

You did not fix anything, you used a workaround which was already explained on the documents, here on the Wiki and (as you found yourself) on another thread. As I said this also could be done with adb/terminal and have nothing much todo with AFWall+, this is why I wrote that custom scripts is for advance users only. Because there are several problems which needs background knowledge about how the three way handshake, TCP, UDP, OSI, ICMP and TCP/IP layers work + you need to know and search for existent problems that are ROM/iptables related and possible already known or on the todo list, this requires much much time. Or if you're smart enouth you can debug it and post a good quality bug-report which will be marked as 'obsolete' on the AOSP tracker because Google do not want fixing it (due several reasons I explained over the Wiki here). 


> Thanks for the link but they doesn't apply for what I'm talking about, we don't need to know if the secondary user also installed the app I am blocking for myself, block it in case to be safe if you don't know. It doesn't require any voodoo to know if a secondary user exist, it can be checked by looking if a folder exist.

The links fitting perfect to show that this is ROM specific and that multi-user is just an unfinished business, if you read all of the reported problems you would know that it's also bugged under Android 5. due the lack of usability and bugs. Why AFWall+ should fix this problems, after another update there will be other or the same problems again. Such problems needs always to be fixed at the lowest level and this isn't AFWall+ - it's Android. We can only provide xyz feature if it's possible, and this must for all (or most users and ROM's/configurations) if not everyone would blame AFWall+ and leave a bad 'blah blah nor working' review here on GitHub or on the Market/XDA.  


> We don't need to know who runs AFwall, if someone else than user 1 has root access, the owner has more serious problems to fix than the firewall

Android doesn't allow to handle multiple root users at the same time, you can create them but there will be no traffic since this is a security limited function. This is also the reasons why you can't establish two ifaces at the same time. If will be reject after some seconds. This is also explained on the official Android AOSP documents and within the source.

> Yes this solution has a flaw, if a secondary user has an app the owner doesn't have, it won't be possible to block it for the secondary user from AFwall, but this problem is minor compared to blocking absolutely nothing. 

Agreed enabled protection is always better but you don't need it since there will be no traffic. Especially on whitelist but we only supporting blacklist for this feature since it makes no sense to restrict something that is already limited. 


> And please let's exclude root usage, if root is used of course it is complicated, it's up to the user to manage that if the user trust or not process it grants root to.

This is Android specific since netd is running all the time under root privileges. And this is on every AOSP based ROM 4.x. And this will never be changed, since it would break the entire network stuff. See also the source or my article about background OS usage. 



> If there is no plans to support multi user for 4.4.4, hide the multi user option on device with system version inferior to 5. Boom, resolved. Officially not supported and no plans to. 

I already wrote, there is no one which are fixing iptables related problems, that's the reasons AFWall+ suffering from years old problems. That needs to be changed within iptables + AFWall+, if iptables doesn't support xyz or suffering from bug we can implement xyz it will never work. Nftables is possible the answer, if it hits the final build (some day). It will fix many many problems that coming with iptables and is a lot of faster and resource friendlier. 
Android 4.x is more or less already death, people switching to Android 5 and this (yet another time) re-wrote most of the APi's again (and M is already coming which have the agility to block xyz permission out-of-the box similar to XPrivacy). If Cm or any other team is able to implement an INET API to restrict it, that would mean nobody need a firewall anymore since you could use this function instead of handling iptables or external apps (maybe only to simplify process e.g. for connectivity changes). 


> I am obviously running a version of iptables that support the owneruid parameter (else AFwall wouldn't work at all).

For advance problems like this you need to provide logcat + dumpsys (see my debugging article) to see what's the problem behind the doors. I agree that no GUI for iptables (Avast, AFWall+, ...) not support every iptables feature, again no one is working on it to implement it. But this is only a problem for expert users. 

And again, (I already wrote this here about 20 times) Android is not a server, the inbound option should be used with caution. By default (except the lo -> loop back), all ports are closed to listening connections. If that is not so you have security problems. The only exception is P2P or the owner module we are talking about, which applies to locally generated packets only, not incoming or forwarded packets and is thus used in an OUTPUT (filter) chain. In most distros/ROM's the default group is the same as your user (login) name and can be checked with the 'id' command (example id CHEF-KOCH) which reveal the active group that is used by iptables to grant or reject/block access. 


I hope this is enouth, I wont spent my time any longer in this thread. 

CK

**Comment by Magissia** [comment]
Seems like there was a misunderstanding, if a workaround works for a lot of 4.4.4 devices (wasn't able to find one where it doesn't work on a large panel of Cyanogen slim paranoid pacman OmniROM AOSP AOKP Sense) , why couldn't it be integrated in a cleaner way directly to AFwall?

**Comment by CHEF-KOCH** [comment]
Because 'a lot of' != all. Because it works for you doesn't mean it works on CM, because if it works on CM it doesn't mean it work on Kang. To track every change is impossible for me or for ukanth and even if we monitor each new change that was made on netd, that means that there is still a major gap between adobt this changes and merging/releasing them into AFWall+ That's one of the reason I wrote on the wiki 'no alpha/beta' support. Since between x change it it's always be possible that there was y change made (that hit the final) so the entire work between them would be useless. If we would have a lot of more people here it would be maybe possible but not for 5 people. And I need to pay my bills, that's why I'm hiding a lot of changes here. 

To integrate xyz workaround into AFWall+ also have a weakness, it confuses (maybe) beginners - even if I wrote millon lines on the documents most people never read this. If they would some question would be never asked here or they found out by themselves how to handle xyz problem.
