### ISSUE TITLE
Allow background data control

### ISSUE THREAD

**Issue by edgimar** [ukanth/afwall#430]
It would be great if it were possible to create profiles which also affect an apps ability to use background data.

When I am on certain Wi-Fi networks, I want to whitelist only one or two apps to be able to use background data.  I can use tasker to switch profiles, but the problem is that.AFWall+ doesn't currently seem to have fine grained control over background data usage.

**Comment by CHEF-KOCH** [comment]
From what I understand you're talking about app background data (not OS itself). This isn't possible without manipulate the app itself or change the system specific settings. 

* You can 'increase' the ttl (that's against Googles policy since you need to change this via sysctl).
* Turn off 'sync' (under Android) and if present within the app enable the 'wifi only' option. On Google Play this is implemented to avoid updating apps in the background on cellular connections. (Can also per-app controlled via the 3 dotted right corner menu 'ignore auto. update).
* Ask the developer to fix this, since you're not provide any example which app may leak background data it's difficult to say what behavior you expect. Normally if you switch to the forground and 'restart' the app from the recent it will re-etablish the connection (e.g. Firefox) this is _by design_. If there is background data that usefully means that this app requests someting which may need an active internet connection. To break this is in some cases against Googles policy, every app that have something with IAP or Google Play billing in it need every 24-48 a small range of bytes to verify the status. Blocking this is against there terms since it breaks the validation. Same is with Ads. 
* Depending which app you're were talking about they have (and need) different status, foreground, background, ... blocking this from re-sparning it's child process to do xyz may break some app features. Of course this would be only per-app specific.
* Work with custom rules, but this will (in the wrong hands) suffering from race conditions, limitations due iptables/Android itself (exit status 4).
* Use XPosed and some of the Network apps that can control the network as per white-/blacklist (via MAC/BT/..) to ensure that there is no traffic on certain conditions (not work on VPN btw).

The best and only way is to use custom iptables or better directly stay in touch with the developer to integrate an 'wifi only' feature or like G+ an option to reduce bandwidth (which compress the images). There are also some tools like 3C to manipulate the services, activities, providers or permissions - but I'm not sure if I can explain this here, since this will possible break xyz - and I generally not support to explain how to bypass xyz _official_.

**Comment by uudruid74** [comment]
I think he means background services using data.  I was just about to beg for the same.  For example, YouTube has a habit of talking to network servers when I haven't run it.  It has some background service and I have no idea what its telling them (not sniffed it yet) but I don't really care as I feel it shouldn't be using my Internet without my permission.  If I firewall it off, I can't use it.  The same can be said for a number of apps that always want to get data for you in the background and don't have an interface to tell them NO on Cellular.  In the case of YouTube, I don't want it doing background data over WIFI either! 

And most of us don't care about Google's policy.  They don't pay for my bandwidth.  I was thinking of a method of simply monitoring the LOG and dynamically changing rules via GET_TASK, but that API is no longer reliable.   Maybe something using Xposed?

**Comment by CHEF-KOCH** [comment]
Google Play services is 'telling' them. But as I can remember google is now explicit opt-out such services, I've not tried it with the latest Google products. 

About generally background data in certain apps, I've wrote several ideas on our background data thread. This isn't possible to block on certain conditions and must be 'fixed' within such apps. E.g. if an apps spawns child processes or generate random ports over different socks or proxy's it's only to 'blocking' them by an separate tunnel. 

The easiest method is to use alternatives apps and if that isn't possible you can just use external tools (or if you familiar with adb) ensure that certain (as per needs) services/broadcasts are disabled. Maybe we need to implement this, but's difficult since this breaks several services and could crash the apps and of course it's against google policy (since you could use it to kill the ads services that comes with Google Play services + other apps). 

So there is no easy solution, if someone found one, feel free to submit.

**Comment by ghost** [comment]
At least since Lollipop, you can select an app in `Settings -> Data usage` and enable `Restrict background data` for that particular app. And in the overflow menu there, you can use `Network restrictions` to mark certain Wi-Fi networks as metered, which will be treated like mobile networks when background data is restricted for some apps (or globally).

**Comment by uudruid74** [comment]
So, in order to stop YouTube from accessing the Internet when its not on-screen I have to give up all background services and start checking my mail manually.

You don't think that's a tad inconvenient?

**Comment by ghost** [comment]
On November 24, 2015 6:29:37 PM GMT+01:00, Evan Langlois notifications@github.com wrote:

> So, in order to stop YouTube from accessing the Internet when its not
> on-screen I have to give up all background services and start checking
> my mail manually.
> 
> You don't think that's a tad inconvenient?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ukanth/afwall/issues/430#issuecomment-159348905

## Is it so hard to read? This is the second time today someone has misinterpreted my comment. You can restrict background data on a PER-APP BASIS by selecting the app from the list at Data usage.

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by uudruid74** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

My apologies.  You are correct.   Thanks for the tip

---

EDDON SYSTEMS
Evan Langlois (Linux Consultant)
    evan@eddon.systems

This message is (c) 2015 by Evan Langlois and Eddon Systems.  It is intended for the recipient only. Forwarding or copying of this message is expressly forbidden without the written permission of Eddon Systems.

On Nov 24, 2015, nyuszika7h notifications@github.com wrote:

> On November 24, 2015 6:29:37 PM GMT+01:00, Evan Langlois
> notifications@github.com wrote:
> 
> > So, in order to stop YouTube from accessing the Internet when its not
> > on-screen I have to give up all background services and start
> > checking
> > my mail manually.
> > 
> > You don't think that's a tad inconvenient?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ukanth/afwall/issues/430#issuecomment-159348905
> 
> Is it so hard to read? This is the second time today someone has
> misinterpreted my comment. You can restrict background data on a
> PER-APP BASIS by selecting the app from the list at Data usage.
> -----BEGIN PGP SIGNATURE-----
> Version: APG v1.1.1

iQJYBAEBCgBCBQJWVLemOxxFdmFuIExhbmdsb2lzIChodHRwczovL2VkZG9uLnN5
c3RlbXMpIDxldmFuQGVkZG9uLnN5c3RlbXM+AAoJEGokI+O6Zk3g5boQAI+c1dTh
HzSW0u99QygbtkCxo1kIrsnzgMpqZQGtLYNWOJMQPEa8pR3hYq2neCheoixTeBzk
2pEeU02wVbTh9aM1r/vlWSRKKvabzI3Ri/L1AXAU0Yet9NWSli6B63GnzueiDnhg
C77SEuBzV34/RHm5qXNOy9NL3ncggFoeHaohXNJfUY9yF7tSEVRT+fknIiKY8bTw
bM+avJf5gf6m4gczyc/sD6On/w31jltrcBUDDRbUyrxAPWsMqmHw39WQ7XyR7ExM
fyI3/CllBJLJliG4MC/bxZdj760an9yoZkCDoVRfkAuu1SA3xh2qBA4O/P2v4WhK
iMqBuZxEzmDGHTUM5c3gr0+B6d3+rK1j8kOC4fpsGlpy8+9HvF5ci4qsjpVS+ln2
HsO0uVYxY6l3GN22sxpyTpj1J+GMVqMI4/baEFN5O1m8ioeJ2le7IXfQE1wxxGra
Mk1D1uTCYGps0GsC1bmxy/BH20iEV8MYvUo9O5ORD0gZCJi6njVLgX7tskHrPq74
qvOMTt7Fre+t6AUTWREFn7lCkvDvj4dv16lYlV5CascDD4q31xOOoGzwhancRMV2
ffe07QAjQfVxLXF4zyEtZ1Qk5qr7NA9bwAsRAJ5XwY+spXP5X4ifBYnJpTlqCgEF
5lqWNG6sGUI2B2wklpJ+i9UF8N7BjfKVLwhR
=lYCo
-----END PGP SIGNATURE-----
