### ISSUE TITLE
Failure reasons?

### ISSUE THREAD

**Issue by Efreak** [ukanth/afwall#438]
On devices that don't support ipv6, it fails if ipv6 is enabled. When a failure occurs, please give a reason if it's possible to do so; I had ipv6 enabled for several months with no problems, then either Cyanogenmod or afwall+ got updated and it stopped working (or maybe stopped silently falling, since I never actually tested it)

In any case, rather than just showing a generic toast when it fails to set rules, it would be nice for the toast to say which part failed.

Probably-irrelevant-details: I'm on cm12 nightlies, with beta version of afwall+ (via g+ group), nexus 7 2013/flo.

**Comment by CHEF-KOCH** [comment]
Well, IPv6 is bugged. The binary and the implementation within AFWall+, I already asked cernekee but he seems busy and is fine with AOSP from what I could understand. The main question is still if the final CM or any mod of the coming M will introduce an INTERNET blocking mechanism to block the permission itself for each single app, if that maybe comes true it would possible in 80% (besides the iptables stuff) better to call it instead of using AFWall+ (maybe an integration to call that sysparam would be enouth?) to block per-app basis our things we need. But I don't know that for sure since nobody knows it (at the moment).

About CM, I always said that alpha/beta releases are 'as per own risk' so that means no eta support, we're fine if you report it but not expect quickly fixes due the fact that the next nightly change stuff again. 

> it would be nice for the toast to say which part failed.

No, because an debug msg as toast would be HUGE and annoying. The debugging or 'log' stuff is designed to do this but not the toast. 


If something not works, please read our wiki how to report a useful bug report. Also ensure that Ipv6 is disabled at the moment. 

CK
