### ISSUE TITLE
connection not blocked

### ISSUE THREAD

**Issue by duud** [ukanth/afwall#440]
I've blocked all apps. After a reboot I'm seeing this in netstat.

```
 $ netstat
Proto Recv-Q Send-Q Local Address          Foreign Address        State
tcp6       0      0 ::ffff:192.168.1.2:39201 ::ffff:216.58.213.14:80 ESTABLISHED
```

**Comment by ukanth** [comment]
Do you have "Fix startup data leak" enabled ?

**Comment by duud** [comment]
Yes

**Comment by duud** [comment]
I'm on cm12.1 and it doesn't execute init.d scripts:
https://github.com/EthACKdotOrg/orWall/issues/79

**Comment by CHEF-KOCH** [comment]
<code>::ffff:192.168.1.2</code> is for Socket for router/dhcp and it's whitelisted same like <code>fe80::1,::1/255.255.255.0,::1:192.168.1.2/120,192.168.1.2]/120</code>. If you block it you'll break Port 80. So the question is if there is a strange behavior on this port you really need to block, if not there is no communication if the router isn't 'in use'.

**Comment by duud** [comment]
Sorry, but I don't understand how ::ffff:192.168.1.2 is related to router/dhcp. 192.168.1.2 is the IP of my android device.

**Comment by CHEF-KOCH** [comment]
You're not connected to any router via wifi? Please provide your AFWall+ log.

**Comment by duud** [comment]
There must be some misunderstanding, maybe I'm overseeing something... Just to be sure: I ran the netstat command on my android phone which is running afwall+,  not on my router,  I didn't whitelist any application in afwalls interface, so everything (despite DNS) should be blocked, which works since e.g. my browser app is blocked properly.  I'm not sure why the connection I posted above should be allowed in order to not break port 80

**Comment by CHEF-KOCH** [comment]
Ah okay, if I understand correct you're not connected to any wifi, just cellular connection. I've got that now. Can you anyway provide your firewall log, because I want to see some configuration stuff and such important things. So you're talked about the fact why [216.58.213.14:80](http://www.tcpiputils.com/browse/ip-address/216.58.213.14) is establish an connection over port 80. This is one IP of Google Inc. which possible also use DNS servers like (ns1.google.com/8.8.8.8) or in this case this could be some [safe browsing mechanism](https://ssl-tools.net/webservers/safebrowsing-cache.google.com).

**Comment by c3ph3us** [comment]
"This isn't spying it's just a security feature "   - & could work as backdoor...

**Comment by CHEF-KOCH** [comment]
Nah, the term backdoor is after snowdens leak often used but not many people knowing what does this really mean. Google explained which stuff will be sent in there own terms, but no one really read it. It's like Kaspersky or any other Antivirus with 'Cloud' function, it uploads not even the malware file, it sends your entire computer related infos to them, such as IP, which OS, which software, and and and. And backdoor is something you don't know about or you can't control. 

But to stay on the topic, play services itself can create an tunnel/proxy which isn't blockable by AFWall+ (via normal GUI), the problem is that this 'important' apk gets almost weekly updates and I would not waste my time to monitor each new changes. You already trusted Google by choosing to use the OS so you simply must trust them or just use an alternative modded Android OS like CM. 

To manipulate or 'mod' the play services apk is also against Googles terms, as I said you will possible break other stuff too. But if you really not want anything just use an big hosts file to block Googles dns servers and there will be no connection at all. 

Sr, this will never fixed because given reasons.

**Comment by c3ph3us** [comment]
i use cm but its based on aosp = google they share the same bugs - i contribute to aosp so i know how full of holes like Swiss cheese it is ... 

whole google api could be compromise as simple as .... " hushhhh... just use reflections"  &  i didnt get  from security manager any single exception from time i used reflections - from beginning?  - i don't know if android got any :D - specialy when gets now to SE linux ... u can simple - but there is one possibility for system to be compromised resisted - as ROM system - with  no write access to system files :D - when u can write into memory its not secure .

**Comment by c3ph3us** [comment]
second matter if u want to have not compromised system - unplug internet cable :D

**Comment by CHEF-KOCH** [comment]
Well, I understand the point that people want to get rid of xyz connection, don't get me wrong on this. Even CM sends stuff back to there servers for updates, bugreports and statistics. 

Of course everything can be compromised, but the question is, is it really worth to 'hack' it and how many effort the attackers need? Google is known as 'ddos' or 'hack' secure, I only saw in the entire google area that the server was two or three times down (and this wasn't because hackers). 

I think the entire DNS/Google stuff gets overwhelmed by the leaks, every provider can be compromised, even if he says 'we not log anything' nobody can confirm/check it or we don't know if the NSA not already compromised these providers hardware or cables itself. 

You maybe can monitor on this and tell us/me if you get a huge mass of packages by this and I will look into it, but actually I think we can close it.

**Comment by bfritz** [comment]
@CHEF-KOCH can you expand on this statement?

> The OS have certain aspects which can't be blocked by AFWall+, or
> not for 'normal' users. E.g. as mentioned to block the entire domain
> will also destroy the safe browsing mechanism or the ability to submit
> apk checks.

I am trying to reconcile it with my mental model of AFWall+ as an iptables rule generator (like ufw, Shorewall, etc.).  Understandably AFWall+ won't block connections that are started prior to the rules being loaded into netfilter.  But after AFWall+ is running (in whiltelist mode), I assumed the default policy for outbound traffic would be REJECT and there would be very few default exceptions--perhaps just DNS and DHCP.  Seeing an HTTP socket back to Google (or CM) would surprise me as well.

Am I overlooking something about how traffic might bypass netfilter despite whiltelist mode?  Or a set of behind-the-scenes exceptions AFWall+ makes anticipating certain user expectations?

Thanks.

**Comment by CHEF-KOCH** [comment]
* Tunnels such as VPN/Proxy which e.g. will be created for Googles license checks can't be blocked via the GUI 
* External apps aren't blockable too via GUI e.g. OpenVPn/Connect 
* The default policie doesn't play that much role, due the fact the script is suffering from several 'security problems', see [here](https://github.com/ukanth/afwall/pull/412) and [here](https://github.com/ukanth/afwall/pull/354). 
* DNS 'redirect' or whatever we want to call that, is in some Google exclusive apps hardcoded, e.g. Chrome or must be explicti opt-out via additional addons/extensions or 'config' hacks. 
* The dnsmasq and iptables aka netfilter suffering from several problems, especially if you use 'old' binaries on newer ROM's (that mus always fixed by the ROM dev and not the user [to avoid problems]). 
* To harden DNS 'security' aspects is an mission impossible situation, see my state over [here](https://github.com/jedisct1/dnscrypt-proxy/pull/262)
* EVERY real paid app which use google services api and LVL needs a connection every 24-48 hours to verify the license (this is by design).
* Cracking on the API's cause a lot of problems, not only the _bad_ things, like ads services or license checks, it also would break fundamental things, the G. Play services isn't designed to 'spy' moreover it's designed to download 'security' stuff like updates IPC <-> Play services <-> Play Store. If you cut of the entire IPC system (e.g. with no-gapps) all depending services return an error. Maps service is one good example. 
* The upload service which will send the sha1 to google each time you install an apk can already been opt-out (under 'security'). I must admit that there is (currently?) no opt-out for other mechanism, but I'm sure they are working on it, since the services changing so much and fast.

**Comment by duud** [comment]
I dont't have any google apps installed.

Sorry for not providing the logs, just need to find some free time...

**Comment by CHEF-KOCH** [comment]
> I don't have any google apps installed.


If the main intent comes from the OS because it want to call the services it doesn't matter. But difficult to say what are the reasons for it, maybe an external app tries to call it too. Please provide more logs and monitor if the traffic will be higher if you start xyz app and report back.

**Comment by c3ph3us** [comment]
@CHEF-KOCH  with respect - dns spoofing arp spoofing dns poisoning etc ? how sure u are if connection is not secured - ssl ? etc ? no so any unsecure connection with no valid encryption protocol should be consider as not safe!

**Comment by c3ph3us** [comment]
@CHEF-KOCH  i have one request if u like coding wanna do more realiable for security app - add module which will build list of ip's when app tries establish a connection (for every app-uid ) to filter them white/black list and options to ask user if should allow connection to certain ip - then  filtering ports and protocols will not be necessary - that should be option for advanced users - consider this: app should connect to one ip or cannonical name (Depends) -but also is establishing connections to crashilics, analitycis , acra, adwords andsens etc .. which normally u  not aware .. then u can control yr privacy better - this is good firewall ! yr is based on protocol port  uid filtering - its too little to become a good protection app called firewall

yes i im aware of browsers - so ther should be a switch to allow all  network traffic of to filter trafic for app  uid

**Comment by CHEF-KOCH** [comment]
The mentioned attacks also affects 'secured' DNS stuff/software/channels too, e.g. the ip leakage problem under Windows 8 up to 10 due new 'network changes'. The entire I block xy IP and be secure is useless. one of the best examples I know is explained over [here](https://torrentfreak.com/anti-piracy-blocklists-dont-keep-bittorrent-spies-out-120904/). So I doubt that you can 'secure' the phone with such techniques. Imho we need better protocols for that. / But it's just another topic. 

> add module which will build list of ip's when app tries establish a connection (for every app-uid ) to filter them 

Google uses over 260.000+ IP's, loading them into the custom filters will slow down the machine, sure you could use the CIDR notation and the entire iprange (or ipset) but that won't change the fact if the app or services maybe use a separate tunnel which would need additional user interaction to really block or 'control' it. 

The logic behind to block single ip's is complex, for example block a bunch of ip's with custom script doesn't mean you not seen any ad's anymore (it could be cached offline) because the server is maybe hosted on cloudflare which also use a lot of ipranges or the app changed to implement other techniques that definitely can't controlled by AFWall+. 

Another problem is that the app/process spawns another separate process or init, the currently public iptables is very limited on this. 

But's getting now more off-topic.

**Comment by c3ph3us** [comment]
im devoloping web based aps so i know how  socked comunication is handled
in android / i proposed this as module for advanced user to give them more
control  over app activity
- for first -> user will be informed of app action is trying to establish
  connection -> let user decide to allow or not - if it is aware of
  consequences (its the same as now by uid u dont know which app is
  responsible for what action u can only guess :) -  that was in my case when
  i want to enable tether over usb :D what to enable or what to disable ? dns
  ? lan ? then i enabled all - AND THAT DID ALLOWED MY PHONE TO DO ANYTHING -
  u need more informed app for basic user & some options for advanced user (
  create basic profilesexample for certain types of activity ) - thats only
  my little advice to consider
- yr app is blocking acces on app level / but i wish to distinguish  what
  app is allowed to do or not
- see on any firewall -> simple mode (MALWARE PROTECTION) -> advanced mode
  ( FIREWALL) (learning mode, auto mode)

> "But's getting now more off-topic."
> if u want to develope aplication and move forward u need to go step ahead
> :)  port / protocol control -> then app filtering
> join forces with @EthACK - both have better chances to speed up :)
> i can also help if u want in some parts :D i like coding 

ps how this can be done:
- create a demon app (will start with system and live across reboots) 
- create a chain to iptables which will redirect all trafic thru app 
- app will show dialog: app xxx is trying to establish connection on port ... to ip/name 
  --> allow 
  --> block 
  --> auto (some rules)
- write provider to handle rules  (use cursor & sqlite to store /handle record)

2015-10-06 19:45 GMT+02:00 CHEF-KOCH notifications@github.com:

**Comment by CHEF-KOCH** [comment]
I think the only solution is to make an xposed module like LightningWall, because this would work Android independent and doesn't suffer from iptables related problems or complications.

Leaning mode isn't possible with iptables because there is no intent to capture real-time connection and Google doesn't provide any API for it, there is only the internet monitoring api for e.g. connectivity changes but that doesn't include VPN/LAN/Tethering.

**Comment by c3ph3us** [comment]
set one in & out chain & set acces to yr app ( reroute whole traffic thru one chain) ? and u filter the chain :D  do u know how read packet header ? 
basics -> iptables is a firewall itself - so u need redirect all trafic & filter it 
like any other firewalls are operating on network interace (hooking into it as a driver)

**Comment by E3V3A** [comment]
@CHEF-KOCH  I think your previous explanation [here](https://github.com/ukanth/afwall/issues/440#issuecomment-145898827) is extremely important for most users to know about. (And thank you for those details.) So perhaps it would be a good idea to put some of these items on the front page?

**Comment by CHEF-KOCH** [comment]
This thread is now out-off control, I think we need to close or hold on until we have information we can work with. The thread opener needs to verify first which ID/UID is causing this, I explained it already how to identify such processes over our wiki. Please remember that the wiki is the first place you should look at if there are some troubles. This really solve most of all problems (besides glitches or common bug-reports - thanks).

About my statement:
Thanks for feedback about 'special' iptables cases or VPN related tunnel ideas, I not want to add my posted statement into the readme or here in this wiki due the fact I'm still working on nftables/iptables and busybox solutions because as I always saud I think such problems must be fixed at the lowest levels. Since 1,5 weeks iptables now official supports Android 5 (but busybox still have some odd problems). I think before I not get any response on the iptables/nftables devs I simply can't say 100% it's unblockable, because custom scripts. Moreover I think that I just should [explain how to block special apps](https://github.com/ukanth/afwall/wiki/Google-Play-services-and-other-special-cases) and possible add the interface for it later directly in AFWall+.

If there is an ongoing discussion just open another thread to keep this here as much as possible clean. If I have more time I will bump an new iptables/busybox binary to AFWall+ (which also fix some race conditions we currently have, especially if you use a lot of -DROP and/or -REJECT based chains).

**Comment by duud** [comment]
Still have no time to debug this properly but here is some more information. UID of the process is 1000/setupwizard, I did a tcpdump and judging by the DNS request made before establishing the connection I think this connection is established in order to test whether the device has internet access. I think this is related to androids code part which shows an exclamation mark on the wifi-symbol if the device has no internet access.  As I mentioned above afwalls init script isn't executed properly on cm12.1 due to selinux restrictions, this seems to be the issue here

**Comment by CHEF-KOCH** [comment]
That's not correct anymore, because i was fixed with latest SU (speaking about chainfires SU policy file), see [here](https://github.com/ukanth/afwall/issues/442) fot the entire changelog. But that only confirms that people need the latest iptables binary (not included in any CM or other mod rom yet). But besides the startup script you can block gtalk (the service which runs inside 1000 to check connection - as you already correct pointed out). That needs to be changed in some config files but I don't see any argument to do this since other service would also need a heartbeat too. So that's why I'm asked for more details to really see which cause your problem/connection, if we are talking about only <1 MB data per week I think we can just drop the effort behind it. 

If you have time, feel free to post something over here to make a final decision how to handle this.

**Comment by duud** [comment]
Chainfires su is closed source, I don't want to install a closed source su binary, so I can't test this
