### ISSUE TITLE
Error applying firewall rules: click here to open settings.

### ISSUE THREAD

**Issue by tgharib** [ukanth/afwall#452]
I get the above error message on boot. I have to manually open up the app and select "Enable firewall"

I'm using a Nexus 5 with Android 6 installed.

**Comment by tgharib** [comment]
Hmm, this bug seems to have resolved itself. After about the 8th reboot or so, the firewall seems to be enabled on boot. I'll let you know if this bug comes back.

**Comment by tgharib** [comment]
Bug seems to have disappeared.

**Comment by CHEF-KOCH** [comment]
Is it only during fresh install? Some people reporting that after a fresh install this happens and diaper after some random reboots.

**Comment by tgharib** [comment]
Yes, now that you mention it, I installed it right after a fresh install but after 8 or so reboots, it was gone. I'm not sure if this is a bug that ukanth wants to fix so I'll just leave it open.

**Comment by ecanja** [comment]
This also happened to me after a fresh install, but not all of the time and kind of reproducable (EDIT: or maybe not, see EDIT below). It hasn't disappeared after some reboots (tried at least a dozen times).

For me, it's related to the issue of [being stuck at applying iptables rules](https://github.com/ukanth/afwall/issues/510#issuecomment-208381757) and only occurs after applying a (longer) script causing this hanging issue and then rebooting (see my comment on the other issue for more details). When choosing a shorter script, which applies without difficulties, I don't get this error message after a reboot.

To me, the issue expresses as follows:
1. I apply a script causing issue #510. I need to kill AFWall or do some strange procedure described in the other comment afterwards.
2. After a reboot, I get **three** notifications:
- The notification mentioned in the title.
- The usual notification saying "Firewall is running"
- A popup "Iptables unsupported" telling me that my Android kernel "is missing required iptables/netfilter modules".

However, the third one does not really make sense to me, as with the shorter script, everything works fine. Due to the symptoms, I'm not sure, if the cause of the issue is the same for @tgharib and me.

By the way, here is the logcat after rebooting:

```
======
Logcat
======

14:56:21 Now assuming NO connection (all interfaces down)
14:56:21 Exception : java.util.NoSuchElementException
14:56:21 Starting root shell...
14:56:21 [libsuperuser] [SU%] START
14:56:21 Starting /data/data/dev.ukanth.ufirewall/app_bin/klogripper 
14:56:21 [libsuperuser] [SU%] START
14:56:22 Root shell is open
14:56:22 logservice shell started
14:56:28 [libsuperuser] [SU%] WATCHDOG_EXIT
14:56:28 Exception : java.util.NoSuchElementException
14:56:28 libsuperuser error -1 on command '. /data/afwall_scripts/iptables.sh'
14:56:28 Exception : java.util.NoSuchElementException
15:01:47 Starting root shell...
15:01:47 [libsuperuser] [SU%] START
15:01:47 Root shell is open
```

EDIT: Today, the issue also happened to me after choosing a script that worked yesterday. Moreover, in this case, the popup after applying the script disappeared after some seconds, so there was no hanging. But nevertheless, I got the error message after reboot (though the iptables-kernel-popup was also missing). After clearing cache and data of AFWall, it worked again.
So now I don't see any pattern anymore and it seems to be rather random.

**Comment by Beast141** [comment]
This happens to me too (with latest version afwall), after phone reboot! only after random reboots, and im not using any script.
it gets stuck and then i have to disable and re-enable firewall rules, otherwise my internet doesnt work.
