### ISSUE TITLE
IPv6 support is not adequate

### ISSUE THREAD

**Issue by vi** [ukanth/afwall#461]
Using F-Droid's version 2.1.1

If "IPv6 support" checkbox is checked,
- Policy of OUTPUT chain gets changed from ACCEPT to DROP without any accompanying "ACCEPT" rules;
- AWwall's "awwall" chain is empty in ip6tables
- "Enable Firewall" don't change to "Disable Firewall" whan I click it.
- No error messages are shown
- Maybe IPv4 support gets mangled along the way.

And a nitpick:
- "IPv6 support" checkbox is in "User interface" page, yet does not affect user interface in any way.

Related to #347?

**Comment by CHEF-KOCH** [comment]
IPv6 is bugged and already known.

#251
#281
#329 (especially see my last comment here).

Thanks.

**Comment by vi** [comment]
1. What is the problem doing all the same as in IPv4 case, but with `ip6tables` instead of `iptables`?
2. Why is it not marked as incomplete in UI? It's not even "experimental".

Is AFWall project in general evolving or semi-abandonware? Are there alternatives? The attitute towards errors doesn't look like appropriate one for a security project.

**Comment by CHEF-KOCH** [comment]
The [problem with ip6tables](https://android.googlesource.com/platform/external/iptables/) is that no one cares about it on Android, the branch is far behind the original iptables and there are only 2/3 people which maintain it. It's not only the name we are talking about, we talking about [major problems](https://github.com/ukanth/afwall/wiki/CustomScripts#important-notes-about-ipv4-and-ipv6-differences).  It's not marked as experimental or such because no one reported it yet, except me several times. 

If you're unhappy with AFWall+ you can use an [alternative](https://github.com/ukanth/afwall/wiki/Similar-Firewall-solutions) but I promise there is only AFWall+/Avast or LightningWall which are proper working. But in fact all of them having problems with ip6tables in some situations, because this needs to be fixed directly in ip6tables so that we can merge this.

As I also wrote, maybe the only solution in the future is to handle such stuff with XPosed framwork, since this would work ROM independently and we would not suffer anymore from the fragmentation problem.

**Comment by vi** [comment]
So shall I expect that installation of third-party ip6tables binary should resolve the problem?

I see options for "IPTables Binary":
- Auto
- System iptables
- Built-In iptables

Where to specify the path?

In any case AFWall should show error message when something isn't applied.

**Comment by vi** [comment]
> The problem with ip6tables is that no one cares about it on Android

Does it approximately translate to "nobody really cares about IPv6 in Android"?

**Comment by CHEF-KOCH** [comment]
I only can wrote about my experience, yes, no one cares about it. It starts with the myth on the entire internet to 'disable IPv6' which is horrible wrong.

**Comment by vi** [comment]
At least this script (it tries to copy IPv4 rules to IPv6) finished almost successfully on me device:

``` sh
IFS="
"
A=(`iptables -S | grep afwall`)
for i in ${A[@]}; do eval "ip6tables $i"; done
```

I see the usual list of rules with RETURN per `owner UID match`. The only errors were:

```
ip6tables: Protocol wrong type for socket.
ip6tables v1.4.11.1: unknown reject type "icmp-port-unreachable"
Try `ip6tables -h' or 'ip6tables --help' for more information.
ip6tables v1.4.11.1: unknown reject type "icmp-port-unreachable"
Try `ip6tables -h' or 'ip6tables --help' for more information.
```

Maybe I can hack up IPv6 support this way (after fixing `afwall-reject` chain).

**Comment by CHEF-KOCH** [comment]
Nah, this won't work. 

There a several cases you're script/replacement can't work, especially if it comes to ICMP because Ipv6 hardly needs ICMP compared to IPv4. And not letting ICMP packets in can severely cripple your traffic because you won't receive error messages related to that traffic. Mostly this ends up with timeouts and/or huge delays.

**Comment by vi** [comment]
What's wrong with just allowing all incoming/outgoing ICMP, both for IPv4 and for IPv6 (unless other rule like `-m owner` also applies)?

The main thing is to prevent arbitrary applications from phoning home / downloading ads. Getting those UIDs is Android-specific and is the primary reason to use AFWall instead of just hacking up all rules manually.

[offtopic] Can apps blocked in AFWall resolve DNS? If yes, can them use DNS tunneling to defeat AFWall?
