### ISSUE TITLE
request - add possibility to set "table & proxy traffic"

### ISSUE THREAD

**Issue by c3ph3us** [ukanth/afwall#462]
add possibility to set proxy & possibility to select this proxy for app to use it or bypass :)

**Comment by CHEF-KOCH** [comment]
Nope, this can be already done with integrated mechanism or with other proxy software which working great. AFWall+ can't interference in system related API's which will be used here for this like VPNAPI/[Proxy](https://developer.android.com/reference/android/net/Proxy.html). 

I suggest you use [ProxyDroid](https://play.google.com/store/apps/details?id=org.proxydroid) or another one which getting regular updates and are well design for certain 'special' cases. Because if we implement such things I exactly know that people getting configuration problems with it or asking for 'more'. 

AFWall+ is as mentioned several times and on the Wiki, not an AV/adblocking tool or 'all-in-one' security solution and never will be.

**Comment by c3ph3us** [comment]
proxy Droid as I said here already is not working with afwall

**Comment by c3ph3us** [comment]
same with USB tethering not working I have enabled all  while afwall enabled  -  access to root aps,   adb,  kernel and dhcp  

AppID : -11
Nazwa aplikacji:  
Ilość zablokowanych pakietów:    11
[UDP]66.28.0.45:53(5)
[UDP]212.113.0.3:53(6)

```
---------
```

**Comment by c3ph3us** [comment]
windows nslookup  says  query  refused

**Comment by c3ph3us** [comment]
![screenshot_20151210-101418](https://cloud.githubusercontent.com/assets/10565704/11722566/d62a2e22-9f69-11e5-8b33-926b1c29980e.png)

![screenshot_20151210-101432](https://cloud.githubusercontent.com/assets/10565704/11722578/e3b98f2e-9f69-11e5-87c1-2830dc2d3071.png)

**Comment by CHEF-KOCH** [comment]
Sorry but such information not helps, we need dmesg and other logs but not something within AFWall+ since this only shows the symptomes.
