### ISSUE TITLE
Afwall+ not working on dependably on marshmallow with different root method

### ISSUE THREAD

**Issue by mddvul22** [ukanth/afwall#465]
I've got a nexus 6 running omnirom 6.0.1 that was rooted differently than Chainfire's method.  I'm using an opensource root method, detailed here: http://forum.xda-developers.com/nexus-6/general/root-t3231211

Afwall+ installs correctly.  I'm able to enable/disable firewall rules, and things work for a while.  However, after some time passes, things start to malfunction.  For example, apps that are allowed wifi access can no longer access the internet.  If I disable Afwall+ and then reenable it, the app's internet access starts working again.  This is happening with multiple apps.

I'm not sure if this is an Afwall+ issue, or a marshmallow issue, or something related to the root method I've used (but my other apps that require root are working fine).

Please let me know if I can offer any assistance.
Thanks.

**Comment by CHEF-KOCH** [comment]
I not tested the new 6.0.1 release but the 'old' 6.x worked well (chainfires solution used). 

We would need some debug logs like dmesg, su loggs and others to identificate the real problem. As soon as I get my hands on the new Android release I will re-test with your mentioned rooting solution. Your reported problems sounds like we have a problem to re-apply/refreh the iptables which is maybe busybox/su related but it's speculation.

**Comment by ukanth** [comment]
Can you send error report(under firewall rules) or iptables log when your applications starts behaving differently?  

I observed this behavior even in Lollipop 5.1.1.

**Comment by mddvul22** [comment]
Just emailed the error report, iptables.log, and description/reference to this ticket.  (Please disregard the first error report, sent approximately an hour earlier, where I neglected to attach the iptables.log and also neglected to reference this ticket.

**Comment by ukanth** [comment]
Looks like busybox needs to be updated (built-in). @78c59635bdd8 , please install busybox installer and change the settings within afwall ?

Also please disable log service and observe the behavior.

Are you using restrict background service for any apps ?

**Comment by chrsigg** [comment]
To add another data point: I have the same or a similar issue with a Nexus 5, running stock 6.0.1 and rooted using SuperSU v2.61. AFWall works well initially, but after some time connections are becoming blocked even though they have the proper permissions set in the GUI. Disabling and re-enabling the firewall temporarily fixes the problem, until it happens again.

**Comment by CHEF-KOCH** [comment]
BusyBox isn't ready for 6.0.1 yet.

**Comment by AlexanderOMara** [comment]
I'm also noticing this issue. I'm not sure as I haven't observed it long enough, but it might be related to switching networks? Any updates on this issue?

**Comment by ikelos** [comment]
I suspect it's due to doze mode, and afwall+ being asleep when the network changes (so that when it's woken up, it doesn't spot the change in time and so doesn't update).  I seem to have had a much better time (although still need to wait a little bit after a network change) once I disabled battery optimizations on afwall+.  This can be altered under Settings > Battery [Menu] Battery Optimization > All Apps > Afwall+ > Don't optimize.

I'm not entirely sure why the rules need changing in between every network state change.  It looks as though the rules are all specific to the medium they're using (wifi, mobile, roaming, etc), so perhaps this could be improved?  It was also interesting to see that marshmallow appears to have its own [firewall manager](https://android.googlesource.com/platform/system/netd/+/c8683d7eb9bb95de2090431e8daaa45d92b45e38/server/FirewallController.cpp) (but luckily the two seem to be able to coexist peacefully)..

**Comment by AlexanderOMara** [comment]
If it helps, on my end it seems I have to first disable rules, close the app, re-open the app, then enable rules to make it work again. Just disabling then re-enabling does not seem to work.

**Comment by chrsigg** [comment]
Yes, but for me this is only a temporary fix.

Are there still things that need to be done for 6.0.1 support? I understand that this is a volunteer effort and the devs are of course free to work according to their own schedule.

But with the recent serious vulnerabilities and Google's monthly patch schedule, running the latest release is a must IMO.

On Jan 29, 2016 11:26 PM, AlexanderOMara notifications@github.com wrote:

If it helps, on my end it seems I have to first disable rules, close the app, re-open the app, then enable rules to make it work again.

**Comment by ikelos** [comment]
Please could you try disabling battery optimizations for afwall+ and seeing if that helps?

**Comment by CHEF-KOCH** [comment]
With M a lot of things changed, busybox is not available a lot of other things was fixed and so .... So, generally the app works, but the binaries and the execution of several aspects are known to be broken such as the init.d problem and the network manager in general since it was almost re-written from the scratch. 

At time of writing I highly suggest that if you use your phone daily not use AFWall+ yet and switch to NetGuard because this works _better_ on M and is a newer and directly work with the VPN API (while AFWall+ not respect that) [yet?].

The battery optimization or any other settings that directly affects the gov. of M isn't in anything involved in AFWall+, the M thing needs to be fixed within AFwall+ and not on M or it's settings. So again don't use it yet!

**Comment by ikelos** [comment]
It's not quite clear what you mean by "busybox is not available".  Using busybox from stericson's busybox installer appears to work just fine?

NetGuard has a lot of plus points but prevents use of an actual VPN whilst it's blocking apps.

The battery optimization **of the afwall+ app** absolutely is involved in afwall+ (not just the gov. of M).  The [FAQ for NetGuard](https://github.com/M66B/NetGuard/blob/master/FAQ.md) (point 21) even tells you to do the same thing (which is what made me try it for afwall+).  The thought is that broadcast receivers may be inhibited in doze mode (such as the [connectivity change receiver](https://github.com/ukanth/afwall/blob/beta/aFWall/src/main/java/dev/ukanth/ufirewall/broadcast/ConnectivityChangeReceiver.java) that afwall+ uses in "Active Rules" mode).

Having set battery optimization mode to off **for afwall+ specifically** I've found that a few seconds after joining a WiFi network, the firewall service has been restarted, a toast appears letting me know that the change in network occurred and my appropriate rules appear to be applied.  It's entirely possible this is just masking the issue (by having afwall+ carry out a complete service restart), rather than actually fixing it, but in order to get any more information we need people to test it and report back a) whether it worked and b) if there were any changes/consequences from doing so.

**Comment by CHEF-KOCH** [comment]
Yes, the latest version is fixed but all other binaries are not and of not our integrated ones. But even if you install the latest binary it suffers from several things I already mentioned in other threads.

About doze mode, nope, it has no effect since AFWall+ not respect this or was designed to handle it because the Main activity runs all the time and if M want's to kill it because the gov. want it to reduce battery it's not AFwall+ related because in this time iptables not change in any aspect and not even if you activated the monitoring rules option, because this is the bug currently. The documentation you linked also say 'not sure', but as explained it not affects AFWall+ yet.

Yes the service and other restarting this isn't an issue it's how the gov. wants it that's also related to system app question because the system ones are excluded from this behavior. 

Again that needs to be fixed within AFWall+ and not by changing any option in Android because this should be done automatically, and again that is e.g. possible by flag the activitiy or change it to system app.

**Comment by CHEF-KOCH** [comment]
Maybe we just whitelist it via [REQUEST_IGNORE_BATTERY_OPTIMIZATIONS](https://developer.android.com/reference/android/Manifest.permission.html#REQUEST_IGNORE_BATTERY_OPTIMIZATIONS) permission but imho it's not an good option because in the case someone not want to enable the monitoring option in AFWall then this would be _bad_, my suggestion is to remove the monitoring option within AFW (and enable it by default) and add this permission because a firewall must be run all the time and of course the monitoring option is essential in case network mode changed, but I do agree on Wifi/VPN (as I already said) we may add a whitelist to not monitor the status to safe a little bit energy by ignoring it's state.

**Comment by chrsigg** [comment]
I deactivated battery optimisation and will see if it has a positive effect.

**Comment by AlexanderOMara** [comment]
Just wanted to report back, I haven't had the issue since disabling battery optimizations back when it was suggested above.

**Comment by chrsigg** [comment]
Same here. Thanks for the suggestion.

On Feb 18, 2016 8:23 AM, AlexanderOMara notifications@github.com wrote:

Just wanted to report back, I haven't had the issue since disabling battery optimizations back when it was suggested above.

**Comment by AlexanderOMara** [comment]
With the latest updates, I have disabled the setting to disable battery optimizations, and have not experienced the issue again since. I believe this issue is resolved.
