### ISSUE TITLE
Distributing AFWall+ on TorrApk AppStore

### ISSUE THREAD

**Issue by gianzalone77** [ukanth/afwall#469]
Hoping to give a contribution to this app that I really love,
I put it on TorrApk, an alternative free Android AppStore that distributes free apps all over the world, in their .apk file format and can reach a lot of devices that have no access to Google Play.

This is the link of the app: https://www.torrapk.com/en/apps/30-rooted-phones/8187-AFWall-Android-Firewall

I'll try to keep it always updated with the latest release.

**Comment by CHEF-KOCH** [comment]
Thanks, also added to our wiki with an small hint that this is unofficial. :+1:

**Comment by gianzalone77** [comment]
Hi CHEF-KOCH,
Thank you. I saw ukanth reverted your modification to wiki. Anyway I'll maintain AFWall+ updated on TorrApk. :+1:

**Comment by CHEF-KOCH** [comment]
Hey, 
I think he reverted my change because it's unofficial (aka unknown sources) and not maintained by him. Maybe an option would be that you give (if possible) him your account or you remove the app and he create the afwall repo on torrapk yourself. 

Btw maybe you can also can check apkmirror.com and upload it there too. I usually download WebView and GMS from there and it's a _trusted_ platform. 

THX

**Comment by gianzalone77** [comment]
Hi,
of course I'm glad to give him the full management of the account. Thank you for the suggestion.
I can assure TorrApk too is a trusted platform (I'm working on it since many year), anyway I'll try to contact ukanth.
Thank you again.
