### ISSUE TITLE
Question: how is chromecast penetrating my afwall?

### ISSUE THREAD

**Issue by 5TDg9** [ukanth/afwall#470]
I just installed google's chromecast app. Although i didn't allow the app to communicate with wLan, when i start the app my chromecast stick found. So there must be another open communication level  the android system, maybe through kernel?

**Comment by CHEF-KOCH** [comment]
DNS.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH If you have a moment, can you explain how chromecast is just using DNS to accomplish the functionality described by @5TDg9?

**Comment by CHEF-KOCH** [comment]
Uargh, I not use this but according to [Wiipedia](https://en.wikipedia.org/wiki/Chromecast) it uses mDNS (see also #326) and on older versions the [DIAL](https://en.wikipedia.org/wiki/Discovery_and_Launch) protocols. Both of them are not (yet) respected by AFWall+.

The detection is done by ssdp/http(dns) or upnp which sends a small range of bytes to determinate the status. The problem is that this is system wide open by default to get the best possible streaming quality for YouTube/Chromecast.

**Comment by Atavic** [comment]
CHEF-KOCH has left.

**Comment by Gitoffthelawn** [comment]
@Atavic Where did he go?

**Comment by Atavic** [comment]
There's some users with the same name in forums around. Point here is that he had a lot of material in repos. I have some backup.

**Comment by Atavic** [comment]
Back in business.
