### ISSUE TITLE
afwall+ is being disabled after sometime when screen is off

### ISSUE THREAD

**Issue by alphajoza** [ukanth/afwall#474]
afwall+ version: 2.1.3
android: v4.2.2 (rooted+exposed installed)

My need: every app should have access to the internet while connected to the wifi and none when using mobile data except: Whatsapp and Google Play services(for gcm functionality)

my settings:
  Mode: White list
  'Core' section: all entries are checked to use wifi
  'System' section: only Google Play services set to use mobile data
  'User' section: only Whatsapp set to use mobile data

afwall+ is working just as I expected but if I turn off wifi and switch to mobile data, everything is again as expected but after sometime, when the screen is off, I don't know what happens that when I turn screen on again to use the phone, I can see that afwall+ is not working. (an app like firefox can access internet) (no notification or anything from afwall+)

I have greenify too but afwall+ is not set to be greenified.

**Comment by CHEF-KOCH** [comment]
Can you enable administrator option within AFwall+ and see what happens?

**Comment by alphajoza** [comment]
I did that but it's still the same

**Comment by CHEF-KOCH** [comment]
Thanks for the quick feedback. 

In a normal environment Android only 'kills' something if it runs out of memory.

To better understand zhis issue, you mean the mainactivity is killed or even the background service(s)? Could you check via an taskmanager and 'recent' panel if it's still running [without any GUI]? I'm asking because this sounds that the ROM or an external third-party app want to 'kill' the service to 'safe battery [which is a myth btw]. The strange part is that you say that the rules getting changed to re-allow xyz app/traffic, and this is what I not get even if it's killed an iptables not changed it should be stay blocked.

Sr, but we need more information on this, I currently have no 4.2.2 to test. My my opinion is that maybe the advanced options that are provided by greenify (the aggressive option?) is causing this. In this case we not change our app behavior because this is then coming directly from greenify and must be fixed or mentioned in the greenify thread. Please re-check all the options (not only which app is greenified).

**Comment by ukanth** [comment]
If you use MIUI, try the following method http://xiaomininja.com/2015/08/10/miui-tip-enable-autostart-to-never-miss-a-notification-again/

Otherwise we can't fix this issue
