### ISSUE TITLE
Question: "No data connection" message

### ISSUE THREAD

**Issue by TKLCZ** [ukanth/afwall#487]
Hello,

at first I need to say Thank You for the great firewall app. 
I used the Droidwall but there was many of issues which are solved in your app.
So I bought the paid version of AFW+ after trying of the free version and I've donated something too because the app price is low by my opinion.

But I have one problem with Android's internet connection checker which I'm not able to solve myself.
If I have whitelisted only the apps for which I can allow the internet access (and necessary services like a Google play for example), I get the "No data connection" message in message bar at times.
I have already read the light FAQ in app and the full FAQ on your Github pages too, I spend many of time by googling, but I still cannot find the solution.
Yes, I know that if the processes under UID 1000 will be allowed the issue will gone.
But there is too many services under this UID (and many of this is bloatware or spyware by my opinion) so I don't want allow all at once.

So I have the question to you if there is any other solution of this problem - or if I can write my own rule which will allow only the one right process for the internet connection checking.
Or (workaround) - how to suppress the message. I'm not able to do it by standard way.

Thank you 

Xiaomi Redmi 2 2GB RAM, Android 4.4.4, MIUI 5.12.31

**Comment by CHEF-KOCH** [comment]
There is no bloat-/spyware under UID 1000 and never will be, if there would then someone had already revealed it but there is noting but just false rumors and wrong information. UID 1000/0 is important to Android and should never be blocked by beginners (maybe we change that in the future because I will not again explain it and just link in gms/kernel thread [if it's done]).

Just unblock all systems related things and there will be no problem. This message can't be bypassed because it's there to inform that something important is blocked and we not want/can change that.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH When you mention UID 1000/0, do you mean all UIDs in the range of 1000-1999, or do you mean exactly UID 1000?

**Comment by CHEF-KOCH** [comment]
Exactly [1000](https://android.googlesource.com/platform/system/core/+/master/include/private/android_filesystem_config.h). 

In the range between there are others too of course that shouldn't been blocked but I'm working on it to figure out which are necessary and which not, my personally goal would be to get an option to mark/separate each UID so that power users (for e.g. debug/other reason) may get the ability to allow/deny them.

UID 1000 (aka AID_SYSTEM) is _similar_ to Windows svchost.exe you need them because it can control some network related things that are necessary (in our case the system server) requests for e.g. [Device Monitor](https://developer.android.com/tools/help/monitor.html) and other sub-systems. 

And here are the other important UID's
* AID_RADIO         1001  /* telephony subsystem, RIL */
* AID_BLUETOOTH     1002  /* bluetooth subsystem */
* AID_COMPASS       1008  /* compass device */
* AID_WIFI          1010  /* wifi subsystem */
* AID_ADB           1011  /* android debug bridge (adbd) */
* AID_DHCP          1014  /* dhcp client */
* AID_VPN           1016  /* vpn system */
* AID_KEYSTORE      1017  /* keystore subsystem */
* AID_DRM           1019  /* DRM server */
* AID_MDNSR         1020  /* MulticastDNSResponder (service discovery) */
* AID_GPS           1021  /* GPS daemon */
* AID_DRMRPC        1026  /* group for drm rpc */
* AID_MEDIA_DRM     1031  /* MediaDrm plugins */
* AID_LOGD          1036  /* log daemon */ (**optional**)
* AID_AUDIOSERVER   1041  /* audioserver process */ (**optional**)
* webservd  & metricsd 1044 + 1043 (but needs confirmation)

// only for socket
* AID_NET_BT_ADMIN  3001  /* bluetooth: create any socket */
*  AID_NET_BT        3002  /* bluetooth: create sco, rfcomm or l2cap sockets */
* AID_INET          3003  /* can create AF_INET and AF_INET6 sockets */
* AID_NET_RAW       3004  /* can create raw INET sockets */
* AID_NET_ADMIN     3005  /* can configure interfaces and routing tables. */

The rest incl. 100000 can be blocked.

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH That's a fantastic list. Thanks!

Does UID 1000 need to be whitelisted for LAN too?  Or just for data connections?

**Comment by CHEF-KOCH** [comment]
I think we can close it because it isn't AFWall+ problem, similar to the root # su indicator which was introduced in recent Android/CM versions.

As I already did said in the past and so many times, we not add for every Android OS _gimmick_ workarounds, there are reasons, security or whatever and to bypass this is not an good option. If you have root (as we have) there are ways to do that (if you really want and understand the possible in-complications) like xposed and other methods which then works on all systems and the next not need to whine that it not works on system xyz not anymore.


I will update the wiki the next days with the UID thing if I get my table ready to publish with which UID's to block and which are possible problematic. 

Thanks for understanding this. We can close it.

**Comment by mountbraindevnull** [comment]
@CHEF-KOCH 
Well. I do understand your point of view.

BUT.

As you already stated out you do want to stick to the Google rules. That's alright for me. To some extend.

BUT.

As a user/buyer of AFW+ I do not want the coder to think about what the common user wants and furthermore what is secure for the user. Neither do I want the coder to think about Google's rules because they change all the time - nor do I want the coder to rely upon others to reveal possible security issues. What I want is what is best for the user's privacy.

Up to the time I'm writing this Google's OS is - to some extend - pretty much open. Google's rules will change in the near future and will make much more privacy options unavailable.

Thinking of KK I do not remember to ever had that kind of problem.

I'm sorry but I do not accept your kind of argues. And I'm sorry I have to rely on others to decide for me what's good and what's not.

Always relied on AFW+. I guess, I have to think it over.

Bye.

**Comment by ukanth** [comment]
alternative to allowing 1000 is simply running a terminal command once after a fresh install:

`su -c "settings put global captive_portal_detection_enabled 0"`

**Comment by someone-somenet-org** [comment]
close as invalid. This is by Android design.
If you want to block core OS features, expect the OS to misbehave. If you dont want the OS to misbehave dont block core OS features. If you want to block Android core OS features live with it misbehaving. Easy as that.

**Comment by someone-somenet-org** [comment]
#441 And this one too.
