### ISSUE TITLE
Feature Request: Real Multiuser-Support

### ISSUE THREAD

**Issue by frank-w** [ukanth/afwall#500]
currently Profiles exist but they are not linked to accounts

i have multiuser activated in android, but if i use the new user, everything seems to be blocked...in the main-account the apps are allowed (e.g. firefox, playstore,etc.), apps are shared using the app "multiuser-app-share" from googleplay.
nothing found related in log file of AFWall+ (main-user)

my current workaround is to set FW-Settings again for the new user (shared AFWall and supersu-app and activated multiuser-option in SuperSu) but i don't want root-access by all other accounts

**Comment by CHEF-KOCH** [comment]
[Multi-User is an dead system](https://www.reddit.com/r/Android/comments/1j0lo5/official_android_43_questions_and_answers_thread/cb9wu70). 

I not think we need to support it, since a) only one user can use the device at the same time b) I not get why someone use different apps with different rules on a different profile, it's dangerous to hand someone over your device with different apps which may allow to bypass xyz.

**Comment by frank-w** [comment]
I mean not different rules, currently all traffic ist blocked under different user. App schould enumerate all ids for all users so only one maintaining user is needed

**Comment by CHEF-KOCH** [comment]
Sorry I not understand what you mean. If you have >1 users and you're login into the daily account all other accounts should not be communicate with internet, or do you have this issue? Because this was long time ago implemented that only the current user get internet access, otherwise this would be a security hole.

**Comment by frank-w** [comment]
The main Account can be configured normally. All other Accounts does not have any net-access. I can not change this except i share the app and root.
The securest Option should be configuring all accounts from the main-account so i do not have to share app and root to the second Account.

**Comment by gerroon** [comment]
@CHEF-KOCH 

I do not think that you are understanding what he is saying. He is not trying to run 2 usersat the same time. He just needs his second user to be able to connect to the internet when he switches to that account (which is the issue I myself have)

**Comment by ukanth** [comment]
Duplicate of #271
