### ISSUE TITLE
[FAQ] System Applications to Block/Allow

### ISSUE THREAD

**Issue by Gitoffthelawn** [ukanth/afwall#518]
It will be useful to create a FAQ documenting which Android system applications must be allowed, and which can be blocked.  For each Android system application, any side-effects of blocking the application will be notated.

I'll get the ball rolling, and then others can make corrections and add to this.  Together, we can work towards an accurate document.
## **_Common System Apps**_

**(adb) - Android Debug Bridge**
- If blocked, ADB will not be able to communicate over the 
- Rec: Block if not using ADB over a wireless connection, otherwise enable only for connection type being used

**(drm) - Digital Rights Management service**
- If blocked, cannot view content that requires Android DRM
- Rec: Block if not viewing any content that requires Android DRM content, otherwise allow for connection type(s) being used

**(gps) - GPS**
- If blocked, GPS may not be able to receive AGPS data (needs to be verified)
- Rec: Research if AGPS data can still be obtained if blocked; if so, block

**(Kernel) - Linux Kernel**
- Cases where it needs to be enabled for all connection types (LAN, WiFi, Cell data)
- Rec: Allow for all connection types (including LAN)

**(media) - Media server**
- Need more info
- Rec: Until more info provided, allow for connection types except LAN

**(NTP) - Internet time servers**
- Cell network devices can still obtain current time/date from cell network even if this is blocked
- Rec: Block for cell devices, Allow for connection types except LAN for other devices

**(shell) - Linux shell**
- Cases where it needs to be enabled for connection types except LAN (WiFi, Cell data)
- Rec: Allow for connection types except LAN

**(Tethering) - DHCP+DNS services**
- If blocked, will not be able to tether over the connection types blocked
- Rec: Block if not tethering, otherwise enable only for connection types being used for tethering

**(vpn) - VPN Networking**
- If blocked, will not be able to use a VPN over the connection types blocked
- Rec: Block if not using a VPN, otherwise enable only for connection types being used to connect to the VPN

**ConfigUpdater**
- Function unclear
- Rec: Allow for WiFi, block for other connection types

**Downloads, Media Storage, Download Manager**
- Required to for apps to download content
- Rec: Allow for connection types except LAN

**DRM Service**
- If blocked, cannot view content that requires DRM
- Rec: Block if not viewing any DRM content, otherwise allow for connection type(s) being used

**GoogleAccount Manager, Google Play services, et al.**
- If blocked, cannot use Google apps
- Rec: Block if not using Google apps, otherwise allow for all connection types except LAN

**Google Partner Setup**
- No one seems to know what this does and what data it transmits/receives
- Rec: Block

**Google Play Store**
- If blocked, cannot use the Google Play store
- Rec: Block if not using the Google Play store, otherwise allow for all connection types except LAN

**Market Feedback Agent**
- If blocked, cannot use Google to submit feedback to app developers when apps crash
- Rec: Block if not using the Google Play store, otherwise allow for all connection types except LAN

**PacProcessor**
- Unclear what this does and what data it transmits/receives
- Rec: Block

**ProxyHandler**
- Function not completely clear
- Rec: Allow for all connection types except WiFi; might be good to block if not using any proxies

**Self Service**
- Unclear what this does and what data it transmits/receives
- Rec: Block

**Setup Wizard**
- Unclear what data this transmits/receives
- Rec: Block

**Smart Device Manager**
- Unclear exactly what this data this transmits/receives, but may be required for some tracking tools (finding lost device, for example)
- Rec: Block, unless determined that it is needed for any lost device finding tools

**Comment by ukanth** [comment]
Like the idea. You could edit the wiki and update yourself. 

+1 @CHEF-KOCH

**Comment by Gitoffthelawn** [comment]
@ukanth Sounds good.  Thanks.  I didn't want to edit the wiki without your consent.

I believe it is best to use this thread (issue) to get some of the details worked out and errors fixed.  After the information is a bit more solid, I'll add it all to the wiki.

Thanks again for AFWall+

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Do you have any corrections, changes, or additions to the above list?

**Comment by CHEF-KOCH** [comment]
Uargh, sorry guys I will merge/add this next week into the wiki. Over eastern I had not really the time/motivation, was on Revision 2016 party. 

We need more supporters like you, thanks!  :+1:

**Comment by CHEF-KOCH** [comment]
I'm not really happy with the current look, any suggestions? I added into the todo that we might switch to table view, anything speaks against this? (I'm not a mobile user ... just saying).

**Comment by Gitoffthelawn** [comment]
@CHEF-KOCH Are you referring to the current look of the wiki?

**Comment by haarp** [comment]
uid 1000 (Android System, others) - unblock all. Blocking this causes the dreaded exclamation mark (indicating "no internet") next to the Wifi/Radio icon.

edit: Turns out I can edit the Wiki. Added it myself!

**Comment by an0n981** [comment]
@haarp an alternative to allowing 1000 is simply running a terminal command once after a fresh install:

su -c "settings put global captive_portal_detection_enabled 0"

**Comment by CHEF-KOCH** [comment]
Read also [here](https://android.stackexchange.com/questions/100657/how-to-disable-captive-portal-detection-how-to-remove-exclamation-mark-on-wi-fi).

I will look that I can update the list soon, since a lot have changed.

**Comment by someone-somenet-org** [comment]
Most of your recommendations are wrong for me/my device.
As the first rule of security is: Block anything except stuff you need/want.
There should be no general list of what to allow, just a list of what does what.

**Comment by Gitoffthelawn** [comment]
> Most of your recommendations are wrong for me/my device.

@somenet If you would like to make a contribution, please do so.  Criticism of other people's contributions, without providing contributions of your own, is not very helpful.  Thanks for your understanding.

**Comment by ghost** [comment]
I also don't have any connection problems with blocking everything, but I have scripts for custom DNS server and to route traffic trough Orbot for apps that need access to internet. I've been using it like this for much more than a year.

I don't use a bunch of apps, I only use a few that I really need, don't have any google app but maps, so yes, maybe there's cases where you need to allow system applications.

**Comment by cjsin** [comment]
On my device I have two Setup Wizard apps with different user ids. One looks like a basic app. The other one has user id 1000 and seems combined with Android System, Settings, and more, and also a com.Qualcomm.timeservice

I've observed one of the two ( most likely the one with ID 1000 if I remember correctly) to be used for the Google "walled garden check".
It does something like try to make a http connection to a site something like 'connectivitycheck.google.com' and if it is blocked on your wifi for example then the system will choose to continue to try to send data over your 3g/4g data connection instead of the WiFi. 

I also observed it attempting to use port 123 which is NTP network time protocol, presumably from the com.qualcomm.timeservice service.

This is on cyanogen not stock android though.

If you have a web server and DNS server on your home WiFi you can fix the connectivity check issue when you're there at least, Google generate_204 for instructions

**Comment by breversa** [comment]
Any idea about "Intent filter verification service", found on LineageOS 14.1/Android 7.1 ?

**Comment by CHEF-KOCH** [comment]
You'll find this in every OS. An [intent filter](http://developer.android.com/reference/android/content/IntentFilter.html) lets the system know what data or service requests a component can handle. A component might be an activity, service or a broadcast receiver.

If you are writing e.g. an image viewer, you would add an intent filter (or several) to the manifest describing the images you can handle. If you are writing a file browser, you might package up the details of an image file in an intent, and the system would sift through intent filters until it found the best match to handle that image. The same goes for any type of data or service that might be passed from one component to the next.

That said it should not be blocked. 

--------

> I also observed it attempting to use port 123 which is NTP network time protocol, presumably from the com.qualcomm.timeservice service.

About NTP, it should never be blocked, no matter which OS (if Android, Linux or Mac just don't do it) because the certification system among other systems are depending on a correct time. The only recommendation I can give here is to set your NTP to the one which your router can provide. Some routers have an option for this, so the router gets the time from your ISP (or whatever you put in there) and then you can manually set it into your OS (on Android you only can do this via some bash command) This means the OS gets the time locally within your own network while the router gets it from outside the network. This method bypasses any possible attack scenario on the NTP protocol as long as your router isn't attackable, however if your router is weak then any OS own mechanism is pointless anyway. So a good router is still the only way to protect your network (not the OS). Anothe example, some routers have options to filter Teredo, NetBios etc traffic so no matter if your OS is weak against possible attacks on these protocols the router still guards the entrance door. That said, even if the router is the most important thing, on a mobile OS this drastically changes because you might login into a McDonalds network which has a weak security system (router) and in this case some OS mechanism definitly matter.

--------

> connectivitycheck.google.com

This technology is called "[Captive portal](https://en.wikipedia.org/wiki/Captive_portal)". There are several implementations. As I know, Android tries to reach a file named generate_204 on one of the Google servers and if it is not possible, a notification in generated. It must be http (on local running 'server' like e.g. http://connectivitycheck.gstatic.com/generate_204 because if it would be HTTPS the otherside could't see which client is really behind). On newer OS the traffic can be encrypted do tue several implementation changes. However, it's a bad thing in my opinion since this requires more effort to check if someone is attacking the channel (side-channel attacks are still possible on the client side).


------------

> As the first rule of security is: Block anything except stuff you need/want.

Blocking everything can be a security risk, as I said above, NTP traffic is useful because it's depending on several other security functions (which people often call 'spying') like e.g. background certification traffic. On a mobile OS the use case is much more complex since you have to handle different access points, different checks (e.g. Captive Portal) and other things. Blocking everything is not always a good thing. Using filters within the OS and routers is better so that the end-user doesn't have to bother with all this. 

------------

 I haven't really started writing something about this topic because my time is very limited these days + the topic is gigantic, the thing here is that due to Android fragmentation (several different OS, Stock etc) we run into the problem that some manufracturers handle some things different and it would be a lifework to monitor all changes Android does, writing about it, mention the different user case scenarios and explain what it really does and what are the important things to know about. For example while ADB can be abused for 'evil' things like getting remote access, rooting the phone etc some people see it as security feature since it gives you full access over certain aspects on your operating system. 

Moreover I think most stuff should be fixed on the protocol level itself, Android 8+9 already changes lots of stuff and removed vulnerable things but the thing is once again fragmentation because not every device gets the latest OS and I do belive that you have to stay on the latest OS (no matter at which cost) otherwise you might give attackers the ability to abuse 'known' weaknesses which are might unfixed or not fixable (because they might need a entire re-write e.g. Windows Kerberos system which will never be fixed since this would break 'old' backward compatibility to some clients which still need it).

It's also questionable if some people would read it cause such a huge Wiki entry with a detailed explanation would be huge and most people are already annoyed if you write e.g. 2000+ words as detailed answer but you have to know how things are working otherwise the 'I block everything policy' only ends up with more problems.

**Comment by Atavic** [comment]
It's a system'a security feature: an intent filter is an expression in an app's manifest file that specifies the type of intents that the component would like to receive.

**Comment by k3dar** [comment]
btw: "(shell) - Linux shell" is also need enabled for adb working

**Comment by Miroslavonhub** [comment]
Hello, on my phone, when allowing all of those (when not too), calling doesnt work. If afwall is deactivated, calling works. What else may need to be allowed, and did i get it right that 1000 needs lan,wifi,mobiledata aswell as 1001? Thanks in advice for any replys.
Here is my afwall config, you might have to rename it back to .json so its valid.
[afwallconfig.txt](https://github.com/ukanth/afwall/files/11069919/afwallconfig.txt)
Thanks in advice for any replys.

**Comment by tempuserr** [comment]
There is not possible to fork Wiki with a browser access to Github, so maybe someone can PR info about allowing apps with **root [0]** access:

**root [0]** 
- Some Messenger, services and apps need root [0] enabled to use GCM (Google Cloud Messaging)
- Recommendation: Block if not using Google apps, otherwise allow for all connection types except LAN

Source: https://github.com/ukanth/afwall/wiki/Android-kernel-traffic#known-ports

**Comment by tempuserr** [comment]
System process `Network Manager, com.android.server.NetworkPermissionConfig` (UID 1073 on Android 12) constantly try to reach Google's servers IPs.

I found following info about it:
> Defines the UID/GID for fs-verity certificate ownership in keystore.

and 
> This package only exists to define the below permissions, and enforce that they are only granted to apps sharing the same signature. Permissions defined here are intended to be used only by the NetworkStack: both NetworkStack and this stub APK are to be signed with a dedicated certificate to ensure that, with the below permissions being signature permissions.

Can be added to [FAQ](https://github.com/ukanth/afwall/wiki/System-Applications-to-block-or-allow) with recommendation to block or not.

EDIT: 
it seems that internet access for this process is needed for many apps to access internet, e.g. Spotify shows as _Offline_ and didn't log in with this process blocked.
Conversely Brave browser works fine even with more blocked processes (this one, google play services, UID 1000, and few others system processes)

After unblocking this process dozens of stock installed apps starts to try to connect to network.
Additionally Google account didn't sync (contacts, calendar, etc.)) with this this process blocked - but this should be confirmed by someone else.
