### ISSUE TITLE
Possible knockoff on Play Store "ADFirewall"

### ISSUE THREAD

**Issue by AlexanderOMara** [ukanth/afwall#548]
I wasn't sure if this qualifies as an issue, but there appears to be a direct knockoff named "ADFirewall" on the Google Play store.

https://play.google.com/store/apps/details?id=dev.duyhoang.androidfirewall&hl=en

I'm not sure what the full story is, why it exists, or if it is safe to try, but thought it should be brought up.

**Comment by ukanth** [comment]
There are many clone's available on playstore. Since AFWall+ is opensource, we can't avoid these clones. None of these apps release their source. Funny part is I get lot of emails from these apps (using error report) asking for help 

Stay away from these apps and report it for abusing GPL licensing.

Here is the list of clones :)

https://play.google.com/store/apps/details?id=dev.duyhoang.androidfirewall
https://play.google.com/store/apps/details?id=ltd.banehappy.drofirewall
https://play.google.com/store/apps/details?id=com.ikramshah.firewallpk
https://play.google.com/store/apps/details?id=com.mueskor.securityfirewall
