### ISSUE TITLE
Firewall disables internet access for all apps intermittently

### ISSUE THREAD

**Issue by foreignb0dy** [ukanth/afwall#641]
Even with the experimental startup box unchecked, eventually network access is restricted for all apps. Disabling and then Enabling the firewall makes the internet work again.

**Comment by 0xjd** [comment]
I'm also still facing this issue and i think this might be similar as #603 #612 or #618.
Usually the app crashes when i switch between mobile data and wifi (vice versa). After killing the app and enabling the rules again internet is working again.
Also the possible solution disabling CaptivePortal using command shell or just allowing its connection with afwall didn't help.

**Update**: Since i've updated to version 2.9.1 everything is working fine!

**Comment by ukanth** [comment]
Please report in this way. Otherwise I can't fix
https://github.com/ukanth/afwall/wiki/HOWTO-Report-Bug#sending-bug-report

**Comment by foreignb0dy** [comment]
v 2.9.1 seems to have fixed it.
