### ISSUE TITLE
Multiple system apps in one item

### ISSUE THREAD

**Issue by successionreg** [ukanth/afwall#651]
![untitled](https://cloud.githubusercontent.com/assets/2804472/21686212/8c6b226c-d39f-11e6-8e9f-84a7771df0d7.png)

As shown in the photo, multiple system apps are combined into a single item. I cant really know if the blocking is working for this but it is working properly for other apps.

Device: OnePlus 3T running stock Android 7.0
AFWall+ Version: 2.9.1

**Comment by SebiderSushi** [comment]
I guess the reason for this is that all these Apps are in one single Package and therefore have the same user id in Android.  Which after all is the reason why this kind of firewall even works. Because it blocks users and every Package is treated as a separate user in Android.  So after all i assume this is a technical issue that can't be fixed within this app.

**Comment by ukanth** [comment]
Agree with @SebiderSushi , it's a technical limitation of android.
