### ISSUE TITLE
[Feature Request] Resolve IP address option for logs. 

### ISSUE THREAD

**Issue by davedavis** [ukanth/afwall#655]
In the log section, blocked requests are shown nicely. It would be great if there was an option to show these IP addresses' names resolved. 

I understand that some log categories can have hundreds of thousands of entries, so perhaps a long tap on an entry to resolve might work without having to have a separate option and warning? 

Would be cool to see the specific package/activity or system process that's making the request if it's possible too.

**Comment by walrus543** [comment]
+1
ukanth has such an idea in mind for months. We just have to be patient.
Logs of allowed connections is also useful BTW.

**Comment by davedavis** [comment]
At the very least, it would be good to be able to copy the ip address to the clipboard. Old and new log styles don't allow this. But a long tap context menu would be best. Copy or resolve (maybe additional details in future).

**Comment by vzool** [comment]
@davedavis That's a great idea 💯 

So, what about these options came from context menu shown when long tap pressed:
- Copy Source IP
- Copy Destination IP
- Ping Source
- Ping Destination
- Resolve Source
- Resolve Destination

What are you suggest ?

Thanks

**Comment by davedavis** [comment]
@vzool That's _**EXACTLY**_ what I'm suggesting :)

**Comment by walrus543** [comment]
@vzool do you still work on AFWall+?
An option to be able to block undesired connections from the logs would be an awesome. I finally switched to another firewall to have a better control of the connections.

**Comment by vzool** [comment]
@Primokorn No, sorry I'm currently interesting in something else.
Maybe I'll join again if I desire that in the close future.
I like your idea, it is very nice.
In fact, I don't have enough knowledge to implement your requirements now, a research is needed for me to accomplish your task.
Of course, @ukanth  is better than me for a good suggestions about if this project have a proper basement for that.
By the way, what is the other firewall you switched to?

**Comment by walrus543** [comment]
@vzool Actually I'm using both for now. When I need to have a closer look to the connections I switch to [NetGuard](https://github.com/M66B/NetGuard).

**Comment by vzool** [comment]
@Primokorn Yes, I used for a sometime and it does the job very nicely.

But, it turns out it does block the connection by a **local VPN connection**, and the Android devices has only one slot for a VPN application to run at once. You can't run any application using a VPN functionality while the **NetGuard** is working in the background. and android will told you that you should close NetGuard first. This is a **MalFunctionality** !!! Ha ha ha

My main demand is to make Firewall & VPN works together, side by side.

Who refuses VPN(Secure & Encrypted Connection) and let that for a firewall !!!

So, I lift NetGuard for that only reason. ^_^
