### ISSUE TITLE
VPN fine grain control 

### ISSUE THREAD

**Issue by raulcano** [ukanth/afwall#656]
Since a VPN connection runs over WiFi /LAN/data/roaming, it would be nice to have options to further control app inet access depending on which connection the VPN is running on.  

My proposal is the following:
Option "VPN fine-grain control" INACTIVE:
-The VPN filters works just as they do now. 

Option "VPN fine-grain control" ACTIVE:
-Have a further option "VPN inherit underlying connection" which, if active, when a VPN is on, an app will be allowed or blocked according to what is set for that app in the connection type the current VPN is running on. 
-If the option "VPN inherit underlying connection" is INACTIVE,  then it should be possible to manually select access for "VPN over LAN", "VPN over WiFi ","VPN over Data","VPN over Roaming". 

I understand this is not a trivial request, and alternative proposals may be better, but I guess I made my point. In any case, keep up the good work!

**Comment by ukanth** [comment]
It will be complex and less useful in my opinion.I'm open for discussion.

**Comment by raulcano** [comment]
I understand.
It's just that when I'm on roaming and I connect my VPN, then it's the VPN column that takes precedence and not the roaming one, which can lead to some high costs...

What about, for starters, the most "simple" scenario I put above. An option to enable/disable "VPN to inherit underlying connection". That would be , if I am on roaming and enable my VPN, the apps will be allowed if they are allowed in the Roaming connection. 
Does that make sense? 
Thanks in advance.

**Comment by ruralTom** [comment]
I'm with Raulcano here. One of the frustrations I've been fighting is that when my VPN is up, every app can get to the web. 

If I turn on VPN control, I can block or allow an app to access the VPN, but  apps that I have marked as "no data" but "yes wifi" and "yes VPN" can get to the web when the VPN is on data. This kind of control would be a game changer.

I try to limit my data usage because I pay per gig. So having the​ nuanced control Raul describes would be a huge blessing for a lot of us.

I've scoured the web for a way to do this but haven't found a tool that let's me accomplish this.

This would make one heck of a "donate" only feature!

**Comment by ruralTom** [comment]
For what it's worth, there's two to three similar requests to this one that are currently open.

**Comment by stavae** [comment]
(I realize this is an old thread, but) I have been looking high and low for this feature as well. Very simply put what I would like:
- All internet (wifi/4g w/e) always goes through VPN (This works fine right now)
- Some apps never get internet (This works fine right now)
  - Some apps only get internet access if VPN + WiFi (e.g. for downloading/streaming etc.)
  - Other apps also get internet access if VPN + Data (pretty much just WhatsApp/Telegram)

This way I can keep my internet data super low (<5MB month) while still having a VPN.
I use prepaid internet because I dont use that much data and it is cheap. This was my whole reason for using Afwall in the first place, but using it with a VPN is awkward because of this lack of control.

**Comment by ruralTom** [comment]
I managed to make three profiles and have tasker bounce between them as my
data situation changes.

**Comment by stavae** [comment]
@ruralTom I didnt know Afwall had a Tasker plugin, Thanks. This works flawlessly :D

**Comment by raulcano** [comment]
Hi @ruralTom, could you please explain a bit your solution? Thanks in
advance!

Blutti <notifications@github.com> schrieb am So., 27. Mai 2018, 09:38:

**Comment by stavae** [comment]
@raulcano Basically install tasker and create 2 events. One for when you have WiFi and one for when you dont. 
In AFWall you make 2 profiles and activate them (/make tasker activate them automatically for you) when you gain/lose WiFi

**Comment by raulcano** [comment]
Cool, thanks a lot!

Blutti <notifications@github.com> schrieb am Di., 29. Mai 2018, 19:32:

**Comment by ruralTom** [comment]
Sorry, been busy with work. I made 4. 1 for mobile, with vpn, 1 for home
wifi, one for other wifi VPN on lt and the last is only for googl maps and
communication apps.
