### ISSUE TITLE
Apps bypass firewall if a proxy used in the wireless settings

### ISSUE THREAD

**Issue by gerroon** [ukanth/afwall#658]
Hi

I accidentally foud  out that if I set a proxy in the Android  wireless control settings, Afwal is not able to block apps traffic. I am not sure if this is by design or a bug.

thanks

**Comment by ukanth** [comment]
I need more information like device/proxy settings/iptables rules etc.

**Comment by gerroon** [comment]
I am using privoxy instance ip in the proxy settings of advanced settings when you set a wireless connection in Android's connection editor. 

As far as Iptable rules goes, I do not have any additional ones, I just use the app listing to enable disable apps.

This was CM13 but I had the same issue with another Android, I believe it was lollipop. 

Once I saw that the connections was not guarded I disabled proxy settings in the connection editor. You can also use Mitm as proxy and see that the connections happen regardless of Afwall

**Comment by sibrat** [comment]
>I accidentally foud out that if I set a proxy in the Android wireless control settings, Afwal is not able to block apps traffic. I am not sure if this is by design or a bug.

I also got this problem but find out that it was due to my misconfiguration. You shoud treat proxy's internal (local) ip address as internet address in iptables rules. I.e. must except it from local area band or (if it outside your LAN) not permit all to that ip

**Comment by ivantao8** [comment]
> Apps bypass firewall if a proxy used in the wireless settings

similar problem here.
seems all apps pass through due to system proxy setting.
[afwall-backup-all-2018-09-01-20-48-03.zip](https://github.com/ukanth/afwall/files/2342404/afwall-backup-all-2018-09-01-20-48-03.zip)
proxy setting:`127.7.7.7:8118`
tcp        0      0 127.0.0.1:5353          0.0.0.0:*               LISTEN      3816/dnscrypt-proxy
tcp        0      0 127.7.7.7:8118          0.0.0.0:*               LISTEN      5863/privoxy
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN      5619/stunnel
tcp        0      0 ::1:5353                :::*                    LISTEN      3816/dnscrypt-proxy


>  I.e. must except it from local area band or (if it outside your LAN) not permit all to that ip

tried,failed.how to get this done?
below is my rule,it doesnt work.
`iptables -N proxy`
`iptables -A proxy -m owner --uid-owner 10121 -j RETURN`
`iptables -I proxy -m owner --uid-owner 0 -j RETURN`
`iptables -A proxy -j afwall-reject`
`iptables -I afwall -d 127.7.7.7 -j proxy`

my device:redmi5 V9.6.3.0.NDAMIFD (MIUI9) (android 7.x)
non native english,sorry

**Comment by ivantao8** [comment]
> similar problem here.

my bad，didnt replace custom script,and my rules works fine.
