### ISSUE TITLE
use iptable binding libraries?

### ISSUE THREAD

**Issue by zcattacz** [ukanth/afwall#686]
Hi, 
Is afwall using any iptabls binding lib like https://github.com/ldx/python-iptables (Its not java, I know. but that's not the point here. the great java must have sth alike, right?)
I feel afwall is acting so slow sometimes when turning on/off firewall, applying rules.
espcially one cant change and apply indivisual rule. thus i am guessing its commandline parsing based? i see there are many customized rule related ticket. this will make them a lot more robust and easier.

(sorry, should be iptables)

**Comment by ukanth** [comment]
This could be done using JNI/libiptc in Java. But that's too much of work. The biggest problem with that approach is Android Fragmentation. Since iptables built-into Android, most of the time it's abandoned by device manufactures ( old version ) 

We could improve the performance in multiple ways in Java way itself. I will look at performance when I get some time.
