### ISSUE TITLE
No updates on F-Droid since 2.9.1

### ISSUE THREAD

**Issue by Miwer** [ukanth/afwall#696]
Hi,

I'm using AFWall from F-Droid repository, but it seems there are no updates since 2.9.1 (2016-12-15).
Did something happen with the process of publishing the updates on F-Droid?

https://f-droid.org/repository/browse/?fdid=dev.ukanth.ufirewall

**Comment by ukanth** [comment]
Kindly raise the issue in f-droid's repo.  Last time I heard it failed because of some internal build error from f-droid without any proper logs.

**Comment by Miwer** [comment]
Excuse me?
I was merely trying to make you aware of a potential problem with updates on a repository that you yourself promote on your site. Maybe you should raise the issue with F-Droid yourself, but if you're not going to bother, then perhaps you'd want to change the information on your web site, and not promote F-Droid. I really don't care - I'll just uninstall the F-Droid version, and install from Google Play instead.
I can't say that this wasn't informative, so thanks anyway.

**Comment by bfritz** [comment]
@Miwer Wow.  That was harsh for no good reason.
@ukanth Thanks again for making afwall available as open source.  I use the F-Droid version and I'll raise an issue there.

**Comment by ukanth** [comment]
Fair enough. I will remove f-droid support now onwards !

**Comment by bfritz** [comment]
Also, this is a known issue:
https://gitlab.com/fdroid/fdroiddata/issues/637

No promises on timing, but I'll try to reproduce it and see if I can find a path forward for the f-droid build.

**Comment by ShapeShifter499** [comment]
@ukanth @bfritz I'm sad F-Droid is being dropped, I install stuff from both F-Droid and Google Play. I try to install most of what I need from F-Droid because I want to use and support open source projects.  I did purchase both the "donate" and "unlocker" packages in Google Play Store to show my support.  

I hope this can be fixed and updated in F-Droid as F-Droid just added back support for "privileged extension" in Android 5 or newer.

**Comment by ukanth** [comment]
You can always download apk files from https://github.com/ukanth/afwall/releases. The problem with F-droid, they change something internal and they don't bother giving logs/more information. I have travis CI which builds on each commit and always works. 

If they don't fix/information, I have no choice, but remove the support for F-droid.

**Comment by ShapeShifter499** [comment]
@ukanth I understand, F-Droid is a bit wonky from what I see.  It's easier for me to install from Google Play at this point so I'll switch to that version. Thank you for all the work on this.

**Comment by Miwer** [comment]
@bfritz You're right - I was a bit harsh there. I was just a bit surprised of the closing, and apparent display of indifference towards the issue, which I was trying to give notice on.

Apologies to @ukanth. I was not aware, that the problems are F-Droids fault. I do however still believe, that app authors should take action against the repositories, they choose to publish on, not the users. I appreciate the work you do on the AFWall. 

Have a nice day. :)

**Comment by ukanth** [comment]
@Miwer , no need to apologies, you have to see from my end. I get 5/6 emails every day saying the same issue that f-droid builds are not coming. Everyone thinks I own builds at F-droid. But authors doesn't have any control on their build machine. 

I shouldn't have closed. Let it be open, so that next guys doesn't open the same request :)

**Comment by bfritz** [comment]
@ukanth replied ahead of me, but this might be worth saying anyhow...

As I understand it, the relationship between F-Droid and OSS authors is a tricky one.

F-Droid, by design, runs their own build infrastructure and does their own signing.  As a F-Droid user, I consider that a feature.  It means I can be fairly confident that the build matches the source published in the project's repo.  It also gives me access to some really good apps while opting out of most of the Google ecosystem.  (I don't want a dozen Google services running on my phone and collecting data about me so I can be sold ads.)

But F-Droid adds headaches for OSS authors.  Now a small, but likely vocal, group of their users are getting the app from F-Droid and a build pipeline out of the author's control.  If something goes wrong over at F-Droid, authors get complaints from users even though the app works fine outside the F-Droid ecosystem.  And F-Droid does a really poor job (IMO and limited experience) of making it easy for the authors to track down build failures.  Case in point:  I just wasted the better part of an hour trying to [this commit](https://gitlab.com/fdroid/fdroiddata/commit/f08ebf2b20d9a66363e20337f31688457fad0938) and correlate it to a failed GitLab CI build.  I came up empty.  In contrast, I can trivially review the afwall [Travis builds](https://travis-ci.org/ukanth/afwall).

Not that anyone wants my advice, but...
* If you don't care about what F-Droid offers, using apps from Google Play instead will probably work better for you.
* If you do value F-Droid, you'll probably need to get your hands dirty once-in-a-while tracking down issues.  Complaining to upstream authors without offering something in return is likely to be a dead end.

Out of time for today, but I'll keep my eye on AFWall in F-Droid.  It was [recently bumped to 2.9.4](https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/dev.ukanth.ufirewall.txt).  Hopefully the F-Droid build issues sort themselves out.  If not, I'll try to carve out time to reproduce the failed F-Droid build and get a PR in over there.

**Comment by hackel** [comment]
F-Droid was the most convenient option to install AFWall on my Nexus player, since it doesn't show up in Google Play for Android TV devices.  Otherwise I have to sideload every update.  Sadly, after checking the release notes, it seemed your dropped x86 support, so I won't be able to use any new versions anyway. :(

**Comment by bfritz** [comment]
The build of 2.9.4 on F-Droid succeeded[1,2].  The apk was signed yesterday and is now available for download[3].

[1] https://f-droid.org/wiki/page/dev.ukanth.ufirewall/lastbuild_15940
[2] https://gitlab.com/fdroid/fdroiddata/issues/637
[3] https://f-droid.org/repository/browse/?fdid=dev.ukanth.ufirewall

**Comment by knezi** [comment]
Yes, I've just received the update. Thank you all for solving it.

**Comment by ukanth** [comment]
@hackel , I added the support back with 2.9.4. You should be good with 2.9.4 !

**Comment by hackel** [comment]
Brilliant, thank you @ukanth!
