### ISSUE TITLE
OpenVPN and AFWall+

### ISSUE THREAD

**Issue by ghost** [ukanth/afwall#699]
Hello,

I think this is related to https://github.com/ukanth/afwall/issues/51. I am using AFWall+ on LineageOS 14.1 (Android 7.1) and am facing the fact that all blocked app are able to bypass the firewall when the VPN is active.

I might need to say that the VPN runs over TCP on port 443 instead of 1194/UDP.

Do you have a suggestion of how to fix this and get the apps blocked on VPN as well?

**Comment by Itsnothectic** [comment]
I have Lineage too and I wanna know if this is gonna work with Netguard that uses a local VPN?

**Comment by walrus543** [comment]
Could you provide more information?
I'm using OpenVPN and AFWall+ 2.9.4. OpenVPN is the only app that has access to WiFi and Mobile data. Other apps only have VPN allowed.
As soon as OpenVPN is off no apps have access to Internet.

**Comment by EchoDev** [comment]
I noticed this too. You need to enable the separate VPN controls if you want apps to stop bypassing your wifi/mobile network settings. 


It would actually be nice if there were more VPN specific options e.g. stop traffic from mobile networks when VPN is not active.  At the moment I disabled access for all apps to mobile networks which works(ish...it just stops all traffic until I manually enable the VPN =D...oh and it shows an error symbol for the mobile network icon because the kernel etc. gets blocked too and it doesn't seem to recover from that status)....Anyways this last part is kinda offtopic lol...

**Comment by protist** [comment]
This is also slightly off-topic, but I spent half an hour working this out. You may also need to enable IPv6 support (Preferences > Rules/Connectivity > IPv6 support). With OpenVPN off, I didn't need this on, but when using OpenVPN, this setting had to be enabled.
