### ISSUE TITLE
Bug: Data being leaked

### ISSUE THREAD

**Issue by neilmacintyre** [ukanth/afwall#709]
I am not sure what is going on but Chrome and Firefox allows several sites through on by Nexus 6 (shamu) on Android 7.0 stock and rooted, despite being both being disabled. Websites including Google, Cnn and Wikipedia all go through but most others don't. Snapchat also goes through desptite being blocked. I have logging enabled and it says all the apps I mentioned are being blocked despite everything going through.

**Comment by ukanth** [comment]
Have you enabled IPv6 ?

**Comment by raulcano** [comment]
Can confirm with Firefox App. I'm on Android 7.1.2

**Comment by walrus543** [comment]
Android 7.1.2 - Firefox beta - AFWall+ 2.9.4 - MagiskSU
**NO LEAK**
IPv6 connections are blocked.

**Comment by raulcano** [comment]
@Primokorn How did you block the IPv6? I'd like to try

**Comment by walrus543** [comment]
@raulcano Preferences > Rules > Block IPv6.
There's also a custom script in the Wiki.

**Comment by raulcano** [comment]
Thanks!!

**Comment by ghost** [comment]
Same issue here but only in Wifi mode 
Android 7.1.2_r8
AFWall+ 2.9.4
MagiskSU

No change with IPv6 blocked or not

@Primokorn @raulcano @neilmacintyre 
can you please check if the leak is wifi only?

@neilmacintyre yes for me is google.com not blocked but github.com is blocked, strange!

**Comment by ghost** [comment]
Here is a logcat where i did the following:
* powered on my device
* enabled mobile data
* opened org.lineageos.jelly(Browser) and tryed to open google.com and github.com
* disabled all AFWall+ rules
* switched to Browser and opened google.com and github.com
* enabled all AFWall+ rules
* enabled wifi
* switched to Browser and opened google.com and github.com
* disabled AFWall+ rules
* switched to Browser and opened google.com and github.com
* enabled AFWall+ rules
* switched to Browser and opened google.com and github.com

https://www.file-upload.net/download-12525883/afwall.logcat.html

**Comment by neilmacintyre** [comment]
By enabling ipv6 support all of my problems are solved even on wifi. @Herny64 I would just double check that Ipv6 support is selected under prefrences -> rules and connectivity. 
@Primokorn What exactly is the differecnce between Block Ipv6 and support IPv6?

**Comment by ghost** [comment]
@neilmacintyre so i need to support it instead of block it ?

Im a bit confused about the 3 possible Options

1. uncheck both "Support IPv6" and "Block IPv6"
2. check "Support IPv6"
3. check "Block IPv6"

while 2 and 3 are alternatives to each other i have no idea what happens at 1

**Comment by ukanth** [comment]
1. Block It - if your wifi/carrier supports only ipv4 connection 
2. Allow it - if your wifi/carrier supports only ipv4 and ipv6 connections.

How to check if your carrier/wifi support ipv6 ?

http://test-ipv6.com/

Also don't forget to reapply the rules when enable or disable ipv6 related settings.

**Comment by walrus543** [comment]
For the record, it has been discussed on XDA: https://forum.xda-developers.com/showthread.php?p=69693440&postcount=3451#post69693440

**Comment by peake** [comment]
I'm getting a data leak too and, like Herny64, it's only out Wi-Fi -- cell data gets filtered properly.  In looking at the generated ruleset, I see the chain 'afwall-wifi-fork' has no rules to its name.

@ukanth:  After doing a bit of testing, this problem seems to only happen when "LAN control" is enabled.

@Herny64: If you have "LAN control" enabled, can you disable it and confirm whether that fixes it for you?

**Comment by anewuser** [comment]
MX Player started displaying ads to me when I connected to a wifi network, even though I've never whitelisted external connections for it.

It seems that it's the same problem as what has been reported here.  I also have IPv6 support and "LAN Control" enabled. I've uninstalled it, but if none of you have it installed to verify it and check if toggling that setting makes it stop, I may install it again.

Nexus 7 2013
LineageOS nightly

**Comment by peake** [comment]
Fun new data point:  My problem (chain 'afwall-wifi-fork' is empty) seems to only happen upon two conditions:  "LAN Control" is enabled and Wi-Fi is disabled during boot-up (i.e. system Wi-Fi was turned off before the last shutdown/reboot).

**Comment by peturbg** [comment]
hi guys.

now this is serrious problem for the peoples and im gonna ask the developer ukanth why you sell your ass to the elite and governments. ukanth your afwall+ was great before 2.9.1 after that to 2.9.5 include the new version DATA LEAKS. i install the latest include i install veraon 2.9.4 and it too data leaks. so when i install 2.9.5 or was leaked. so after i return to 2.9.1 ALL WORKS GREAT. why ukanth the firat day the problem start i wait to see if you are gonna repair the problem AND YOU ukanth DONT WANT TO REPAIR THE PROBLEM. YES im the person who wrote you email and you disnt want repair the DATA LEAKS. so why i nees to pay for a program that is like microsoft that DATA LEAKS all data illegaly or legally. afwall+ is to block not to data leaks. HEY GUYS return to 2.9.1 and you are gonna see the afwall+ works perfectly. from two or three version of afwall+ it start data leaks include now i have fears to install if afwall+ has new version. ukanth tell of the peoples if you want more money and stop SELL you ass to tge elite ans governments peoples. for this peoples who love afwall+ and didnt buy the program. please dont buy the program becouse after version 2.9.1 to version 2.9.5 afwall+ is DATA LEAKS, no mather what you do afwall will leaks include if you turn log on it will not log anything. im with super su 2.7.9 sr3 on nougat galaxy s7. so guys dont buy afwall+ version 2.9.5 becouse it is like you dont nothing. ukanth bratushka if i remember corrwctly you are from ukraine stop selling your ass and if someone put pressure on you comment it here and make youtube, if you tell the true only the peoples will help you, the elite and governments are only killing peoples dont belive them. ukanth this issue is high, it continue how i say more than one time in this message fix it and make too block ipv6, becouse in versio  2.9.1 blockipv6 dont work and some program google play conctact on ipv6.

**Comment by peturbg** [comment]
ukanth deleted a comment from peturbg 7 hours ago
so ukanth you try delete becouse i say true  that you sell your ass to the elite and governments, ukanth you know about data leaks, amd now ukanth you confirm yoi will not fix the data fix. peoples dont buy new version of afwall or afwall+ after version afwall and afwall+ 2.9.1 to afwall and afwall+ there is data leaks and peoples you can see ukanth know about this problem amd data leaks ukanth deleting the true will not aolve your seling ass to elite ans governments. peoples are you gonna trust and peoplea are you gonna give your your money for developers that sell and leaks your life. ukamth know about this data leaks tbis data leaks come after veraion 2.9.1

**Comment by ukanth** [comment]
@peturbg , repeating the same issue on every thread is not going to resolve the issue. I never blocked anyone till date.  Also, kindly mind your language. AFWall+ is opensource project and it doesn't collect any data to sell to governments. 

If it's bug, it will get fixed.  If you are not happy, delete AFWall+ and move on to any other firewall which satisfies your need.

**Comment by peturbg** [comment]
ukanth Also, kindly mind your language. ukanth you are LIER. after version 2.9.1 to version 2.9.5 you didn't fix data leaks, so don't lie the peoples. And i don't have afwall+ ukanth comment " If it's bug, it will get fixed. " so ukanth if you don't see the bug you will not repair it. ukanth you didn't repair data leaks after version 2.9.1 to version 2.9.5 ukanth you can block, but you will be blocked, ukanth how you are gonna feel if someone block your mounth and if you are blocked in the real life lets see how you are gonna feel. ukanth don't worry, more peoples will complaint about data leaks. im gonna make youtube video to remain the peoples of this day that you had been reported this data leaks was reported and you ukanth try menace, but ukanth you are menace. ukanth you had been reported that there is data leaks after version 2.1.9 but when i make youtube video after that don't try to escape.

**Comment by ukanth** [comment]
Can you guys test this version and let me know if this resolves this issue ?

https://www.dropbox.com/s/e9e1go4a4142j31/AFWall%2B%202.9.6-BETA.apk?dl=0

**Comment by peake** [comment]
So far so good.  Everything seems to be working as it should.
