### ISSUE TITLE
Trouble with KingRoot!

### ISSUE THREAD

**Issue by RobertRBT** [ukanth/afwall#715]
KingRoot will change iptables and there should be a service reapplying afwall rules every x second so preventing kingroot...

There might be a better solution but the point is to fight with kingroot without killing her :)

Good luck

**Comment by ukanth** [comment]
Actual problem is, Kingroot always  has an upper hand, since it manages su. It can silently deny access to AFWall+ and pretent that it does( technically possible). 

I don't want to accuse without any solid evidence. But I would avoid any app which has suspect  behavior. Most of the community now moved from SuperSU to Magisk including me and all my devices.

**Comment by CHEF-KOCH** [comment]
KingRoot is awful and should be avoided at all cost. [KingRoot was originally written to steal your data](https://forum.xda-developers.com/android/general/kingroot-malware-adware-root-t3563090) (the reason earlier - dunno if it still does) needed an [active Internet connection](https://www.quora.com/Is-KingRoot-safe-for-my-phone). That's also the reason why it's still often been detected by most AV's as malware.
