### ISSUE TITLE
Wrong icons in the log

### ISSUE THREAD

**Issue by walrus543** [ukanth/afwall#716]
Hi,
As the title says:
* Example: Titanium Backup icon on Substratum's line
* Swiftkey Keyboard appears twice with 2 different UID

![screenshot_20170621-080450](https://user-images.githubusercontent.com/5938828/27372173-f1edebd2-5663-11e7-8a5a-ab054a498d0a.png)

AFWall 2.9.5 - Android 7.1.2 - Magisk 12

**Comment by ukanth** [comment]
Logs are stored in database and if you restore using Titanium backup, you might see this. Because UID changes everytime when you install/uninstall.

But AFWall+ stores the log record at that time what UID got blocked ( we could change it to package instead)

I will see if I can get sometime to fix it.

**Comment by walrus543** [comment]
I was going to try without restoring from TiBu.
FWIW after restoring from TiBu I import my json backup.

Switching to package name would be better indeed since UID are not the same after a clean flash. I guess it could also help for some apps: my json backup doesn't apply the right rules for Firefox.
