### ISSUE TITLE
Blacklist specific app

### ISSUE THREAD

**Issue by JonnyTech** [ukanth/afwall#773]
I am in whitelist mode, but I want to blacklist one specific app sometimes - how can I achieve this with a script - is there a suitable example that I can examine?

**Comment by CHEF-KOCH** [comment]
iptables are not designed to manage per-application filtering, the only thing which you could write is a script which checks the [user/group/process ID.](https://debian-administration.org/article/120/Application_level_firewalling). 

The problem here is that it can be bypassed, whenever someone creates another profile or runs another app under root rights this might not block (all) connections. This also won't work under an Android tunneled connection (VPN).
