### ISSUE TITLE
Default Rule For New App Installs?

### ISSUE THREAD

**Issue by whitedavidp** [ukanth/afwall#814]
Not really an issue. More like an enhancement request...

Your app works great under most conditions I have tried so far. However, it seems that any time I install a new app I will have to go into your app and update the settings for that new app and apply them. I wonder if it is possible to do something to relieve this burden?

I was thinking that your app could listen for new installs (not needed/wanted for update installs) and, when they occur, automatically apply a default rule that the user specifies. In my case, by default I will want any new app to be granted access to wifi/lan but not to 3G/roaming. So I was thinking that at the bottom of the current display, beneath the final line (Any App) you could place a new line where the user can specify the default pattern to use.

I don't know yet what your app does if the user uninstalls an app that has had a rule set for it. One of my apps, Keyboard Master, listens for app uninstalls and removes any settings the user has made for that app (if any). It just seems like the suggestion above would go along with something like this.

**Comment by CHEF-KOCH** [comment]
I'm against it, ADGuard nor Avast firewall does have such an option. It makes no sense to allow this because if you accidentally install an app it automatically e.g. gets internet connection without any user interaction. 

The purpose of a firewall is (by default) to block and not to allow xyz to prevent possible data leaks. It takes like 5 seconds to go into the app and manually control it, which is fine with me how it right now is.

> I don't know yet what your app does if the user uninstalls an app that has had a rule set for it. One of my apps, Keyboard Master, listens for app uninstalls and removes any settings the user has made for that app (if any). 

AFWall+ does nothing, it would only fill the database with a lot of dead entries if you would like to keep each and every single settings for each individual app. Another problem is that you might change your mind over time and forget that app x was already installed + configured and then you also end up with leaks. Keep also in mind that the bigger the database gets the more you waste your storage with garbage and it only takes more time to load it (at initial load) with then fills up your ram to store the data constantly while AFWall+ is running in the background.

**Comment by ukanth** [comment]
Added in 3.5.0
