### ISSUE TITLE
AFWall don't autostart and apply rules

### ISSUE THREAD

**Issue by PutinVladimir** [ukanth/afwall#851]
If "Turn on log service" is off, then AFWall do not start&apply rules after reboot phone.

**Comment by dimgel** [comment]
JFYI: Was googling same issue, but turned out to find solution myself: in application properties, I've set Battery Saver = No restrictions. Didn't see this mentioned in FAQ, maybe worth adding. (Log was on; although it works only for 2 hours after [re]install, too lazy to create new issue.) My phone is Xiaomi Redmi 5 Plus 6/64GB, MEG7 (international), Android 7.1.2, MIUI 9.6.3.0.

**Comment by dimgel** [comment]
// Ups, log works now too, maybe was also Battery Saver issue.

**Comment by ukanth** [comment]
Try with latest version and reopen if still present.
