### ISSUE TITLE
Captive Portal Check Service?

### ISSUE THREAD

**Issue by MrGlasspoole** [ukanth/afwall#868]
What exactly does block the Captive Portal Check in AFWall?
I did disable captive_portal_detection to get rid of the exclamation mark. But what if you are on a vacation and in a hotel? Nobody wants to go to the terminal on vacation...

So is there a simple way to turn this stuff on and off so that for example the hotel login page works?
Or does that work anyway and has nothing to do with the Android check?

I also never had that exclamation mark problem on my 4.x.x devices. Had it the first time on 6 and now 7.
Does 4 not have this check?

**Comment by 0lm** [comment]
yeah that exclamation mark problem exists since android 6. thats why you dont have any problems with android 4.
i would like to know a solution for that problem, too. i also had to set captive portal mode to 0 on my lineageOS 15.1 when i want to access to google or yalpstore via my own wifi connection.

**Comment by ukanth** [comment]
Use adb to disable it.

http://littlebigtomatoes.com/2017/02/disabling-captive-portal-check-in-android/

**Comment by MrGlasspoole** [comment]
As we wrote we already disabled it...

**Comment by MrGlasspoole** [comment]
> 
> 
> Use adb to disable it.
> 
That was not the question. As we wrote we already did that...

**Comment by therealmaxmoon** [comment]
Is there a solution for this, because I have this issue still in 2021.
