### ISSUE TITLE
Internet connectivity detection, addition request to FAQ

### ISSUE THREAD

**Issue by ConniShiva** [ukanth/afwall#891]
I had problems with my mobile detecting if there is a valid internet connection over wifi.
You can just ignore the message and everything works as intended.
I didnt want to give too many sysapp a firewall bypass, because of privacy so i let it be that way

BUT

Sync services on 8.1 (omni-rom) do not start (not even when triggered manually) if there is no internet connection detected. After allowing pid 1000 (Android-System,etc) the internet connection was detected and Davdroid, Firefox, etc started syncing imediately.

So i think this should be reflected in the FAQ as a side effect of blocking pid 1000 Android System,etc...

Other people seem to have this problem as well (it's where i got the solution from):
https://forums.bitfire.at/topic/1816/android-one-8-1-doesn-t-sync-calendar/11

**Comment by UniDoY** [comment]
Thanks for this, I was going crazy why I could use internet normally but/and in my case Play Store doesn't download if I don't allow pid 1000. I also found it a bit, confusing because that pid is also for things like Fingerprint and face, things I don't feel needs to have access.

**Comment by doodhout** [comment]
So THAT is what was wrong with Firefox Sync while using AFWall+ on my new phone running Android Pie (9.0). I was already considering opening a new issue here on github for this specific case, but it turns out it's more generic: no synchronising if process with UID=1000 is blocked in the firewall.

Can anyone explain the technical reason why this is the case? I don't feel comfortable allowing that enormous bundle of services that hide behind process(UID=1000) access to the internet when I don't feel it's necessary or a choice I make.

EDIT: it seems that instead of allowing PID=1000 internet access, you can just disable internet access check like this: https://github.com/ukanth/afwall/issues/761

This solution is also mentioned in the link posted by OP.
