### ISSUE TITLE
AFWall blocking access to the Download Manager for whitelisted apps (even when disabled)

### ISSUE THREAD

**Issue by mikekrunk** [ukanth/afwall#903]
Hi,

I am having an issue in that the firewall is blocking access to the Download Manager for the Tecarta Bible app. This is happening regardless of the firewall being enable or disabled. I have tried whitelisting the app for all connection types. I have the download manager whitelisted.

The following message is appearing on my screen when I try downloading anything through the app.
![screenshot_20181121-094710_bible](https://user-images.githubusercontent.com/45242728/48863991-82004580-edcb-11e8-9851-bad65ba59a61.png)

Please help. :)

**Comment by ukanth** [comment]
Disable xposed module.its a bug in xposed module.

**Comment by mikekrunk** [comment]
Thanks for a quick reply. It's working now!

**Comment by cruxcoder** [comment]
I had this issue on Lineage OS 14.1 and 15.1 (with microg) both using Xposed, and as you mentioned disabling the Xposed module got rid of it.  

Took a quick glance at the plugin source and it looks like it only exists to remedy the download manager bypass problem.  But since this issue was closed, does that mean this is going to remain unfixed?  Or is there a blocking issue that prevents a fix being done or?  

thanks.
