### ISSUE TITLE
WIFI tethering doesn't work

### ISSUE THREAD

**Issue by takiainen** [ukanth/afwall#924]
Phone: Oneplus One
ROM: Android Oreo, microg lineage (clean flashed, no GAPPS, no mods).

Afwall doesn't let through WIFI tethering traffic despite whitelisting "-11 tethering". Tried also with "-12 Linux kernel" since it was mentioned in other similar issues, but it does not work. 

If I disable Afwall, tethering works fine.

I have latest F-Droid Afwall version 3.0.3. My friend has version number 2.9.9, and his WIFI tethering works fine (also Lineage rom 8, also OneplusOne).

**Comment by tlpbu** [comment]
Identical situation for me - always have to disable Afwall+ for tethering period.

**Comment by yoshi7** [comment]
I had to activate "Enable inbound connections" under Preferences -> Experimental.

**Comment by takiainen** [comment]
I cannot get it work with "inbound connections" either.

**Comment by tlpbu** [comment]
I can confirm that wifi tethering does not work even with "Enable inbound connections" under Preferences -> Experimental activated and phone restart afterwards.

I have Oneplus One with LineageOS but this is probably not important because I have had this issue for years one multiple devices and Android OS variations.
Would be great to finally solve this problem of having to manually disable firewall during wifi tethering.

Do not have opportunity to verify now but AFAIR USB tethering works with Afwall+ enabled - problem lies only with wifi tethering.

**Comment by ukanth** [comment]
I never had issues with Wifi Tether/Bluetooth hotspot. It will work if you don't route the traffic from the source( means VPN or TOR). If it still doesn't, attach the rules when the tether doesn't work along with logs (firewall logs)

Thanks.

**Comment by 9662** [comment]
What is it that doesn't work? Does the wifi connection authenticate? Does the DHCP negotiation succeed? Does DNS resolving work?

What does the log say?

In my case, I was unable to get the DHCP negotiation working. It turns out I need to give "Applications running as root" wifi access, else DHCP gets blocked. Afterwards, I can remove the access and things keep working (presumably until the next DHCP refresh, I haven't checked).

**Comment by takiainen** [comment]
The iptables rule given here solves this issue for me: https://github.com/ukanth/afwall/issues/965

It seems that afwall's UID was incorrect. Here are the iptables rules copied from above:

#!/system/bin/sh

IPTABLES=/system/bin/iptables
IP6TABLES=/system/bin/ip6tables

$IPTABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 67 --dport 68 -j RETURN
$IPTABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 53 -j RETURN
$IPTABLES -I afwall-wifi-tether -p tcp -m owner --uid-owner 1052 -m tcp --sport 53 -j RETURN

$IP6TABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 67 --dport 68 -j RETURN
$IP6TABLES -I afwall-wifi-tether -p udp -m owner --uid-owner 1052 -m udp --sport 53 -j RETURN
$IP6TABLES -I afwall-wifi-tether -p tcp -m owner --uid-owner 1052 -m tcp --sport 53 -j RETURN

**Comment by 9662** [comment]
What application runs as UID 1052?

**Comment by JasMan78** [comment]
Same issue here with Google Pixel 3 with security patches from 07/2019.

When wifi tethering is enabled the client becomes an IP address, but is not able to resolve any DNS names.
The firewall log shows that process "Unknown(1052)" was blocked. When I open the details of this entry I can see that not the DNS request from the client is blocked, but the response from Android.
Here's an example:

````
29-07-2019 08;42:27(wlan1)
Destination:192.168.43.168:57871
Host:
Source:192.168.43.250:53
Protocol:UDP
````

Not sure how to export the whole firewall log.
Find attached the export of my AFwall rules.

[AFwall_Rules.txt](https://github.com/ukanth/afwall/files/3440724/AFwall_Rules.txt)

**Comment by Stevemoretz** [comment]
None of the solutions worked I updated to the latest version thought this would help :
https://github.com/ukanth/afwall/pull/1141

But nope not working, what is the solution?

**Comment by haraldrudell** [comment]
For Wi-Fi tethering, dnsmasq listens on the interface provided by hotspot to the clients
— clients make dns requests on the hotspot ip address
— on clients, using local dns 127.0.0.1 or 8.8.8.8 may be working, but not the hotspot ip address

The problem is that dnsmasq goes outside vpn and make its delegated requests from the direct upstream wan or wi-fi connection. Old AFWall like 2.9 does not have user id 1052 dns_tether in its list
— security risk: upstream dns is not encrypted
— Hello **Google**, update please
— that’s Android 12…
— Once dns is working, hotspot clients can configure dns privacy

on hotspot device:
install termux
install nano: pkg install nano
in root adb session:
```bash
/data/data/com.termux/files/usr/bin/nano /data/tether
—
#!/system/bin/sh
# © 2021-present Harald Rudell <harald.rudell@gmail.com> (https://haraldrudell.github.io/haraldrudell/)
# License: ISC
# /data/data/com.termux/files/usr/bin/nano /data/tether
unset RULE CHAIN
RULE=(--match owner --uid-owner 1052 --jump RETURN)
CHAIN=afwall-3g-home
if ! iptables --check $CHAIN "${RULE[@]}"; then 
  iptables --insert $CHAIN "${RULE[@]}"
fi 
RULE=(--match owner --uid-owner 1052 --jump RETURN)
CHAIN=afwall-wifi-wan
if ! iptables --check $CHAIN "${RULE[@]}"; then 
  iptables --insert $CHAIN "${RULE[@]}"
fi 
unset RULE CHAIN
—
chown root:root /data/tether
chmod 755 /data/tether
ls -l /data/tether
-rwxr-xr-x 1 root root 1565 2021-11-12 14:18 /data/tether
```

In AFWall+: select ⋮ — Set custom script
Enter custom script below.
. /data/tether
Note: the line above starts with period, space
tap OK
— Working…

dns on hotspot clients should now work. Check on a client that it can browse to apple.com and find M1 Max

BONUS:
Bluetooth tethering works, too

**Comment by GordianLN** [comment]
> 

Can confirm the above solution is working, I just used Xplore with root to create the file, the rest was followed to the letter, android 12 on hotspot.

**Comment by agaricus-campestris** [comment]
Did work on Pixel 3A XL !
Just needed to remember I had to `adb shell` and `su` before applying script !
(゜▼゜＊）

**Comment by infinity0** [comment]
Same issue for me on LineageOS 19.1 (Android 12) with MicroG on OnePlus 8T (KB2003), AFWall+ 3.5.3.

@haraldrudell's script works for me to fix the problem. I didn't even have to `chmod +x` - not sure what the point is as `. /data/tether` is sourcing it, not executing it, so execute bit isn't required.

How should the fix to AFWall look like? Will everyone have to use this script or is it as simple as adding `1052 dns_tether` to the list of apps?

**Comment by KJ7LNW** [comment]
@infinity0,

I had to enable mobile data for the `clat` app, which is id 1029.  Thats all it needed, now tethering works:

https://blog.dan.drown.org/clatd-on-android/

**Comment by Miroslavonhub** [comment]
sadly the above didnt work, maybe my rules point something out. tried everything, even did rules with the chatbot but devices hang up with message with obtaining ip. would be the happiest if someone knows how to get it to work. 
[afwallrules.txt](https://github.com/user-attachments/files/15906429/afwallrules.txt)
[iptables_on.txt](https://github.com/user-attachments/files/15906597/iptables_on.txt)
file left behind

**Comment by 0xzfs** [comment]
Sorry to bumping a closed issue, but a much simpler solution is to click 3 dots, 'set custom script' and in the first field add this (for every profile separately):

iptables -A 'afwall' -p udp -m udp --dport 53 -j ACCEPT
iptables -A 'afwall' -p udp -m udp --sport 53 -j ACCEPT

Now re-apply rules.

EDIT: works nicely on LinageOS, Android 14
