### ISSUE TITLE
Custom ip6tables nat rules cause error applying rules

### ISSUE THREAD

**Issue by jjakob** [ukanth/afwall#993]
NAT rules in custom script cause rule application to fail, probably due to no NAT chain.

17:21:02 command 'ip6tables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination [::1]:5354' exited with status 3
Output:
ip6tables v1.4.20: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.

Possible fixes could be:

1) add NAT chain if not present (could also be done by user if this error occurs and the app warns him)
2) fail gracefully on that particular rule only and continue adding all other rules, this guarantees a working firewall setup that a malformed custom script can't break

**Comment by tusch001** [comment]
I don't know if this could be your problem:

I have the same issue and the same error message when applying nat with iptables (IPv4) on one of my LineageOS 16 devices.
Also in my case in terminal 
system/bin/iptables -t nat -F
throws the same error.

Reading on the web in general comments said that the **kernel might be compiled without nat support** (although often referred to in linux os).

[Here somewhere down the comments](https://www.howtoforge.com/community/threads/iptables-table-does-not-exist-do-you-need-to-insmod.3196/) there are suggestions to find out if this is the case.

Just to let you know.

(I'm quite annoyed to be honest because I can't do anything about this. But one of the developers wrote in another post that he's trying to get orbot work together with the guys from the guardian project. Hopefully they are successful.)

**Comment by jjakob** [comment]
zcat /proc/config.gz | grep -i tables:
```
CONFIG_IP_MULTIPLE_TABLES=y
CONFIG_IPV6_MULTIPLE_TABLES=y
CONFIG_NETFILTER_XTABLES=y
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_ARPTABLES=y
CONFIG_IP6_NF_IPTABLES=y
CONFIG_BRIDGE_NF_EBTABLES=y
```
iptables -t nat works fine, just ip6tables throws this error. I've tried "lsmod" but it says  "No file /proc/modules: no such file or directory" so I'm not sure how to check which modules are loaded or available on Android.
This is on LineageOS 14.1 unofficial.

**Comment by h1z1** [comment]
Modules aren't enabled by default, everything is static.  Appears to be a problem with Lineage or your build.  No problems on Lightrom.

**Comment by jjakob** [comment]
Can you confirm that it works with these custom rules? If so, it must be my ROM, I'll try a different/newer one and the issue can be closed. Thanks.

Custom script:
ip6tables -t nat -A OUTPUT -p tcp --dport 53 -j DNAT --to-destination [::1]:5354
ip6tables -t nat -A OUTPUT -p udp --dport 53 -j DNAT --to-destination [::1]:5354

Shutdown script:
ip6tables -t nat -D OUTPUT -p tcp --dport 53 -j DNAT --to-destination [::1]:5354
ip6tables -t nat -D OUTPUT -p udp --dport 53 -j DNAT --to-destination [::1]:5354

**Comment by h1z1** [comment]
I can confirm those rules work yes.
