### ISSUE TITLE
AFWall blocking requests to .org domains using Wlan

### ISSUE THREAD

**Issue by hirrov** [ukanth/afwall#999]
Helo,

if AFWall is enabled access to all .org domains is blocked
(e.g. F-Droid store, Lineageos Updates), though access is whitelisted and permitted.

WLAN-connections work, when

    AFWall is disabled;
    or
    AFWall is enabled, but Lineage - Preferences - Use Private DNS is enabled -> by this bypassing Pihole’s filters obviously;
    or
    by cellular network of course.

I tried checking different preferences for AFWall. Nothing helped.
Seems AFWall changes any DNS requests which then are blocked by Pihole whyever.
But Logs in AFWall or Pihole don’t show any expedient hints.

My System: Lineage 16.0, rooted; AFWall newest version; 
local DNS-Server Pihole last version.

Please let me knwo how to solve this. Thanks in advance.

**Comment by CHEF-KOCH** [comment]
AFWall+ does not block specific TLD's, AFWall+ also does not changes your DNS settings. 


Since you mentioned "Private DNS and Pi-Hole" I assume your DNS restrict some .org domains.

If you test something make sure you use your real DNS and no Pi-Hole or any scripts etc. 

The solution is to provide useful information like a log otherwise it's nothing but guessing what could be wrong.

**Comment by HuiiBuh** [comment]
I tested it as well.
Without afwall enabled. org domains can be accessed. If you enable afwall. org domains cannot be accessed.
I have pinhole Installed in my network, but without afwall enabled everything works...
